// Hi-Fi's own words, in every language Sonora speaks.
//
// Only what this theme says and no other: the names of its components,
// the legends on its keys and the display's annunciators, and the lines
// its panels print. Everything the shared components say is in Sonora's
// own catalog. The i18n layer lays this over that catalog while Hi-Fi is
// the chosen theme.

const enUS = {
  'hifi.meter.peak': "Peak",
  'hifi.meter.balance': "Balance",
  'hifi.meter.phase': "Phase",
  'hifi.meter.dynamics': "Dynamics",
  'hifi.levelsUnavailable': "Levels can’t be shown for this source.",
  'hifi.vuMeters': "VU Meters",
  'hifi.levelDisplay': "Level display",
  'hifi.eqDisplay': "Graphic Equalizer",
  'hifi.reload': 'Reload',
  'hifi.fn.zones': "Zones",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Tape",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Setup",
  'hifi.function': "Function",
  'hifi.system': "System",
  'hifi.mixtape': "{name} Mixtape",
  'hifi.showControls': "Show the controls",
  'hifi.unit.preamp': "Control Amplifier",
  'hifi.unit.zones': "Zone Amplifier",
  'hifi.unit.tuner': "Source Tuner",
  'hifi.unit.tape': "Queue Deck",
  'hifi.unit.timer': "Program Timer",
  'hifi.unit.setup': "Rear Panel",
  'hifi.ann.shuffle': "Shuffle",
  'hifi.ann.repeat': "Repeat",
  'hifi.ann.repeatOne': "Repeat 1",
  'hifi.ann.crossfade': "X-Fade",
  'hifi.ann.sleep': "Sleep",
  'hifi.info': "Info",
  'hifi.link': "Link",
  'hifi.trim': "Trim",
  'hifi.zone': "Zone",
  'hifi.chooseZone': "Choose a zone",
  'hifi.noZone': "No zone selected",
  'hifi.select': "Select",
  'hifi.selectZone': "Select this zone",
  'hifi.party': "Party",
  'hifi.partyHint': "Party mode: every room of this system joins the zone in view",
  'hifi.dragToLink': "Drag a module's name plate onto another to link them.",
  'hifi.speakerSelector': "Speaker Selector",
  'hifi.output': "Plays to",
  'hifi.presets': "Presets",
  'hifi.preset': "Preset {n}",
  'hifi.memory': "Memory",
  'hifi.showInTuner': "Show in the tuner",
  'hifi.track': "Track",
  'hifi.rec': "Rec",
  'hifi.eject': "Eject",
  'hifi.cue': "Cue",
  'hifi.moreTracks': "{count} more tracks follow in the queue.",
  'hifi.newProgram': "New",
  'hifi.program': "Prog {n}",
  'hifi.queueEmptyBody': "Tune in something on the tuner, or add tracks with \"Add to End of Queue\".",
  'hifi.allServices': "All services",
  'hifi.allServicesGen': "All {gen} Services",
  'hifi.playOtherSystem': "That is on the {gen} system. Choose one of its rooms to play it.",
  'hifi.playingNow': "Playing {title}",
  'hifi.queuedNext': "Playing {title} next",
  'hifi.replacedQueue': "Queue replaced with {title}",
  'hifi.addedToQueue': "Added {title} to the queue",
  'hifi.selected': "{count} selected",
  'hifi.otherSystem': "On the {gen} system; choose one of its rooms to play from it",
  'hifi.filterServices': "Filter services",
  'hifi.musicSources': "Music Sources",
  'hifi.view': "View",
  'hifi.viewAuto': "Automatic",
  'hifi.viewGrid': "Grid",
  'hifi.viewList': "List",
  'hifi.services.none': "No music services are set up on this system yet.",
  'hifi.services.linked': "Linked in Sonora",
  'hifi.services.notLinked': "Set up in the Sonos app, not yet linked in Sonora",
  'hifi.alsoRemembered': "Also remembered but out of reach: {names}.",
  'hifi.quality': "Quality",
  'hifi.worst': "worst ms",
  'hifi.wired': "Wired",
  'hifi.serviceRemoved': "Removed {service}",
  'hifi.moveUp': "Move up",
  'hifi.moveDown': "Move down",
  'hifi.removeSelected': "Remove {count} selected",
  'hifi.queueSaved': "Saved the queue as \"{title}\"",
  'hifi.noPairCandidates': "No other unpaired speaker of this model.",
  'hifi.lineIn': "Line-In",
  'hifi.connected': "Connected",
  'hifi.nothingConnected': "Nothing connected",
  'hifi.none': "None",
  'hifi.thisRoom': "This room",
  'hifi.linkedWith': "Grouped with {room}",
  'hifi.linkAcrossSystems': "Rooms on different systems cannot be grouped together.",
  'hifi.open': "Open",
  'hifi.leaveGroup': "Take {room} out of the group",
  'hifi.noRooms': "No rooms in this system.",
  'hifi.diag.noAnswer': "no answer",
  'hifi.setup.account': "Sonos Account",
  'hifi.setup.services': "Music services",
  'hifi.setup.services.blurb': "The streaming services you've configured.",
  'hifi.setup.library': "Music library",
  'hifi.setup.library.blurb': 'Shared music folders on your network.',
  'hifi.setup.time': "Date and time",
  'hifi.setup.time.blurb': 'Clock and time zone settings.',
  'hifi.setup.systems': "Systems and rooms",
  'hifi.setup.systems.blurb': 'What devices Sonora sees on your network.',
  'hifi.setup.parental': "Content Filters",
  'hifi.setup.parental.blurb': 'Explicit content filtering.',
  'hifi.setup.s2': "Upgrade advisor",
  'hifi.setup.network': "Network check",
  'hifi.setup.network.blurb': 'Identify potential performance issues on your network.',
  'hifi.setup.appearance': "Appearance",
  'hifi.setup.appearance.blurb': "The theme Sonora wears and the language it speaks.",
  'hifi.setup.log': "Log",
  'hifi.setup.log.blurb': "What went wrong recently, newest first.",
}

const esES = {
  'hifi.meter.peak': "Pico",
  'hifi.meter.balance': "Balance",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dinámica",
  'hifi.levelsUnavailable': "No se pueden mostrar los niveles de esta fuente.",
  'hifi.vuMeters': "Vúmetros",
  'hifi.levelDisplay': "Indicador de nivel",
  'hifi.eqDisplay': "Ecualizador gráfico",
  'hifi.reload': 'Recargar',
  'hifi.fn.zones': "Zonas",
  'hifi.fn.tuner': "Sintonizador",
  'hifi.fn.tape': "Cinta",
  'hifi.fn.timer': "Temporizador",
  'hifi.fn.setup': "Ajustes",
  'hifi.function': "Función",
  'hifi.system': "Sistema",
  'hifi.mixtape': "Mixtape de {name}",
  'hifi.showControls': "Mostrar los controles",
  'hifi.unit.preamp': "Amplificador de control",
  'hifi.unit.zones': "Amplificador de zonas",
  'hifi.unit.tuner': "Sintonizador de fuentes",
  'hifi.unit.tape': "Pletina de la cola",
  'hifi.unit.timer': "Temporizador de programas",
  'hifi.unit.setup': "Panel trasero",
  'hifi.ann.shuffle': "Aleatorio",
  'hifi.ann.repeat': "Repetir",
  'hifi.ann.repeatOne': "Repetir 1",
  'hifi.ann.crossfade': "Fundido",
  'hifi.ann.sleep': "Dormir",
  'hifi.info': "Info",
  'hifi.link': "Enlazar",
  'hifi.trim': "Ajuste",
  'hifi.zone': "Zona",
  'hifi.chooseZone': "Elegir una zona",
  'hifi.noZone': "Ninguna zona seleccionada",
  'hifi.select': "Elegir",
  'hifi.selectZone': "Elegir esta zona",
  'hifi.party': "Fiesta",
  'hifi.partyHint': "Modo fiesta: todas las salas de este sistema se unen a la zona que está a la vista",
  'hifi.dragToLink': "Arrastra la placa con el nombre de un módulo sobre otro para enlazarlos.",
  'hifi.speakerSelector': "Selector de altavoces",
  'hifi.output': "Suena en",
  'hifi.presets': "Presintonías",
  'hifi.preset': "Presintonía {n}",
  'hifi.memory': "Memoria",
  'hifi.showInTuner': "Mostrar en el sintonizador",
  'hifi.track': "Pista",
  'hifi.rec': "Grabar",
  'hifi.eject': "Expulsar",
  'hifi.cue': "Localizar",
  'hifi.moreTracks': "Siguen {count} pistas más en la cola.",
  'hifi.newProgram': "Nuevo",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Sintoniza algo en el sintonizador o añade pistas con «Añadir al final de la cola».",
  'hifi.allServices': "Todos los servicios",
  'hifi.allServicesGen': "Todos los servicios de {gen}",
  'hifi.playOtherSystem': "Está en el sistema {gen}. Elige una de sus habitaciones para reproducirlo.",
  'hifi.playingNow': "Reproduciendo {title}",
  'hifi.queuedNext': "{title} sonará a continuación",
  'hifi.replacedQueue': "Cola sustituida por {title}",
  'hifi.addedToQueue': "{title} añadido a la cola",
  'hifi.selected': "{count} seleccionados",
  'hifi.otherSystem': "En el sistema {gen}; elige una de sus habitaciones para reproducir desde él",
  'hifi.filterServices': "Filtrar servicios",
  'hifi.musicSources': "Fuentes de música",
  'hifi.view': "Vista",
  'hifi.viewAuto': "Automática",
  'hifi.viewGrid': "Cuadrícula",
  'hifi.viewList': "Lista",
  'hifi.services.none': "Este sistema aún no tiene servicios de música configurados.",
  'hifi.services.linked': "Vinculado en Sonora",
  'hifi.services.notLinked': "Configurado en la app de Sonos, aún no vinculado en Sonora",
  'hifi.alsoRemembered': "También recordadas pero fuera de alcance: {names}.",
  'hifi.quality': "Calidad",
  'hifi.worst': "peor ms",
  'hifi.wired': "Por cable",
  'hifi.serviceRemoved': "{service} eliminado",
  'hifi.moveUp': "Subir",
  'hifi.moveDown': "Bajar",
  'hifi.removeSelected': "Quitar {count} seleccionadas",
  'hifi.queueSaved': "Cola guardada como \"{title}\"",
  'hifi.noPairCandidates': "No hay otro altavoz de este modelo sin emparejar.",
  'hifi.lineIn': "Entrada de línea",
  'hifi.connected': "Conectada",
  'hifi.nothingConnected': "Nada conectado",
  'hifi.none': "Ninguna",
  'hifi.thisRoom': "Esta habitación",
  'hifi.linkedWith': "Agrupada con {room}",
  'hifi.linkAcrossSystems': "No se pueden agrupar habitaciones de sistemas distintos.",
  'hifi.open': "Abrir",
  'hifi.leaveGroup': "Sacar {room} del grupo",
  'hifi.noRooms': "No hay habitaciones en este sistema.",
  'hifi.diag.noAnswer': "sin respuesta",
  'hifi.setup.account': "Cuenta de Sonos",
  'hifi.setup.services': "Servicios de música",
  'hifi.setup.services.blurb': 'Los servicios de streaming que has configurado.',
  'hifi.setup.library': "Biblioteca de música",
  'hifi.setup.library.blurb': 'Carpetas de música compartidas en tu red.',
  'hifi.setup.time': "Fecha y hora",
  'hifi.setup.time.blurb': 'Ajustes de reloj y zona horaria.',
  'hifi.setup.systems': "Sistemas y habitaciones",
  'hifi.setup.systems.blurb': 'Qué dispositivos ve Sonora en tu red.',
  'hifi.setup.parental': "Filtros de contenido",
  'hifi.setup.parental.blurb': 'Filtrado de contenido explícito.',
  'hifi.setup.s2': "Asesor de actualización",
  'hifi.setup.network': "Comprobación de red",
  'hifi.setup.network.blurb': 'Detecta posibles problemas de rendimiento en tu red.',
  'hifi.setup.appearance': "Apariencia",
  'hifi.setup.appearance.blurb': "El tema que lleva Sonora y el idioma en que habla.",
  'hifi.setup.log': "Registro",
  'hifi.setup.log.blurb': "Lo que ha fallado últimamente, lo más reciente primero.",
}

const huHU = {
  'hifi.meter.peak': "Csúcs",
  'hifi.meter.balance': "Balansz",
  'hifi.meter.phase': "Fázis",
  'hifi.meter.dynamics': "Dinamika",
  'hifi.levelsUnavailable': "Ennek a forrásnak a szintje nem jeleníthető meg.",
  'hifi.vuMeters': "VU-mérők",
  'hifi.levelDisplay': "Szintkijelző",
  'hifi.eqDisplay': "Grafikus hangszínszabályzó",
  'hifi.reload': 'Újratöltés',
  'hifi.fn.zones': "Zónák",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Kazetta",
  'hifi.fn.timer': "Időzítő",
  'hifi.fn.setup': "Beállítás",
  'hifi.function': "Funkció",
  'hifi.system': "Rendszer",
  'hifi.mixtape': "{name} mixtape",
  'hifi.showControls': "Vezérlők megjelenítése",
  'hifi.unit.preamp': "Vezérlőerősítő",
  'hifi.unit.zones': "Zónaerősítő",
  'hifi.unit.tuner': "Forrástuner",
  'hifi.unit.tape': "Várólista-magnó",
  'hifi.unit.timer': "Programidőzítő",
  'hifi.unit.setup': "Hátlap",
  'hifi.ann.shuffle': "Véletlen",
  'hifi.ann.repeat': "Ismétlés",
  'hifi.ann.repeatOne': "Ismétlés 1",
  'hifi.ann.crossfade': "Áttűnés",
  'hifi.ann.sleep': "Alvás",
  'hifi.info': "Infó",
  'hifi.link': "Összekötés",
  'hifi.trim': "Finomhangolás",
  'hifi.zone': "Zóna",
  'hifi.chooseZone': "Zóna kiválasztása",
  'hifi.noZone': "Nincs kiválasztott zóna",
  'hifi.select': "Kiválaszt",
  'hifi.selectZone': "Ennek a zónának a kiválasztása",
  'hifi.party': "Parti",
  'hifi.partyHint': "Partimód: a rendszer minden helyisége csatlakozik a látható zónához",
  'hifi.dragToLink': "Húzza egy modul névtábláját egy másikra az összekötésükhöz.",
  'hifi.speakerSelector': "Hangszóróválasztó",
  'hifi.output': "Itt szól",
  'hifi.presets': "Előbeállítások",
  'hifi.preset': "{n}. előbeállítás",
  'hifi.memory': "Memória",
  'hifi.showInTuner': "Megjelenítés a tunerben",
  'hifi.track': "Szám",
  'hifi.rec': "Felvétel",
  'hifi.eject': "Kiadás",
  'hifi.cue': "Ugrás",
  'hifi.moreTracks': "Még {count} szám következik a várólistán.",
  'hifi.newProgram': "Új",
  'hifi.program': "{n}. program",
  'hifi.queueEmptyBody': "Hangoljon be valamit a tunerrel, vagy adjon hozzá számokat a „Hozzáadás a várólista végéhez” paranccsal.",
  'hifi.allServices': "Minden szolgáltatás",
  'hifi.allServicesGen': "Minden {gen}-szolgáltatás",
  'hifi.playOtherSystem': "Ez a(z) {gen} rendszeren van. Válaszd ki egyik szobáját a lejátszáshoz.",
  'hifi.playingNow': "{title} lejátszása",
  'hifi.queuedNext': "{title} következik",
  'hifi.replacedQueue': "A sor helyére: {title}",
  'hifi.addedToQueue': "{title} a sor végére került",
  'hifi.selected': "{count} kijelölve",
  'hifi.otherSystem': "A(z) {gen} rendszeren; válaszd annak egy szobáját a lejátszáshoz",
  'hifi.filterServices': "Szolgáltatások szűrése",
  'hifi.musicSources': "Zeneforrások",
  'hifi.view': "Nézet",
  'hifi.viewAuto': "Automatikus",
  'hifi.viewGrid': "Rács",
  'hifi.viewList': "Lista",
  'hifi.services.none': "Ezen a rendszeren még nincs beállított zeneszolgáltatás.",
  'hifi.services.linked': "Összekapcsolva a Sonorával",
  'hifi.services.notLinked': "A Sonos alkalmazásban beállítva, a Sonorában még nincs összekapcsolva",
  'hifi.alsoRemembered': "Emlékszik rájuk, de nem éri el: {names}.",
  'hifi.quality': "Minőség",
  'hifi.worst': "legrosszabb ms",
  'hifi.wired': "Vezetékes",
  'hifi.serviceRemoved': "{service} eltávolítva",
  'hifi.moveUp': "Feljebb",
  'hifi.moveDown': "Lejjebb",
  'hifi.removeSelected': "{count} kijelölt eltávolítása",
  'hifi.queueSaved': "Sor elmentve „{title}” néven",
  'hifi.noPairCandidates': "Nincs másik párosítatlan hangszóró ebből a típusból.",
  'hifi.lineIn': "Vonalbemenet",
  'hifi.connected': "Csatlakoztatva",
  'hifi.nothingConnected': "Nincs csatlakoztatva semmi",
  'hifi.none': "Nincs",
  'hifi.thisRoom': "Ez a szoba",
  'hifi.linkedWith': "Csoportban: {room}",
  'hifi.linkAcrossSystems': "Különböző rendszerek szobái nem csoportosíthatók.",
  'hifi.open': "Megnyitás",
  'hifi.leaveGroup': "{room} kivétele a csoportból",
  'hifi.noRooms': "Ebben a rendszerben nincs szoba.",
  'hifi.diag.noAnswer': "nincs válasz",
  'hifi.setup.account': "Sonos-fiók",
  'hifi.setup.services': "Zeneszolgáltatások",
  'hifi.setup.services.blurb': 'A beállított streamingszolgáltatások.',
  'hifi.setup.library': "Zenekönyvtár",
  'hifi.setup.library.blurb': 'Megosztott zenemappák a hálózaton.',
  'hifi.setup.time': "Dátum és idő",
  'hifi.setup.time.blurb': 'Óra és időzóna beállításai.',
  'hifi.setup.systems': "Rendszerek és szobák",
  'hifi.setup.systems.blurb': 'Milyen eszközöket lát a Sonora a hálózaton.',
  'hifi.setup.parental': "Tartalomszűrők",
  'hifi.setup.parental.blurb': 'Szókimondó tartalmak szűrése.',
  'hifi.setup.s2': "Frissítési tanácsadó",
  'hifi.setup.network': "Hálózat-ellenőrzés",
  'hifi.setup.network.blurb': 'A hálózat lehetséges teljesítményproblémáinak feltárása.',
  'hifi.setup.appearance': "Megjelenés",
  'hifi.setup.appearance.blurb': "A téma, amit a Sonora visel, és a nyelv, amin beszél.",
  'hifi.setup.log': "Napló",
  'hifi.setup.log.blurb': "Ami mostanában elromlott, a legújabb elöl.",
}

const frFR = {
  'hifi.meter.peak': "Pic",
  'hifi.meter.balance': "Balance",
  'hifi.meter.phase': "Phase",
  'hifi.meter.dynamics': "Dynamique",
  'hifi.levelsUnavailable': "Impossible d’afficher les niveaux de cette source.",
  'hifi.vuMeters': "Vumètres",
  'hifi.levelDisplay': "Affichage des niveaux",
  'hifi.eqDisplay': "Égaliseur graphique",
  'hifi.reload': 'Recharger',
  'hifi.fn.zones': "Zones",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Cassette",
  'hifi.fn.timer': "Minuterie",
  'hifi.fn.setup': "Réglages",
  'hifi.function': "Fonction",
  'hifi.system': "Système",
  'hifi.mixtape': "Mixtape {name}",
  'hifi.showControls': "Afficher les commandes",
  'hifi.unit.preamp': "Amplificateur de commande",
  'hifi.unit.zones': "Amplificateur de zones",
  'hifi.unit.tuner': "Tuner de sources",
  'hifi.unit.tape': "Platine de la file",
  'hifi.unit.timer': "Minuterie de programmes",
  'hifi.unit.setup': "Panneau arrière",
  'hifi.ann.shuffle': "Aléatoire",
  'hifi.ann.repeat': "Répéter",
  'hifi.ann.repeatOne': "Répéter 1",
  'hifi.ann.crossfade': "Fondu",
  'hifi.ann.sleep': "Veille",
  'hifi.info': "Infos",
  'hifi.link': "Lier",
  'hifi.trim': "Réglage fin",
  'hifi.zone': "Zone",
  'hifi.chooseZone': "Choisir une zone",
  'hifi.noZone': "Aucune zone choisie",
  'hifi.select': "Choisir",
  'hifi.selectZone': "Choisir cette zone",
  'hifi.party': "Fête",
  'hifi.partyHint': "Mode fête : toutes les pièces de ce système rejoignent la zone affichée",
  'hifi.dragToLink': "Faites glisser la plaque d’un module sur un autre pour les lier.",
  'hifi.speakerSelector': "Sélecteur d’enceintes",
  'hifi.output': "Joue dans",
  'hifi.presets': "Présélections",
  'hifi.preset': "Présélection {n}",
  'hifi.memory': "Mémoire",
  'hifi.showInTuner': "Afficher dans le tuner",
  'hifi.track': "Piste",
  'hifi.rec': "Enreg.",
  'hifi.eject': "Éjecter",
  'hifi.cue': "Repérer",
  'hifi.moreTracks': "{count} pistes de plus suivent dans la file.",
  'hifi.newProgram': "Nouveau",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Réglez le tuner sur quelque chose, ou ajoutez des pistes avec « Ajouter à la fin de la file d’attente ».",
  'hifi.allServices': "Tous les services",
  'hifi.allServicesGen': "Tous les services {gen}",
  'hifi.playOtherSystem': "C'est sur le système {gen}. Choisis l'une de ses pièces pour le lire.",
  'hifi.playingNow': "Lecture de {title}",
  'hifi.queuedNext': "{title} sera lu ensuite",
  'hifi.replacedQueue': "File d’attente remplacée par {title}",
  'hifi.addedToQueue': "{title} a été ajouté à la file d’attente",
  'hifi.selected': "{count} sélectionnés",
  'hifi.otherSystem': "Sur le système {gen} ; choisis l’une de ses pièces pour y lire",
  'hifi.filterServices': "Filtrer les services",
  'hifi.musicSources': "Sources de musique",
  'hifi.view': "Affichage",
  'hifi.viewAuto': "Automatique",
  'hifi.viewGrid': "Grille",
  'hifi.viewList': "Liste",
  'hifi.services.none': "Aucun service de musique n’est encore configuré sur ce système.",
  'hifi.services.linked': "Associé dans Sonora",
  'hifi.services.notLinked': "Configuré dans l’application Sonos, pas encore associé dans Sonora",
  'hifi.alsoRemembered': "Également en mémoire mais hors de portée : {names}.",
  'hifi.quality': "Qualité",
  'hifi.worst': "pire ms",
  'hifi.wired': "Filaire",
  'hifi.serviceRemoved': "{service} a été supprimé",
  'hifi.moveUp': "Monter",
  'hifi.moveDown': "Descendre",
  'hifi.removeSelected': "Supprimer les {count} sélectionnés",
  'hifi.queueSaved': "File d’attente enregistrée sous « {title} »",
  'hifi.noPairCandidates': "Aucune autre enceinte non appairée de ce modèle.",
  'hifi.lineIn': "Entrée ligne",
  'hifi.connected': "Connectée",
  'hifi.nothingConnected': "Rien de connecté",
  'hifi.none': "Aucun",
  'hifi.thisRoom': "Cette pièce",
  'hifi.linkedWith': "Groupée avec {room}",
  'hifi.linkAcrossSystems': "Des pièces de systèmes différents ne peuvent pas être groupées.",
  'hifi.open': "Ouvrir",
  'hifi.leaveGroup': "Retirer {room} du groupe",
  'hifi.noRooms': "Aucune pièce dans ce système.",
  'hifi.diag.noAnswer': "aucune réponse",
  'hifi.setup.account': "Compte Sonos",
  'hifi.setup.services': "Services de musique",
  'hifi.setup.services.blurb': 'Les services de streaming que vous avez configurés.',
  'hifi.setup.library': "Bibliothèque musicale",
  'hifi.setup.library.blurb': 'Les dossiers de musique partagés sur votre réseau.',
  'hifi.setup.time': "Date et heure",
  'hifi.setup.time.blurb': "Réglages de l'horloge et du fuseau horaire.",
  'hifi.setup.systems': "Systèmes et pièces",
  'hifi.setup.systems.blurb': 'Les appareils que Sonora voit sur votre réseau.',
  'hifi.setup.parental': "Filtres de contenu",
  'hifi.setup.parental.blurb': 'Filtrage du contenu explicite.',
  'hifi.setup.s2': "Conseiller de mise à niveau",
  'hifi.setup.network': "Test du réseau",
  'hifi.setup.network.blurb': 'Repérez les problèmes de performances possibles sur votre réseau.',
  'hifi.setup.appearance': "Apparence",
  'hifi.setup.appearance.blurb': "Le thème que porte Sonora et la langue qu’il parle.",
  'hifi.setup.log': "Journal",
  'hifi.setup.log.blurb': "Ce qui s’est mal passé récemment, du plus récent au plus ancien.",
}

const deDE = {
  'hifi.meter.peak': "Spitze",
  'hifi.meter.balance': "Balance",
  'hifi.meter.phase': "Phase",
  'hifi.meter.dynamics': "Dynamik",
  'hifi.levelsUnavailable': "Für diese Quelle können keine Pegel angezeigt werden.",
  'hifi.vuMeters': "VU-Meter",
  'hifi.levelDisplay': "Pegelanzeige",
  'hifi.eqDisplay': "Grafischer Equalizer",
  'hifi.reload': 'Neu laden',
  'hifi.fn.zones': "Zonen",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Kassette",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Einstellungen",
  'hifi.function': "Funktion",
  'hifi.system': "System",
  'hifi.mixtape': "{name} Mixtape",
  'hifi.showControls': "Bedienelemente anzeigen",
  'hifi.unit.preamp': "Steuerverstärker",
  'hifi.unit.zones': "Zonenverstärker",
  'hifi.unit.tuner': "Quellen-Tuner",
  'hifi.unit.tape': "Warteschlangen-Deck",
  'hifi.unit.timer': "Programm-Timer",
  'hifi.unit.setup': "Rückseite",
  'hifi.ann.shuffle': "Zufall",
  'hifi.ann.repeat': "Wiederholen",
  'hifi.ann.repeatOne': "Wiederholen 1",
  'hifi.ann.crossfade': "Überblenden",
  'hifi.ann.sleep': "Schlaf",
  'hifi.info': "Info",
  'hifi.link': "Verbinden",
  'hifi.trim': "Feinregler",
  'hifi.zone': "Zone",
  'hifi.chooseZone': "Zone wählen",
  'hifi.noZone': "Keine Zone gewählt",
  'hifi.select': "Wählen",
  'hifi.selectZone': "Diese Zone wählen",
  'hifi.party': "Party",
  'hifi.partyHint': "Partymodus: Alle Räume dieses Systems schließen sich der gezeigten Zone an",
  'hifi.dragToLink': "Ziehen Sie das Namensschild eines Moduls auf ein anderes, um beide zu verbinden.",
  'hifi.speakerSelector': "Lautsprecherwahl",
  'hifi.output': "Spielt in",
  'hifi.presets': "Senderspeicher",
  'hifi.preset': "Speicher {n}",
  'hifi.memory': "Verlauf",
  'hifi.showInTuner': "Im Tuner zeigen",
  'hifi.track': "Titel",
  'hifi.rec': "Aufn.",
  'hifi.eject': "Auswerfen",
  'hifi.cue': "Suchlauf",
  'hifi.moreTracks': "In der Warteschlange folgen noch {count} Titel.",
  'hifi.newProgram': "Neu",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Stellen Sie am Tuner etwas ein oder fügen Sie Titel mit „Ans Ende der Warteschlange“ hinzu.",
  'hifi.allServices': "Alle Dienste",
  'hifi.allServicesGen': "Alle {gen}-Dienste",
  'hifi.playOtherSystem': "Das liegt im {gen}-System. Wähle einen seiner Räume, um es abzuspielen.",
  'hifi.playingNow': "{title} läuft",
  'hifi.queuedNext': "{title} läuft als Nächstes",
  'hifi.replacedQueue': "Warteschlange durch {title} ersetzt",
  'hifi.addedToQueue': "{title} wurde zur Warteschlange hinzugefügt",
  'hifi.selected': "{count} ausgewählt",
  'hifi.otherSystem': "Auf dem {gen}-System; wähle einen seiner Räume, um daraus abzuspielen",
  'hifi.filterServices': "Dienste filtern",
  'hifi.musicSources': "Musikquellen",
  'hifi.view': "Ansicht",
  'hifi.viewAuto': "Automatisch",
  'hifi.viewGrid': "Raster",
  'hifi.viewList': "Liste",
  'hifi.services.none': "Auf diesem System sind noch keine Musikdienste eingerichtet.",
  'hifi.services.linked': "In Sonora verknüpft",
  'hifi.services.notLinked': "In der Sonos-App eingerichtet, in Sonora noch nicht verknüpft",
  'hifi.alsoRemembered': "Ebenfalls bekannt, aber außer Reichweite: {names}.",
  'hifi.quality': "Qualität",
  'hifi.worst': "schlechteste ms",
  'hifi.wired': "Kabelgebunden",
  'hifi.serviceRemoved': "{service} entfernt",
  'hifi.moveUp': "Nach oben",
  'hifi.moveDown': "Nach unten",
  'hifi.removeSelected': "{count} ausgewählte entfernen",
  'hifi.queueSaved': "Warteschlange als „{title}“ gespeichert",
  'hifi.noPairCandidates': "Kein weiterer ungepaarter Lautsprecher dieses Modells.",
  'hifi.lineIn': "Line-In",
  'hifi.connected': "Verbunden",
  'hifi.nothingConnected': "Nichts verbunden",
  'hifi.none': "Keine",
  'hifi.thisRoom': "Dieser Raum",
  'hifi.linkedWith': "Gruppiert mit {room}",
  'hifi.linkAcrossSystems': "Räume verschiedener Systeme lassen sich nicht gruppieren.",
  'hifi.open': "Öffnen",
  'hifi.leaveGroup': "{room} aus der Gruppe nehmen",
  'hifi.noRooms': "Keine Räume in diesem System.",
  'hifi.diag.noAnswer': "keine Antwort",
  'hifi.setup.account': "Sonos-Konto",
  'hifi.setup.services': "Musikdienste",
  'hifi.setup.services.blurb': 'Die Streamingdienste, die Sie eingerichtet haben.',
  'hifi.setup.library': "Musikbibliothek",
  'hifi.setup.library.blurb': 'Freigegebene Musikordner in Ihrem Netzwerk.',
  'hifi.setup.time': "Datum und Uhrzeit",
  'hifi.setup.time.blurb': 'Uhr- und Zeitzoneneinstellungen.',
  'hifi.setup.systems': "Systeme und Räume",
  'hifi.setup.systems.blurb': 'Welche Geräte Sonora in Ihrem Netzwerk sieht.',
  'hifi.setup.parental': "Inhaltsfilter",
  'hifi.setup.parental.blurb': 'Filter für explizite Inhalte.',
  'hifi.setup.s2': "Upgrade-Berater",
  'hifi.setup.network': "Netzwerkprüfung",
  'hifi.setup.network.blurb': 'Mögliche Leistungsprobleme in Ihrem Netzwerk erkennen.',
  'hifi.setup.appearance': "Erscheinungsbild",
  'hifi.setup.appearance.blurb': "Das Design, das Sonora trägt, und die Sprache, die es spricht.",
  'hifi.setup.log': "Protokoll",
  'hifi.setup.log.blurb': "Was zuletzt schiefgelaufen ist, das Neueste zuerst.",
}

const itIT = {
  'hifi.meter.peak': "Picco",
  'hifi.meter.balance': "Bilanciamento",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dinamica",
  'hifi.levelsUnavailable': "Non è possibile mostrare i livelli di questa sorgente.",
  'hifi.vuMeters': "Indicatori VU",
  'hifi.levelDisplay': "Indicatore di livello",
  'hifi.eqDisplay': "Equalizzatore grafico",
  'hifi.reload': 'Ricarica',
  'hifi.fn.zones': "Zone",
  'hifi.fn.tuner': "Sintonizzatore",
  'hifi.fn.tape': "Cassetta",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Impostazioni",
  'hifi.function': "Funzione",
  'hifi.system': "Sistema",
  'hifi.mixtape': "Mixtape {name}",
  'hifi.showControls': "Mostra i controlli",
  'hifi.unit.preamp': "Amplificatore di controllo",
  'hifi.unit.zones': "Amplificatore di zona",
  'hifi.unit.tuner': "Sintonizzatore di sorgenti",
  'hifi.unit.tape': "Piastra della coda",
  'hifi.unit.timer': "Timer di programmazione",
  'hifi.unit.setup': "Pannello posteriore",
  'hifi.ann.shuffle': "Casuale",
  'hifi.ann.repeat': "Ripeti",
  'hifi.ann.repeatOne': "Ripeti 1",
  'hifi.ann.crossfade': "Dissolvenza",
  'hifi.ann.sleep': "Sonno",
  'hifi.info': "Info",
  'hifi.link': "Collega",
  'hifi.trim': "Regolazione",
  'hifi.zone': "Zona",
  'hifi.chooseZone': "Scegli una zona",
  'hifi.noZone': "Nessuna zona scelta",
  'hifi.select': "Scegli",
  'hifi.selectZone': "Scegli questa zona",
  'hifi.party': "Festa",
  'hifi.partyHint': "Modalità festa: tutte le stanze di questo sistema si uniscono alla zona in vista",
  'hifi.dragToLink': "Trascina la targhetta di un modulo su un altro per collegarli.",
  'hifi.speakerSelector': "Selettore diffusori",
  'hifi.output': "Suona in",
  'hifi.presets': "Preselezioni",
  'hifi.preset': "Preselezione {n}",
  'hifi.memory': "Memoria",
  'hifi.showInTuner': "Mostra nel sintonizzatore",
  'hifi.track': "Brano",
  'hifi.rec': "Reg.",
  'hifi.eject': "Espelli",
  'hifi.cue': "Cerca",
  'hifi.moreTracks': "Nella coda seguono altri {count} brani.",
  'hifi.newProgram': "Nuovo",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Sintonizza qualcosa sul sintonizzatore, oppure aggiungi brani con «Aggiungi in fondo alla coda».",
  'hifi.allServices': "Tutti i servizi",
  'hifi.allServicesGen': "Tutti i servizi {gen}",
  'hifi.playOtherSystem': "Si trova nel sistema {gen}. Scegli una delle sue stanze per riprodurlo.",
  'hifi.playingNow': "In riproduzione {title}",
  'hifi.queuedNext': "{title} sarà riprodotto dopo",
  'hifi.replacedQueue': "Coda sostituita con {title}",
  'hifi.addedToQueue': "{title} è stato aggiunto alla coda",
  'hifi.selected': "{count} selezionati",
  'hifi.otherSystem': "Sul sistema {gen}; scegli una delle sue stanze per riprodurre da lì",
  'hifi.filterServices': "Filtra i servizi",
  'hifi.musicSources': "Sorgenti musicali",
  'hifi.view': "Vista",
  'hifi.viewAuto': "Automatica",
  'hifi.viewGrid': "Griglia",
  'hifi.viewList': "Elenco",
  'hifi.services.none': "Su questo sistema non è ancora configurato alcun servizio musicale.",
  'hifi.services.linked': "Collegato in Sonora",
  'hifi.services.notLinked': "Configurato nell’app Sonos, non ancora collegato in Sonora",
  'hifi.alsoRemembered': "Ricordati ma fuori portata: {names}.",
  'hifi.quality': "Qualità",
  'hifi.worst': "ms peggiore",
  'hifi.wired': "Cablato",
  'hifi.serviceRemoved': "{service} rimosso",
  'hifi.moveUp': "Sposta su",
  'hifi.moveDown': "Sposta giù",
  'hifi.removeSelected': "Rimuovi {count} selezionati",
  'hifi.queueSaved': "Coda salvata come «{title}»",
  'hifi.noPairCandidates': "Nessun altro speaker non abbinato di questo modello.",
  'hifi.lineIn': "Ingresso linea",
  'hifi.connected': "Collegato",
  'hifi.nothingConnected': "Niente collegato",
  'hifi.none': "Nessuna",
  'hifi.thisRoom': "Questa stanza",
  'hifi.linkedWith': "Raggruppata con {room}",
  'hifi.linkAcrossSystems': "Stanze di sistemi diversi non possono essere raggruppate.",
  'hifi.open': "Apri",
  'hifi.leaveGroup': "Togli {room} dal gruppo",
  'hifi.noRooms': "Nessuna stanza in questo sistema.",
  'hifi.diag.noAnswer': "nessuna risposta",
  'hifi.setup.account': "Account Sonos",
  'hifi.setup.services': "Servizi musicali",
  'hifi.setup.services.blurb': 'I servizi di streaming che hai configurato.',
  'hifi.setup.library': "Libreria musicale",
  'hifi.setup.library.blurb': 'Cartelle musicali condivise sulla tua rete.',
  'hifi.setup.time': "Data e ora",
  'hifi.setup.time.blurb': 'Impostazioni di orologio e fuso orario.',
  'hifi.setup.systems': "Sistemi e stanze",
  'hifi.setup.systems.blurb': 'Quali dispositivi vede Sonora sulla tua rete.',
  'hifi.setup.parental': "Filtri dei contenuti",
  'hifi.setup.parental.blurb': 'Filtro dei contenuti espliciti.',
  'hifi.setup.s2': "Consulente per l’aggiornamento",
  'hifi.setup.network': "Verifica della rete",
  'hifi.setup.network.blurb': 'Individua possibili problemi di prestazioni sulla tua rete.',
  'hifi.setup.appearance': "Aspetto",
  'hifi.setup.appearance.blurb': "Il tema che indossa Sonora e la lingua che parla.",
  'hifi.setup.log': "Registro",
  'hifi.setup.log.blurb': "Cosa è andato storto di recente, dal più nuovo.",
}

const ptBR = {
  'hifi.meter.peak': "Pico",
  'hifi.meter.balance': "Balanço",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dinâmica",
  'hifi.levelsUnavailable': "Não é possível mostrar os níveis desta fonte.",
  'hifi.vuMeters': "Medidores VU",
  'hifi.levelDisplay': "Indicador de nível",
  'hifi.eqDisplay': "Equalizador gráfico",
  'hifi.reload': 'Recarregar',
  'hifi.fn.zones': "Zonas",
  'hifi.fn.tuner': "Sintonizador",
  'hifi.fn.tape': "Fita",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Ajustes",
  'hifi.function': "Função",
  'hifi.system': "Sistema",
  'hifi.mixtape': "Mixtape {name}",
  'hifi.showControls': "Mostrar os controles",
  'hifi.unit.preamp': "Amplificador de controle",
  'hifi.unit.zones': "Amplificador de zonas",
  'hifi.unit.tuner': "Sintonizador de fontes",
  'hifi.unit.tape': "Deck da fila",
  'hifi.unit.timer': "Timer de programas",
  'hifi.unit.setup': "Painel traseiro",
  'hifi.ann.shuffle': "Aleatório",
  'hifi.ann.repeat': "Repetir",
  'hifi.ann.repeatOne': "Repetir 1",
  'hifi.ann.crossfade': "Transição",
  'hifi.ann.sleep': "Dormir",
  'hifi.info': "Info",
  'hifi.link': "Ligar",
  'hifi.trim': "Ajuste fino",
  'hifi.zone': "Zona",
  'hifi.chooseZone': "Escolher uma zona",
  'hifi.noZone': "Nenhuma zona escolhida",
  'hifi.select': "Escolher",
  'hifi.selectZone': "Escolher esta zona",
  'hifi.party': "Festa",
  'hifi.partyHint': "Modo festa: todos os ambientes deste sistema se juntam à zona em vista",
  'hifi.dragToLink': "Arraste a plaqueta de nome de um módulo sobre outro para ligá-los.",
  'hifi.speakerSelector': "Seletor de caixas",
  'hifi.output': "Toca em",
  'hifi.presets': "Predefinições",
  'hifi.preset': "Predefinição {n}",
  'hifi.memory': "Memória",
  'hifi.showInTuner': "Mostrar no sintonizador",
  'hifi.track': "Faixa",
  'hifi.rec': "Gravar",
  'hifi.eject': "Ejetar",
  'hifi.cue': "Localizar",
  'hifi.moreTracks': "Mais {count} faixas seguem na fila.",
  'hifi.newProgram': "Novo",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Sintonize algo no sintonizador ou adicione faixas com \"Adicionar ao fim da fila\".",
  'hifi.allServices': "Todos os serviços",
  'hifi.allServicesGen': "Todos os serviços do {gen}",
  'hifi.playOtherSystem': "Isso está no sistema {gen}. Escolha um dos ambientes dele para tocar.",
  'hifi.playingNow': "Tocando {title}",
  'hifi.queuedNext': "{title} toca em seguida",
  'hifi.replacedQueue': "Fila substituída por {title}",
  'hifi.addedToQueue': "{title} foi adicionado à fila",
  'hifi.selected': "{count} selecionados",
  'hifi.otherSystem': "No sistema {gen}; escolha um dos cômodos dele para tocar a partir daí",
  'hifi.filterServices': "Filtrar serviços",
  'hifi.musicSources': "Fontes de música",
  'hifi.view': "Visualização",
  'hifi.viewAuto': "Automática",
  'hifi.viewGrid': "Grade",
  'hifi.viewList': "Lista",
  'hifi.services.none': "Ainda não há serviços de música configurados neste sistema.",
  'hifi.services.linked': "Vinculado no Sonora",
  'hifi.services.notLinked': "Configurado no aplicativo Sonos, ainda não vinculado no Sonora",
  'hifi.alsoRemembered': "Também lembrados, mas fora de alcance: {names}.",
  'hifi.quality': "Qualidade",
  'hifi.worst': "pior ms",
  'hifi.wired': "Com fio",
  'hifi.serviceRemoved': "{service} removido",
  'hifi.moveUp': "Mover para cima",
  'hifi.moveDown': "Mover para baixo",
  'hifi.removeSelected': "Remover {count} selecionados",
  'hifi.queueSaved': "Fila salva como “{title}”",
  'hifi.noPairCandidates': "Nenhuma outra caixa de som sem par deste modelo.",
  'hifi.lineIn': "Entrada de linha",
  'hifi.connected': "Conectado",
  'hifi.nothingConnected': "Nada conectado",
  'hifi.none': "Nenhum",
  'hifi.thisRoom': "Este cômodo",
  'hifi.linkedWith': "Agrupado com {room}",
  'hifi.linkAcrossSystems': "Cômodos de sistemas diferentes não podem ser agrupados.",
  'hifi.open': "Abrir",
  'hifi.leaveGroup': "Tirar {room} do grupo",
  'hifi.noRooms': "Nenhum cômodo neste sistema.",
  'hifi.diag.noAnswer': "sem resposta",
  'hifi.setup.account': "Conta Sonos",
  'hifi.setup.services': "Serviços de música",
  'hifi.setup.services.blurb': 'Os serviços de streaming que você configurou.',
  'hifi.setup.library': "Biblioteca musical",
  'hifi.setup.library.blurb': 'Pastas de música compartilhadas na sua rede.',
  'hifi.setup.time': "Data e hora",
  'hifi.setup.time.blurb': 'Configurações de relógio e fuso horário.',
  'hifi.setup.systems': "Sistemas e cômodos",
  'hifi.setup.systems.blurb': 'Quais dispositivos o Sonora vê na sua rede.',
  'hifi.setup.parental': "Filtros de conteúdo",
  'hifi.setup.parental.blurb': 'Filtragem de conteúdo explícito.',
  'hifi.setup.s2': "Consultor de atualização",
  'hifi.setup.network': "Verificação da rede",
  'hifi.setup.network.blurb': 'Identifique possíveis problemas de desempenho na sua rede.',
  'hifi.setup.appearance': "Aparência",
  'hifi.setup.appearance.blurb': "O tema que o Sonora veste e o idioma que ele fala.",
  'hifi.setup.log': "Registro",
  'hifi.setup.log.blurb': "O que deu errado recentemente, do mais novo ao mais antigo.",
}

const nlNL = {
  'hifi.meter.peak': "Piek",
  'hifi.meter.balance': "Balans",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dynamiek",
  'hifi.levelsUnavailable': "Voor deze bron kunnen geen niveaus worden getoond.",
  'hifi.vuMeters': "VU-meters",
  'hifi.levelDisplay': "Niveauweergave",
  'hifi.eqDisplay': "Grafische equalizer",
  'hifi.reload': 'Opnieuw laden',
  'hifi.fn.zones': "Zones",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Cassette",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Instellingen",
  'hifi.function': "Functie",
  'hifi.system': "Systeem",
  'hifi.mixtape': "{name} mixtape",
  'hifi.showControls': "Bediening tonen",
  'hifi.unit.preamp': "Regelversterker",
  'hifi.unit.zones': "Zoneversterker",
  'hifi.unit.tuner': "Bronnentuner",
  'hifi.unit.tape': "Wachtrijdeck",
  'hifi.unit.timer': "Programmatimer",
  'hifi.unit.setup': "Achterpaneel",
  'hifi.ann.shuffle': "Willekeurig",
  'hifi.ann.repeat': "Herhalen",
  'hifi.ann.repeatOne': "Herhaal 1",
  'hifi.ann.crossfade': "Crossfade",
  'hifi.ann.sleep': "Slaap",
  'hifi.info': "Info",
  'hifi.link': "Koppelen",
  'hifi.trim': "Fijnregeling",
  'hifi.zone': "Zone",
  'hifi.chooseZone': "Kies een zone",
  'hifi.noZone': "Geen zone gekozen",
  'hifi.select': "Kiezen",
  'hifi.selectZone': "Deze zone kiezen",
  'hifi.party': "Feest",
  'hifi.partyHint': "Feestmodus: alle kamers van dit systeem sluiten aan bij de zone in beeld",
  'hifi.dragToLink': "Sleep het naamplaatje van een module op een andere om ze te koppelen.",
  'hifi.speakerSelector': "Luidsprekerkeuze",
  'hifi.output': "Speelt in",
  'hifi.presets': "Voorkeuzes",
  'hifi.preset': "Voorkeuze {n}",
  'hifi.memory': "Geheugen",
  'hifi.showInTuner': "Tonen in de tuner",
  'hifi.track': "Nummer",
  'hifi.rec': "Opn.",
  'hifi.eject': "Uitwerpen",
  'hifi.cue': "Zoeken",
  'hifi.moreTracks': "Er volgen nog {count} nummers in de wachtrij.",
  'hifi.newProgram': "Nieuw",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Stem de tuner op iets af, of voeg nummers toe met ‘Achteraan de wachtrij zetten’.",
  'hifi.allServices': "Alle diensten",
  'hifi.allServicesGen': "Alle {gen}-diensten",
  'hifi.playOtherSystem': "Dat staat op het {gen}-systeem. Kies een van zijn ruimtes om het af te spelen.",
  'hifi.playingNow': "{title} speelt",
  'hifi.queuedNext': "{title} speelt hierna",
  'hifi.replacedQueue': "Wachtrij vervangen door {title}",
  'hifi.addedToQueue': "{title} is aan de wachtrij toegevoegd",
  'hifi.selected': "{count} geselecteerd",
  'hifi.otherSystem': "Op het {gen}-systeem; kies een van de ruimtes daarvan om er vanaf te spelen",
  'hifi.filterServices': "Diensten filteren",
  'hifi.musicSources': "Muziekbronnen",
  'hifi.view': "Weergave",
  'hifi.viewAuto': "Automatisch",
  'hifi.viewGrid': "Raster",
  'hifi.viewList': "Lijst",
  'hifi.services.none': "Op dit systeem zijn nog geen muziekdiensten ingesteld.",
  'hifi.services.linked': "Gekoppeld in Sonora",
  'hifi.services.notLinked': "Ingesteld in de Sonos-app, nog niet gekoppeld in Sonora",
  'hifi.alsoRemembered': "Ook bekend maar buiten bereik: {names}.",
  'hifi.quality': "Kwaliteit",
  'hifi.worst': "slechtste ms",
  'hifi.wired': "Bedraad",
  'hifi.serviceRemoved': "{service} verwijderd",
  'hifi.moveUp': "Omhoog",
  'hifi.moveDown': "Omlaag",
  'hifi.removeSelected': "{count} geselecteerde verwijderen",
  'hifi.queueSaved': "Wachtrij opgeslagen als ‘{title}’",
  'hifi.noPairCandidates': "Geen andere ongekoppelde speaker van dit model.",
  'hifi.lineIn': "Lijningang",
  'hifi.connected': "Verbonden",
  'hifi.nothingConnected': "Niets verbonden",
  'hifi.none': "Geen",
  'hifi.thisRoom': "Deze ruimte",
  'hifi.linkedWith': "Gegroepeerd met {room}",
  'hifi.linkAcrossSystems': "Ruimtes van verschillende systemen kunnen niet worden gegroepeerd.",
  'hifi.open': "Openen",
  'hifi.leaveGroup': "{room} uit de groep halen",
  'hifi.noRooms': "Geen ruimtes in dit systeem.",
  'hifi.diag.noAnswer': "geen antwoord",
  'hifi.setup.account': "Sonos-account",
  'hifi.setup.services': "Muziekdiensten",
  'hifi.setup.services.blurb': 'De streamingdiensten die je hebt ingesteld.',
  'hifi.setup.library': "Muziekbibliotheek",
  'hifi.setup.library.blurb': 'Gedeelde muziekmappen op je netwerk.',
  'hifi.setup.time': "Datum en tijd",
  'hifi.setup.time.blurb': 'Instellingen voor klok en tijdzone.',
  'hifi.setup.systems': "Systemen en ruimtes",
  'hifi.setup.systems.blurb': 'Welke apparaten Sonora op je netwerk ziet.',
  'hifi.setup.parental': "Inhoudsfilters",
  'hifi.setup.parental.blurb': 'Filteren van expliciete inhoud.',
  'hifi.setup.s2': "Upgradeadviseur",
  'hifi.setup.network': "Netwerkcontrole",
  'hifi.setup.network.blurb': 'Spoor mogelijke prestatieproblemen op je netwerk op.',
  'hifi.setup.appearance': "Weergave",
  'hifi.setup.appearance.blurb': "Het thema dat Sonora draagt en de taal die het spreekt.",
  'hifi.setup.log': "Logboek",
  'hifi.setup.log.blurb': "Wat er onlangs misging, nieuwste eerst.",
}

const ukUA = {
  'hifi.meter.peak': "Пік",
  'hifi.meter.balance': "Баланс",
  'hifi.meter.phase': "Фаза",
  'hifi.meter.dynamics': "Динаміка",
  'hifi.levelsUnavailable': "Для цього джерела рівні показати не можна.",
  'hifi.vuMeters': "VU-індикатори",
  'hifi.levelDisplay': "Індикатор рівня",
  'hifi.eqDisplay': "Графічний еквалайзер",
  'hifi.reload': 'Оновити',
  'hifi.fn.zones': "Зони",
  'hifi.fn.tuner': "Тюнер",
  'hifi.fn.tape': "Касета",
  'hifi.fn.timer': "Таймер",
  'hifi.fn.setup': "Налаштування",
  'hifi.function': "Функція",
  'hifi.system': "Система",
  'hifi.mixtape': "Мікстейп {name}",
  'hifi.showControls': "Показати елементи керування",
  'hifi.unit.preamp': "Керівний підсилювач",
  'hifi.unit.zones': "Зонний підсилювач",
  'hifi.unit.tuner': "Тюнер джерел",
  'hifi.unit.tape': "Дека черги",
  'hifi.unit.timer': "Програмний таймер",
  'hifi.unit.setup': "Задня панель",
  'hifi.ann.shuffle': "Випадково",
  'hifi.ann.repeat': "Повтор",
  'hifi.ann.repeatOne': "Повтор 1",
  'hifi.ann.crossfade': "Перехід",
  'hifi.ann.sleep': "Сон",
  'hifi.info': "Інфо",
  'hifi.link': "Зв’язати",
  'hifi.trim': "Підлаштування",
  'hifi.zone': "Зона",
  'hifi.chooseZone': "Виберіть зону",
  'hifi.noZone': "Зону не вибрано",
  'hifi.select': "Вибрати",
  'hifi.selectZone': "Вибрати цю зону",
  'hifi.party': "Вечірка",
  'hifi.partyHint': "Режим вечірки: усі кімнати цієї системи приєднуються до зони на екрані",
  'hifi.dragToLink': "Перетягніть табличку з назвою модуля на інший, щоб зв’язати їх.",
  'hifi.speakerSelector': "Вибір динаміків",
  'hifi.output': "Грає в",
  'hifi.presets': "Пресети",
  'hifi.preset': "Пресет {n}",
  'hifi.memory': "Пам’ять",
  'hifi.showInTuner': "Показати в тюнері",
  'hifi.track': "Трек",
  'hifi.rec': "Запис",
  'hifi.eject': "Вийняти",
  'hifi.cue': "Пошук",
  'hifi.moreTracks': "Далі в черзі ще {count} треків.",
  'hifi.newProgram': "Нова",
  'hifi.program': "Прог. {n}",
  'hifi.queueEmptyBody': "Налаштуйте тюнер на щось або додайте треки командою «Додати в кінець черги».",
  'hifi.allServices': "Усі сервіси",
  'hifi.allServicesGen': "Усі сервіси {gen}",
  'hifi.playOtherSystem': "Це в системі {gen}. Обери одну з її кімнат, щоб відтворити.",
  'hifi.playingNow': "Грає {title}",
  'hifi.queuedNext': "{title} гратиме наступним",
  'hifi.replacedQueue': "Чергу замінено на {title}",
  'hifi.addedToQueue': "{title} додано до черги",
  'hifi.selected': "Вибрано: {count}",
  'hifi.otherSystem': "У системі {gen}; вибери одну з її кімнат, щоб грати звідти",
  'hifi.filterServices': "Фільтрувати сервіси",
  'hifi.musicSources': "Джерела музики",
  'hifi.view': "Вигляд",
  'hifi.viewAuto': "Автоматично",
  'hifi.viewGrid': "Сітка",
  'hifi.viewList': "Список",
  'hifi.services.none': "У цій системі ще не налаштовано жодного музичного сервісу.",
  'hifi.services.linked': "Приєднано в Sonora",
  'hifi.services.notLinked': "Налаштовано в застосунку Sonos, ще не приєднано в Sonora",
  'hifi.alsoRemembered': "Також у пам’яті, але поза досяжністю: {names}.",
  'hifi.quality': "Якість",
  'hifi.worst': "найгірші мс",
  'hifi.wired': "Дротове",
  'hifi.serviceRemoved': "{service} вилучено",
  'hifi.moveUp': "Вище",
  'hifi.moveDown': "Нижче",
  'hifi.removeSelected': "Вилучити вибрані ({count})",
  'hifi.queueSaved': "Чергу збережено як «{title}»",
  'hifi.noPairCandidates': "Немає іншої непарної колонки цієї моделі.",
  'hifi.lineIn': "Лінійний вхід",
  'hifi.connected': "Під’єднано",
  'hifi.nothingConnected': "Нічого не під’єднано",
  'hifi.none': "Немає",
  'hifi.thisRoom': "Ця кімната",
  'hifi.linkedWith': "Згруповано з {room}",
  'hifi.linkAcrossSystems': "Кімнати з різних систем не можна згрупувати разом.",
  'hifi.open': "Відкрити",
  'hifi.leaveGroup': "Вивести {room} з групи",
  'hifi.noRooms': "У цій системі немає кімнат.",
  'hifi.diag.noAnswer': "немає відповіді",
  'hifi.setup.account': "Обліковий запис Sonos",
  'hifi.setup.services': "Музичні сервіси",
  'hifi.setup.services.blurb': 'Стрімінгові сервіси, які ви налаштували.',
  'hifi.setup.library': "Музична бібліотека",
  'hifi.setup.library.blurb': 'Спільні папки з музикою у вашій мережі.',
  'hifi.setup.time': "Дата й час",
  'hifi.setup.time.blurb': 'Налаштування годинника й часового поясу.',
  'hifi.setup.systems': "Системи та кімнати",
  'hifi.setup.systems.blurb': 'Які пристрої Sonora бачить у вашій мережі.',
  'hifi.setup.parental': "Фільтри вмісту",
  'hifi.setup.parental.blurb': 'Фільтрування відвертого вмісту.',
  'hifi.setup.s2': "Порадник з оновлення",
  'hifi.setup.network': "Перевірка мережі",
  'hifi.setup.network.blurb': 'Виявлення можливих проблем із продуктивністю у вашій мережі.',
  'hifi.setup.appearance': "Вигляд",
  'hifi.setup.appearance.blurb': "Тема, яку носить Sonora, і мова, якою вона говорить.",
  'hifi.setup.log': "Журнал",
  'hifi.setup.log.blurb': "Що нещодавно пішло не так, від найновішого.",
}

const jaJP = {
  'hifi.meter.peak': "ピーク",
  'hifi.meter.balance': "バランス",
  'hifi.meter.phase': "位相",
  'hifi.meter.dynamics': "ダイナミクス",
  'hifi.levelsUnavailable': "このソースのレベルは表示できません。",
  'hifi.vuMeters': "VUメーター",
  'hifi.levelDisplay': "レベル表示",
  'hifi.eqDisplay': "グラフィックイコライザー",
  'hifi.reload': '再読み込み',
  'hifi.fn.zones': "ゾーン",
  'hifi.fn.tuner': "チューナー",
  'hifi.fn.tape': "テープ",
  'hifi.fn.timer': "タイマー",
  'hifi.fn.setup': "設定",
  'hifi.function': "機能",
  'hifi.system': "システム",
  'hifi.mixtape': "{name} ミックステープ",
  'hifi.showControls': "コントロールを表示",
  'hifi.unit.preamp': "コントロールアンプ",
  'hifi.unit.zones': "ゾーンアンプ",
  'hifi.unit.tuner': "ソースチューナー",
  'hifi.unit.tape': "キューデッキ",
  'hifi.unit.timer': "プログラムタイマー",
  'hifi.unit.setup': "リアパネル",
  'hifi.ann.shuffle': "シャッフル",
  'hifi.ann.repeat': "リピート",
  'hifi.ann.repeatOne': "1曲リピート",
  'hifi.ann.crossfade': "クロスフェード",
  'hifi.ann.sleep': "スリープ",
  'hifi.info': "情報",
  'hifi.link': "リンク",
  'hifi.trim': "微調整",
  'hifi.zone': "ゾーン",
  'hifi.chooseZone': "ゾーンを選択",
  'hifi.noZone': "ゾーンが選択されていません",
  'hifi.select': "選択",
  'hifi.selectZone': "このゾーンを選択",
  'hifi.party': "パーティー",
  'hifi.partyHint': "パーティーモード：このシステムのすべての部屋が表示中のゾーンに加わります",
  'hifi.dragToLink': "モジュールの銘板を別のモジュールにドラッグするとリンクできます。",
  'hifi.speakerSelector': "スピーカーセレクター",
  'hifi.output': "再生先",
  'hifi.presets': "プリセット",
  'hifi.preset': "プリセット {n}",
  'hifi.memory': "メモリー",
  'hifi.showInTuner': "チューナーで表示",
  'hifi.track': "トラック",
  'hifi.rec': "録音",
  'hifi.eject': "取り出し",
  'hifi.cue': "頭出し",
  'hifi.moreTracks': "キューにはさらに {count} 曲あります。",
  'hifi.newProgram': "新規",
  'hifi.program': "プログラム {n}",
  'hifi.queueEmptyBody': "チューナーで何かを選局するか、「キューの最後に追加」で曲を追加してください。",
  'hifi.allServices': "すべてのサービス",
  'hifi.allServicesGen': "すべての{gen}サービス",
  'hifi.playOtherSystem': "これは {gen} システムにあります。再生するには、そのシステムのルームを選んでください。",
  'hifi.playingNow': "{title} を再生中",
  'hifi.queuedNext': "{title} を次に再生します",
  'hifi.replacedQueue': "キューを {title} で置き換えました",
  'hifi.addedToQueue': "{title} をキューに追加しました",
  'hifi.selected': "{count} 件選択",
  'hifi.otherSystem': "{gen} システム上です。そこから再生するには、その部屋のいずれかを選んでください",
  'hifi.filterServices': "サービスを絞り込む",
  'hifi.musicSources': "音楽ソース",
  'hifi.view': "表示",
  'hifi.viewAuto': "自動",
  'hifi.viewGrid': "グリッド",
  'hifi.viewList': "リスト",
  'hifi.services.none': "このシステムにはまだ音楽サービスが設定されていません。",
  'hifi.services.linked': "Sonora に連携済み",
  'hifi.services.notLinked': "Sonos アプリで設定済み、Sonora には未連携",
  'hifi.alsoRemembered': "覚えてはいますが届きません：{names}。",
  'hifi.quality': "品質",
  'hifi.worst': "最遅 ms",
  'hifi.wired': "有線",
  'hifi.serviceRemoved': "{service} を削除しました",
  'hifi.moveUp': "上へ",
  'hifi.moveDown': "下へ",
  'hifi.removeSelected': "選択した {count} 件を削除",
  'hifi.queueSaved': "キューを「{title}」として保存しました",
  'hifi.noPairCandidates': "このモデルで未ペアのスピーカーが他にありません。",
  'hifi.lineIn': "ライン入力",
  'hifi.connected': "接続済み",
  'hifi.nothingConnected': "何も接続されていません",
  'hifi.none': "なし",
  'hifi.thisRoom': "この部屋",
  'hifi.linkedWith': "{room} とグループ化",
  'hifi.linkAcrossSystems': "異なるシステムの部屋どうしはグループにできません。",
  'hifi.open': "開く",
  'hifi.leaveGroup': "{room} をグループから外す",
  'hifi.noRooms': "このシステムに部屋がありません。",
  'hifi.diag.noAnswer': "応答なし",
  'hifi.setup.account': "Sonos アカウント",
  'hifi.setup.services': "音楽サービス",
  'hifi.setup.services.blurb': '設定済みのストリーミングサービス。',
  'hifi.setup.library': "音楽ライブラリ",
  'hifi.setup.library.blurb': 'ネットワーク上の共有音楽フォルダー。',
  'hifi.setup.time': "日付と時刻",
  'hifi.setup.time.blurb': '時計とタイムゾーンの設定。',
  'hifi.setup.systems': "システムと部屋",
  'hifi.setup.systems.blurb': 'Sonora がネットワーク上で認識しているデバイス。',
  'hifi.setup.parental': "コンテンツフィルター",
  'hifi.setup.parental.blurb': '露骨なコンテンツのフィルタリング。',
  'hifi.setup.s2': "アップグレードアドバイザー",
  'hifi.setup.network': "ネットワーク確認",
  'hifi.setup.network.blurb': 'ネットワークで起こりうるパフォーマンスの問題を見つけます。',
  'hifi.setup.appearance': "外観",
  'hifi.setup.appearance.blurb': "Sonora がまとうテーマと、話す言語。",
  'hifi.setup.log': "ログ",
  'hifi.setup.log.blurb': "最近うまくいかなかったこと、新しい順。",
}

const koKR = {
  'hifi.meter.peak': "피크",
  'hifi.meter.balance': "밸런스",
  'hifi.meter.phase': "위상",
  'hifi.meter.dynamics': "다이내믹",
  'hifi.levelsUnavailable': "이 소스의 레벨은 표시할 수 없습니다.",
  'hifi.vuMeters': "VU 미터",
  'hifi.levelDisplay': "레벨 표시",
  'hifi.eqDisplay': "그래픽 이퀄라이저",
  'hifi.reload': '새로고침',
  'hifi.fn.zones': "존",
  'hifi.fn.tuner': "튜너",
  'hifi.fn.tape': "테이프",
  'hifi.fn.timer': "타이머",
  'hifi.fn.setup': "설정",
  'hifi.function': "기능",
  'hifi.system': "시스템",
  'hifi.mixtape': "{name} 믹스테이프",
  'hifi.showControls': "컨트롤 표시",
  'hifi.unit.preamp': "컨트롤 앰프",
  'hifi.unit.zones': "존 앰프",
  'hifi.unit.tuner': "소스 튜너",
  'hifi.unit.tape': "대기열 데크",
  'hifi.unit.timer': "프로그램 타이머",
  'hifi.unit.setup': "후면 패널",
  'hifi.ann.shuffle': "임의",
  'hifi.ann.repeat': "반복",
  'hifi.ann.repeatOne': "한 곡 반복",
  'hifi.ann.crossfade': "크로스페이드",
  'hifi.ann.sleep': "취침",
  'hifi.info': "정보",
  'hifi.link': "연결",
  'hifi.trim': "미세 조정",
  'hifi.zone': "존",
  'hifi.chooseZone': "존 선택",
  'hifi.noZone': "선택된 존 없음",
  'hifi.select': "선택",
  'hifi.selectZone': "이 존 선택",
  'hifi.party': "파티",
  'hifi.partyHint': "파티 모드: 이 시스템의 모든 방이 보고 있는 존에 합류합니다",
  'hifi.dragToLink': "모듈의 이름판을 다른 모듈로 끌어 놓으면 둘을 연결합니다.",
  'hifi.speakerSelector': "스피커 선택기",
  'hifi.output': "재생 위치",
  'hifi.presets': "프리셋",
  'hifi.preset': "프리셋 {n}",
  'hifi.memory': "기록",
  'hifi.showInTuner': "튜너에서 보기",
  'hifi.track': "트랙",
  'hifi.rec': "녹음",
  'hifi.eject': "꺼내기",
  'hifi.cue': "찾기",
  'hifi.moreTracks': "대기열에 {count}곡이 더 있습니다.",
  'hifi.newProgram': "새로 만들기",
  'hifi.program': "프로그램 {n}",
  'hifi.queueEmptyBody': "튜너에서 무언가를 맞추거나 \"대기열 끝에 추가\"로 트랙을 추가하세요.",
  'hifi.allServices': "모든 서비스",
  'hifi.allServicesGen': "모든 {gen} 서비스",
  'hifi.playOtherSystem': "{gen} 시스템에 있습니다. 재생하려면 그 시스템의 룸을 선택하세요.",
  'hifi.playingNow': "{title} 재생 중",
  'hifi.queuedNext': "{title}을(를) 다음에 재생합니다",
  'hifi.replacedQueue': "대기열을 {title}(으)로 바꿨습니다",
  'hifi.addedToQueue': "{title}을(를) 대기열에 추가했습니다",
  'hifi.selected': "{count}개 선택됨",
  'hifi.otherSystem': "{gen} 시스템에 있습니다. 거기서 재생하려면 그 방 중 하나를 선택하세요",
  'hifi.filterServices': "서비스 필터",
  'hifi.musicSources': "음악 소스",
  'hifi.view': "보기",
  'hifi.viewAuto': "자동",
  'hifi.viewGrid': "그리드",
  'hifi.viewList': "목록",
  'hifi.services.none': "이 시스템에는 아직 설정된 음악 서비스가 없습니다.",
  'hifi.services.linked': "Sonora에 연결됨",
  'hifi.services.notLinked': "Sonos 앱에서 설정됨, Sonora에는 아직 연결되지 않음",
  'hifi.alsoRemembered': "기억하고 있지만 닿지 않음: {names}.",
  'hifi.quality': "품질",
  'hifi.worst': "최저 ms",
  'hifi.wired': "유선",
  'hifi.serviceRemoved': "{service}을(를) 제거했습니다",
  'hifi.moveUp': "위로",
  'hifi.moveDown': "아래로",
  'hifi.removeSelected': "선택한 {count}개 제거",
  'hifi.queueSaved': "대기열을 '{title}'(으)로 저장했습니다",
  'hifi.noPairCandidates': "같은 모델의 짝 없는 스피커가 더 없습니다.",
  'hifi.lineIn': "라인 입력",
  'hifi.connected': "연결됨",
  'hifi.nothingConnected': "연결된 것 없음",
  'hifi.none': "없음",
  'hifi.thisRoom': "이 방",
  'hifi.linkedWith': "{room}과(와) 그룹",
  'hifi.linkAcrossSystems': "서로 다른 시스템의 방은 함께 묶을 수 없습니다.",
  'hifi.open': "열기",
  'hifi.leaveGroup': "{room}을(를) 그룹에서 빼기",
  'hifi.noRooms': "이 시스템에 방이 없습니다.",
  'hifi.diag.noAnswer': "응답 없음",
  'hifi.setup.account': "Sonos 계정",
  'hifi.setup.services': "음악 서비스",
  'hifi.setup.services.blurb': '설정한 스트리밍 서비스.',
  'hifi.setup.library': "음악 라이브러리",
  'hifi.setup.library.blurb': '네트워크의 공유 음악 폴더.',
  'hifi.setup.time': "날짜와 시간",
  'hifi.setup.time.blurb': '시계 및 시간대 설정.',
  'hifi.setup.systems': "시스템과 방",
  'hifi.setup.systems.blurb': 'Sonora가 네트워크에서 보고 있는 기기.',
  'hifi.setup.parental': "콘텐츠 필터",
  'hifi.setup.parental.blurb': '선정적인 콘텐츠 필터링.',
  'hifi.setup.s2': "업그레이드 도우미",
  'hifi.setup.network': "네트워크 점검",
  'hifi.setup.network.blurb': '네트워크의 잠재적인 성능 문제를 찾아냅니다.',
  'hifi.setup.appearance': "모양",
  'hifi.setup.appearance.blurb': "Sonora가 입은 테마와 사용하는 언어.",
  'hifi.setup.log': "로그",
  'hifi.setup.log.blurb': "최근에 잘못된 일들, 최신순.",
}

const zhCN = {
  'hifi.meter.peak': "峰值",
  'hifi.meter.balance': "平衡",
  'hifi.meter.phase': "相位",
  'hifi.meter.dynamics': "动态",
  'hifi.levelsUnavailable': "无法显示此音源的电平。",
  'hifi.vuMeters': "VU 表",
  'hifi.levelDisplay': "电平显示",
  'hifi.eqDisplay': "图形均衡器",
  'hifi.reload': '重新加载',
  'hifi.fn.zones': "区域",
  'hifi.fn.tuner': "调谐器",
  'hifi.fn.tape': "磁带",
  'hifi.fn.timer': "定时器",
  'hifi.fn.setup': "设置",
  'hifi.function': "功能",
  'hifi.system': "系统",
  'hifi.mixtape': "{name} 混音带",
  'hifi.showControls': "显示控件",
  'hifi.unit.preamp': "控制放大器",
  'hifi.unit.zones': "区域放大器",
  'hifi.unit.tuner': "音源调谐器",
  'hifi.unit.tape': "队列卡座",
  'hifi.unit.timer': "程序定时器",
  'hifi.unit.setup': "后面板",
  'hifi.ann.shuffle': "随机",
  'hifi.ann.repeat': "重复",
  'hifi.ann.repeatOne': "单曲重复",
  'hifi.ann.crossfade': "交叉淡入淡出",
  'hifi.ann.sleep': "睡眠",
  'hifi.info': "信息",
  'hifi.link': "连接",
  'hifi.trim': "微调",
  'hifi.zone': "区域",
  'hifi.chooseZone': "选择区域",
  'hifi.noZone': "未选择区域",
  'hifi.select': "选择",
  'hifi.selectZone': "选择此区域",
  'hifi.party': "派对",
  'hifi.partyHint': "派对模式：此系统的所有房间加入当前区域",
  'hifi.dragToLink': "将一个模块的铭牌拖到另一个模块上即可将两者连接。",
  'hifi.speakerSelector': "扬声器选择器",
  'hifi.output': "播放到",
  'hifi.presets': "预设",
  'hifi.preset': "预设 {n}",
  'hifi.memory': "记忆",
  'hifi.showInTuner': "在调谐器中显示",
  'hifi.track': "曲目",
  'hifi.rec': "录制",
  'hifi.eject': "弹出",
  'hifi.cue': "定位",
  'hifi.moreTracks': "队列中还有 {count} 首曲目。",
  'hifi.newProgram': "新建",
  'hifi.program': "程序 {n}",
  'hifi.queueEmptyBody': "在调谐器上选一个音源，或用“添加到队列末尾”加入曲目。",
  'hifi.allServices': "所有服务",
  'hifi.allServicesGen': "所有 {gen} 服务",
  'hifi.playOtherSystem': "这在 {gen} 系统上。请选择该系统的一个房间来播放。",
  'hifi.playingNow': "正在播放 {title}",
  'hifi.queuedNext': "{title} 将在下一首播放",
  'hifi.replacedQueue': "播放队列已替换为 {title}",
  'hifi.addedToQueue': "已把 {title} 加入播放队列",
  'hifi.selected': "已选择 {count} 项",
  'hifi.otherSystem': "在 {gen} 系统上；选择它的一个房间即可从那里播放",
  'hifi.filterServices': "筛选服务",
  'hifi.musicSources': "音乐来源",
  'hifi.view': "视图",
  'hifi.viewAuto': "自动",
  'hifi.viewGrid': "网格",
  'hifi.viewList': "列表",
  'hifi.services.none': "此系统还没有配置音乐服务。",
  'hifi.services.linked': "已在 Sonora 中关联",
  'hifi.services.notLinked': "已在 Sonos 应用中配置，尚未在 Sonora 中关联",
  'hifi.alsoRemembered': "还记得但无法触及：{names}。",
  'hifi.quality': "质量",
  'hifi.worst': "最慢 ms",
  'hifi.wired': "有线",
  'hifi.serviceRemoved': "已移除 {service}",
  'hifi.moveUp': "上移",
  'hifi.moveDown': "下移",
  'hifi.removeSelected': "移除选中的 {count} 项",
  'hifi.queueSaved': "播放队列已保存为“{title}”",
  'hifi.noPairCandidates': "没有同型号的其他未配对扬声器。",
  'hifi.lineIn': "线路输入",
  'hifi.connected': "已连接",
  'hifi.nothingConnected': "没有连接任何设备",
  'hifi.none': "无",
  'hifi.thisRoom': "这个房间",
  'hifi.linkedWith': "与 {room} 编组",
  'hifi.linkAcrossSystems': "不同系统的房间无法编组在一起。",
  'hifi.open': "打开",
  'hifi.leaveGroup': "把 {room} 移出编组",
  'hifi.noRooms': "此系统中没有房间。",
  'hifi.diag.noAnswer': "没有响应",
  'hifi.setup.account': "Sonos 账户",
  'hifi.setup.services': "音乐服务",
  'hifi.setup.services.blurb': '您已设置的流媒体服务。',
  'hifi.setup.library': "音乐库",
  'hifi.setup.library.blurb': '网络上的共享音乐文件夹。',
  'hifi.setup.time': "日期与时间",
  'hifi.setup.time.blurb': '时钟和时区设置。',
  'hifi.setup.systems': "系统与房间",
  'hifi.setup.systems.blurb': 'Sonora 在您的网络上看到的设备。',
  'hifi.setup.parental': "内容过滤",
  'hifi.setup.parental.blurb': '露骨内容过滤。',
  'hifi.setup.s2': "升级顾问",
  'hifi.setup.network': "网络检查",
  'hifi.setup.network.blurb': '找出网络上可能存在的性能问题。',
  'hifi.setup.appearance': "外观",
  'hifi.setup.appearance.blurb': "Sonora 穿的主题，以及它说的语言。",
  'hifi.setup.log': "日志",
  'hifi.setup.log.blurb': "最近出错的记录，最新的在前。",
}

const zhTW = {
  'hifi.meter.peak': "峰值",
  'hifi.meter.balance': "平衡",
  'hifi.meter.phase': "相位",
  'hifi.meter.dynamics': "動態",
  'hifi.levelsUnavailable': "無法顯示此音源的電平。",
  'hifi.vuMeters': "VU 表",
  'hifi.levelDisplay': "電平顯示",
  'hifi.eqDisplay': "圖形等化器",
  'hifi.reload': '重新載入',
  'hifi.fn.zones': "區域",
  'hifi.fn.tuner': "調諧器",
  'hifi.fn.tape': "卡帶",
  'hifi.fn.timer': "定時器",
  'hifi.fn.setup': "設定",
  'hifi.function': "功能",
  'hifi.system': "系統",
  'hifi.mixtape': "{name} 混音帶",
  'hifi.showControls': "顯示控制項",
  'hifi.unit.preamp': "控制擴大機",
  'hifi.unit.zones': "區域擴大機",
  'hifi.unit.tuner': "音源調諧器",
  'hifi.unit.tape': "佇列卡座",
  'hifi.unit.timer': "節目定時器",
  'hifi.unit.setup': "背板",
  'hifi.ann.shuffle': "隨機",
  'hifi.ann.repeat': "重複",
  'hifi.ann.repeatOne': "單曲重複",
  'hifi.ann.crossfade': "交叉淡入淡出",
  'hifi.ann.sleep': "睡眠",
  'hifi.info': "資訊",
  'hifi.link': "連結",
  'hifi.trim': "微調",
  'hifi.zone': "區域",
  'hifi.chooseZone': "選擇區域",
  'hifi.noZone': "未選擇區域",
  'hifi.select': "選擇",
  'hifi.selectZone': "選擇此區域",
  'hifi.party': "派對",
  'hifi.partyHint': "派對模式：此系統的所有房間加入目前的區域",
  'hifi.dragToLink': "將一個模組的名牌拖到另一個模組上，即可將兩者連結。",
  'hifi.speakerSelector': "喇叭選擇器",
  'hifi.output': "播放於",
  'hifi.presets': "預設",
  'hifi.preset': "預設 {n}",
  'hifi.memory': "記憶",
  'hifi.showInTuner': "在調諧器中顯示",
  'hifi.track': "曲目",
  'hifi.rec': "錄音",
  'hifi.eject': "退出",
  'hifi.cue': "定位",
  'hifi.moreTracks': "佇列中還有 {count} 首曲目。",
  'hifi.newProgram': "新增",
  'hifi.program': "節目 {n}",
  'hifi.queueEmptyBody': "在調諧器上選一個音源，或用「加到佇列最後」加入曲目。",
  'hifi.allServices': "所有服務",
  'hifi.allServicesGen': "所有 {gen} 服務",
  'hifi.playOtherSystem': "這在 {gen} 系統上。請選擇該系統的一個房間來播放。",
  'hifi.playingNow': "正在播放 {title}",
  'hifi.queuedNext': "{title} 將在下一首播放",
  'hifi.replacedQueue': "播放佇列已換成 {title}",
  'hifi.addedToQueue': "已把 {title} 加入播放佇列",
  'hifi.selected': "已選取 {count} 項",
  'hifi.otherSystem': "在 {gen} 系統上；選它的一個房間就能從那裡播放",
  'hifi.filterServices': "篩選服務",
  'hifi.musicSources': "音樂來源",
  'hifi.view': "檢視",
  'hifi.viewAuto': "自動",
  'hifi.viewGrid': "格狀",
  'hifi.viewList': "清單",
  'hifi.services.none': "這套系統還沒有設定音樂服務。",
  'hifi.services.linked': "已在 Sonora 中連結",
  'hifi.services.notLinked': "已在 Sonos App 中設定，尚未在 Sonora 中連結",
  'hifi.alsoRemembered': "還記得但搆不著：{names}。",
  'hifi.quality': "品質",
  'hifi.worst': "最慢 ms",
  'hifi.wired': "有線",
  'hifi.serviceRemoved': "已移除 {service}",
  'hifi.moveUp': "上移",
  'hifi.moveDown': "下移",
  'hifi.removeSelected': "移除選取的 {count} 項",
  'hifi.queueSaved': "播放佇列已存成「{title}」",
  'hifi.noPairCandidates': "沒有其他同型號的未配對喇叭。",
  'hifi.lineIn': "線路輸入",
  'hifi.connected': "已連接",
  'hifi.nothingConnected': "沒有接任何東西",
  'hifi.none': "無",
  'hifi.thisRoom': "這個房間",
  'hifi.linkedWith': "與 {room} 群組",
  'hifi.linkAcrossSystems': "不同系統的房間無法組成群組。",
  'hifi.open': "開啟",
  'hifi.leaveGroup': "把 {room} 移出群組",
  'hifi.noRooms': "這套系統裡沒有房間。",
  'hifi.diag.noAnswer': "沒有回應",
  'hifi.setup.account': "Sonos 帳戶",
  'hifi.setup.services': "音樂服務",
  'hifi.setup.services.blurb': '您已設定的串流服務。',
  'hifi.setup.library': "音樂庫",
  'hifi.setup.library.blurb': '網路上的共用音樂資料夾。',
  'hifi.setup.time': "日期與時間",
  'hifi.setup.time.blurb': '時鐘與時區設定。',
  'hifi.setup.systems': "系統與房間",
  'hifi.setup.systems.blurb': 'Sonora 在您的網路上看到的裝置。',
  'hifi.setup.parental': "內容過濾",
  'hifi.setup.parental.blurb': '露骨內容過濾。',
  'hifi.setup.s2': "升級顧問",
  'hifi.setup.network': "網路檢查",
  'hifi.setup.network.blurb': '找出網路上可能存在的效能問題。',
  'hifi.setup.appearance': "外觀",
  'hifi.setup.appearance.blurb': "Sonora 穿的佈景主題，以及它說的語言。",
  'hifi.setup.log': "記錄",
  'hifi.setup.log.blurb': "最近出錯的記錄，最新的在前。",
}

const csCZ = {
  'hifi.meter.peak': "Špička",
  'hifi.meter.balance': "Vyvážení",
  'hifi.meter.phase': "Fáze",
  'hifi.meter.dynamics': "Dynamika",
  'hifi.levelsUnavailable': "Úrovně tohoto zdroje nelze zobrazit.",
  'hifi.vuMeters': "VU metry",
  'hifi.levelDisplay': "Ukazatel úrovně",
  'hifi.eqDisplay': "Grafický ekvalizér",
  'hifi.reload': 'Znovu načíst',
  'hifi.fn.zones': "Zóny",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Kazeta",
  'hifi.fn.timer': "Časovač",
  'hifi.fn.setup': "Nastavení",
  'hifi.function': "Funkce",
  'hifi.system': "Systém",
  'hifi.mixtape': "Mixtape {name}",
  'hifi.showControls': "Zobrazit ovládání",
  'hifi.unit.preamp': "Řídicí zesilovač",
  'hifi.unit.zones': "Zónový zesilovač",
  'hifi.unit.tuner': "Tuner zdrojů",
  'hifi.unit.tape': "Deck fronty",
  'hifi.unit.timer': "Programový časovač",
  'hifi.unit.setup': "Zadní panel",
  'hifi.ann.shuffle': "Náhodně",
  'hifi.ann.repeat': "Opakovat",
  'hifi.ann.repeatOne': "Opakovat 1",
  'hifi.ann.crossfade': "Prolínání",
  'hifi.ann.sleep': "Spánek",
  'hifi.info': "Info",
  'hifi.link': "Propojit",
  'hifi.trim': "Doladění",
  'hifi.zone': "Zóna",
  'hifi.chooseZone': "Vyberte zónu",
  'hifi.noZone': "Není vybrána žádná zóna",
  'hifi.select': "Vybrat",
  'hifi.selectZone': "Vybrat tuto zónu",
  'hifi.party': "Párty",
  'hifi.partyHint': "Režim párty: všechny místnosti tohoto systému se připojí k zobrazené zóně",
  'hifi.dragToLink': "Přetažením jmenovky jednoho modulu na jiný je propojíte.",
  'hifi.speakerSelector': "Volič reproduktorů",
  'hifi.output': "Hraje v",
  'hifi.presets': "Předvolby",
  'hifi.preset': "Předvolba {n}",
  'hifi.memory': "Paměť",
  'hifi.showInTuner': "Zobrazit v tuneru",
  'hifi.track': "Skladba",
  'hifi.rec': "Záznam",
  'hifi.eject': "Vysunout",
  'hifi.cue': "Vyhledat",
  'hifi.moreTracks': "Ve frontě následuje ještě {count} skladeb.",
  'hifi.newProgram': "Nový",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Nalaďte něco na tuneru, nebo přidejte skladby příkazem „Přidat na konec fronty“.",
  'hifi.allServices': "Všechny služby",
  'hifi.allServicesGen': "Všechny služby {gen}",
  'hifi.playOtherSystem': "Je to v systému {gen}. K přehrání vyberte jednu z jeho místností.",
  'hifi.playingNow': "Přehrává se {title}",
  'hifi.queuedNext': "Jako další se přehraje {title}",
  'hifi.replacedQueue': "Fronta nahrazena položkou {title}",
  'hifi.addedToQueue': "{title} přidáno do fronty",
  'hifi.selected': "Vybráno: {count}",
  'hifi.otherSystem': "V systému {gen}; chcete-li z něj přehrávat, vyberte jednu z jeho místností",
  'hifi.filterServices': "Filtrovat služby",
  'hifi.musicSources': "Zdroje hudby",
  'hifi.view': "Zobrazení",
  'hifi.viewAuto': "Automaticky",
  'hifi.viewGrid': "Mřížka",
  'hifi.viewList': "Seznam",
  'hifi.services.none': "V tomto systému zatím nejsou nastavené žádné hudební služby.",
  'hifi.services.linked': "Propojeno v Sonoře",
  'hifi.services.notLinked': "Nastaveno v aplikaci Sonos, zatím nepropojeno v Sonoře",
  'hifi.alsoRemembered': "Zapamatované, ale mimo dosah: {names}.",
  'hifi.quality': "Kvalita",
  'hifi.worst': "nejhorší ms",
  'hifi.wired': "Kabelem",
  'hifi.serviceRemoved': "Služba {service} odebrána",
  'hifi.moveUp': "Posunout nahoru",
  'hifi.moveDown': "Posunout dolů",
  'hifi.removeSelected': "Odebrat vybrané ({count})",
  'hifi.queueSaved': "Fronta uložena jako „{title}“",
  'hifi.noPairCandidates': "Žádný další nespárovaný reproduktor tohoto modelu.",
  'hifi.lineIn': "Linkový vstup",
  'hifi.connected': "Připojeno",
  'hifi.nothingConnected': "Nic není připojeno",
  'hifi.none': "Žádné",
  'hifi.thisRoom': "Tato místnost",
  'hifi.linkedWith': "Seskupeno s {room}",
  'hifi.linkAcrossSystems': "Místnosti z různých systémů nelze seskupit.",
  'hifi.open': "Otevřít",
  'hifi.leaveGroup': "Vyjmout {room} ze skupiny",
  'hifi.noRooms': "V tomto systému nejsou žádné místnosti.",
  'hifi.diag.noAnswer': "bez odpovědi",
  'hifi.setup.account': "Účet Sonos",
  'hifi.setup.services': "Hudební služby",
  'hifi.setup.services.blurb': 'Streamovací služby, které jste nastavili.',
  'hifi.setup.library': "Hudební knihovna",
  'hifi.setup.library.blurb': 'Sdílené složky s hudbou ve vaší síti.',
  'hifi.setup.time': "Datum a čas",
  'hifi.setup.time.blurb': 'Nastavení hodin a časového pásma.',
  'hifi.setup.systems': "Systémy a místnosti",
  'hifi.setup.systems.blurb': 'Která zařízení Sonora vidí ve vaší síti.',
  'hifi.setup.parental': "Filtry obsahu",
  'hifi.setup.parental.blurb': 'Filtrování explicitního obsahu.',
  'hifi.setup.s2': "Poradce pro upgrade",
  'hifi.setup.network': "Kontrola sítě",
  'hifi.setup.network.blurb': 'Odhalte možné potíže s výkonem ve vaší síti.',
  'hifi.setup.appearance': "Vzhled",
  'hifi.setup.appearance.blurb': "Motiv, který Sonora používá, a jazyk, kterým mluví.",
  'hifi.setup.log': "Záznam",
  'hifi.setup.log.blurb': "Co se v poslední době pokazilo, od nejnovějšího.",
}

const daDK = {
  'hifi.meter.peak': "Top",
  'hifi.meter.balance': "Balance",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dynamik",
  'hifi.levelsUnavailable': "Niveauer kan ikke vises for denne kilde.",
  'hifi.vuMeters': "VU-metre",
  'hifi.levelDisplay': "Niveauvisning",
  'hifi.eqDisplay': "Grafisk equalizer",
  'hifi.reload': 'Genindlæs',
  'hifi.fn.zones': "Zoner",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Bånd",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Indstillinger",
  'hifi.function': "Funktion",
  'hifi.system': "System",
  'hifi.mixtape': "{name}-mixtape",
  'hifi.showControls': "Vis betjeningen",
  'hifi.unit.preamp': "Kontrolforstærker",
  'hifi.unit.zones': "Zoneforstærker",
  'hifi.unit.tuner': "Kildetuner",
  'hifi.unit.tape': "Kødæk",
  'hifi.unit.timer': "Programtimer",
  'hifi.unit.setup': "Bagpanel",
  'hifi.ann.shuffle': "Bland",
  'hifi.ann.repeat': "Gentag",
  'hifi.ann.repeatOne': "Gentag 1",
  'hifi.ann.crossfade': "Overtoning",
  'hifi.ann.sleep': "Sov",
  'hifi.info': "Info",
  'hifi.link': "Forbind",
  'hifi.trim': "Finjustering",
  'hifi.zone': "Zone",
  'hifi.chooseZone': "Vælg en zone",
  'hifi.noZone': "Ingen zone valgt",
  'hifi.select': "Vælg",
  'hifi.selectZone': "Vælg denne zone",
  'hifi.party': "Fest",
  'hifi.partyHint': "Festtilstand: alle rum i dette system slutter sig til zonen i visning",
  'hifi.dragToLink': "Træk et moduls navneskilt hen på et andet for at forbinde dem.",
  'hifi.speakerSelector': "Højttalervælger",
  'hifi.output': "Spiller i",
  'hifi.presets': "Forvalg",
  'hifi.preset': "Forvalg {n}",
  'hifi.memory': "Hukommelse",
  'hifi.showInTuner': "Vis i tuneren",
  'hifi.track': "Nummer",
  'hifi.rec': "Opt.",
  'hifi.eject': "Skub ud",
  'hifi.cue': "Søg",
  'hifi.moreTracks': "Der følger {count} numre mere i køen.",
  'hifi.newProgram': "Ny",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Find noget på tuneren, eller tilføj numre med \"Føj til slutningen af køen\".",
  'hifi.allServices': "Alle tjenester",
  'hifi.allServicesGen': "Alle {gen}-tjenester",
  'hifi.playOtherSystem': "Det ligger på {gen}-systemet. Vælg et af dets rum for at afspille det.",
  'hifi.playingNow': "Afspiller {title}",
  'hifi.queuedNext': "Afspiller {title} som det næste",
  'hifi.replacedQueue': "Køen blev erstattet med {title}",
  'hifi.addedToQueue': "{title} blev føjet til køen",
  'hifi.selected': "{count} valgt",
  'hifi.otherSystem': "På {gen}-systemet; vælg et af dets rum for at afspille derfra",
  'hifi.filterServices': "Filtrer tjenester",
  'hifi.musicSources': "Musikkilder",
  'hifi.view': "Visning",
  'hifi.viewAuto': "Automatisk",
  'hifi.viewGrid': "Gitter",
  'hifi.viewList': "Liste",
  'hifi.services.none': "Der er endnu ikke konfigureret nogen musiktjenester på dette system.",
  'hifi.services.linked': "Tilknyttet i Sonora",
  'hifi.services.notLinked': "Konfigureret i Sonos-appen, endnu ikke tilknyttet i Sonora",
  'hifi.alsoRemembered': "Husket, men uden for rækkevidde: {names}.",
  'hifi.quality': "Kvalitet",
  'hifi.worst': "værste ms",
  'hifi.wired': "Kablet",
  'hifi.serviceRemoved': "{service} blev fjernet",
  'hifi.moveUp': "Flyt op",
  'hifi.moveDown': "Flyt ned",
  'hifi.removeSelected': "Fjern {count} valgte",
  'hifi.queueSaved': "Køen blev gemt som \"{title}\"",
  'hifi.noPairCandidates': "Ingen anden uparret højttaler af denne model.",
  'hifi.lineIn': "Line-in",
  'hifi.connected': "Forbundet",
  'hifi.nothingConnected': "Intet tilsluttet",
  'hifi.none': "Ingen",
  'hifi.thisRoom': "Dette rum",
  'hifi.linkedWith': "Grupperet med {room}",
  'hifi.linkAcrossSystems': "Rum på forskellige systemer kan ikke grupperes sammen.",
  'hifi.open': "Åbn",
  'hifi.leaveGroup': "Tag {room} ud af gruppen",
  'hifi.noRooms': "Ingen rum i dette system.",
  'hifi.diag.noAnswer': "intet svar",
  'hifi.setup.account': "Sonos-konto",
  'hifi.setup.services': "Musiktjenester",
  'hifi.setup.services.blurb': 'De streamingtjenester, du har konfigureret.',
  'hifi.setup.library': "Musikbibliotek",
  'hifi.setup.library.blurb': 'Delte musikmapper på dit netværk.',
  'hifi.setup.time': "Dato og tid",
  'hifi.setup.time.blurb': 'Indstillinger for ur og tidszone.',
  'hifi.setup.systems': "Systemer og rum",
  'hifi.setup.systems.blurb': 'Hvilke enheder Sonora ser på dit netværk.',
  'hifi.setup.parental': "Indholdsfiltre",
  'hifi.setup.parental.blurb': 'Filtrering af eksplicit indhold.',
  'hifi.setup.s2': "Opgraderingsrådgiver",
  'hifi.setup.network': "Netværkstjek",
  'hifi.setup.network.blurb': 'Find mulige ydeevneproblemer på dit netværk.',
  'hifi.setup.appearance': "Udseende",
  'hifi.setup.appearance.blurb': "Det tema, Sonora bruger, og det sprog, den taler.",
  'hifi.setup.log': "Log",
  'hifi.setup.log.blurb': "Hvad der er gået galt for nylig, nyeste først.",
}

const fiFI = {
  'hifi.meter.peak': "Huippu",
  'hifi.meter.balance': "Tasapaino",
  'hifi.meter.phase': "Vaihe",
  'hifi.meter.dynamics': "Dynamiikka",
  'hifi.levelsUnavailable': "Tämän lähteen tasoja ei voi näyttää.",
  'hifi.vuMeters': "VU-mittarit",
  'hifi.levelDisplay': "Tasonäyttö",
  'hifi.eqDisplay': "Graafinen taajuuskorjain",
  'hifi.reload': 'Lataa uudelleen',
  'hifi.fn.zones': "Vyöhykkeet",
  'hifi.fn.tuner': "Viritin",
  'hifi.fn.tape': "Kasetti",
  'hifi.fn.timer': "Ajastin",
  'hifi.fn.setup': "Asetukset",
  'hifi.function': "Toiminto",
  'hifi.system': "Järjestelmä",
  'hifi.mixtape': "{name}-mixtape",
  'hifi.showControls': "Näytä säätimet",
  'hifi.unit.preamp': "Ohjausvahvistin",
  'hifi.unit.zones': "Vyöhykevahvistin",
  'hifi.unit.tuner': "Lähdeviritin",
  'hifi.unit.tape': "Jonodekki",
  'hifi.unit.timer': "Ohjelma-ajastin",
  'hifi.unit.setup': "Takapaneeli",
  'hifi.ann.shuffle': "Satunnainen",
  'hifi.ann.repeat': "Toisto",
  'hifi.ann.repeatOne': "Toisto 1",
  'hifi.ann.crossfade': "Häivytys",
  'hifi.ann.sleep': "Uni",
  'hifi.info': "Tiedot",
  'hifi.link': "Yhdistä",
  'hifi.trim': "Hienosäätö",
  'hifi.zone': "Vyöhyke",
  'hifi.chooseZone': "Valitse vyöhyke",
  'hifi.noZone': "Vyöhykettä ei ole valittu",
  'hifi.select': "Valitse",
  'hifi.selectZone': "Valitse tämä vyöhyke",
  'hifi.party': "Juhlat",
  'hifi.partyHint': "Juhlatila: järjestelmän kaikki huoneet liittyvät näkyvään vyöhykkeeseen",
  'hifi.dragToLink': "Vedä moduulin nimikilpi toisen päälle yhdistääksesi ne.",
  'hifi.speakerSelector': "Kaiutinvalitsin",
  'hifi.output': "Soi kohteessa",
  'hifi.presets': "Esivalinnat",
  'hifi.preset': "Esivalinta {n}",
  'hifi.memory': "Muisti",
  'hifi.showInTuner': "Näytä virittimessä",
  'hifi.track': "Kappale",
  'hifi.rec': "Tall.",
  'hifi.eject': "Poista",
  'hifi.cue': "Haku",
  'hifi.moreTracks': "Jonossa on vielä {count} kappaletta.",
  'hifi.newProgram': "Uusi",
  'hifi.program': "Ohj. {n}",
  'hifi.queueEmptyBody': "Viritä jotain virittimeltä tai lisää kappaleita komennolla ”Lisää jonon loppuun”.",
  'hifi.allServices': "Kaikki palvelut",
  'hifi.allServicesGen': "Kaikki {gen}-palvelut",
  'hifi.playOtherSystem': "Se on {gen}-järjestelmässä. Valitse sen huone toistaaksesi.",
  'hifi.playingNow': "Toistetaan: {title}",
  'hifi.queuedNext': "Seuraavaksi: {title}",
  'hifi.replacedQueue': "Jono korvattiin: {title}",
  'hifi.addedToQueue': "Lisättiin jonoon: {title}",
  'hifi.selected': "{count} valittu",
  'hifi.otherSystem': "{gen}-järjestelmässä; valitse jokin sen huoneista toistaaksesi siitä",
  'hifi.filterServices': "Suodata palveluita",
  'hifi.musicSources': "Musiikkilähteet",
  'hifi.view': "Näkymä",
  'hifi.viewAuto': "Automaattinen",
  'hifi.viewGrid': "Ruudukko",
  'hifi.viewList': "Luettelo",
  'hifi.services.none': "Tähän järjestelmään ei ole vielä määritetty musiikkipalveluita.",
  'hifi.services.linked': "Yhdistetty Sonoraan",
  'hifi.services.notLinked': "Määritetty Sonos-sovelluksessa, ei vielä yhdistetty Sonoraan",
  'hifi.alsoRemembered': "Muistetaan myös, mutta ei tavoitettavissa: {names}.",
  'hifi.quality': "Laatu",
  'hifi.worst': "hitain ms",
  'hifi.wired': "Langallinen",
  'hifi.serviceRemoved': "Poistettiin: {service}",
  'hifi.moveUp': "Siirrä ylös",
  'hifi.moveDown': "Siirrä alas",
  'hifi.removeSelected': "Poista {count} valittua",
  'hifi.queueSaved': "Jono tallennettiin nimellä \"{title}\"",
  'hifi.noPairCandidates': "Tätä mallia ei ole muita parittomia kaiuttimia.",
  'hifi.lineIn': "Linjatulo",
  'hifi.connected': "Yhdistetty",
  'hifi.nothingConnected': "Ei mitään yhdistettynä",
  'hifi.none': "Ei mitään",
  'hifi.thisRoom': "Tämä huone",
  'hifi.linkedWith': "Samassa ryhmässä: {room}",
  'hifi.linkAcrossSystems': "Eri järjestelmien huoneita ei voi ryhmittää yhteen.",
  'hifi.open': "Avaa",
  'hifi.leaveGroup': "Poista {room} ryhmästä",
  'hifi.noRooms': "Tässä järjestelmässä ei ole huoneita.",
  'hifi.diag.noAnswer': "ei vastausta",
  'hifi.setup.account': "Sonos-tili",
  'hifi.setup.services': "Musiikkipalvelut",
  'hifi.setup.services.blurb': 'Määrittämäsi suoratoistopalvelut.',
  'hifi.setup.library': "Musiikkikirjasto",
  'hifi.setup.library.blurb': 'Verkkosi jaetut musiikkikansiot.',
  'hifi.setup.time': "Päivämäärä ja aika",
  'hifi.setup.time.blurb': 'Kellon ja aikavyöhykkeen asetukset.',
  'hifi.setup.systems': "Järjestelmät ja huoneet",
  'hifi.setup.systems.blurb': 'Mitkä laitteet Sonora näkee verkossasi.',
  'hifi.setup.parental': "Sisältösuodattimet",
  'hifi.setup.parental.blurb': 'Sopimattoman sisällön suodatus.',
  'hifi.setup.s2': "Päivitysneuvoja",
  'hifi.setup.network': "Verkon tarkistus",
  'hifi.setup.network.blurb': 'Tunnista verkkosi mahdolliset suorituskykyongelmat.',
  'hifi.setup.appearance': "Ulkoasu",
  'hifi.setup.appearance.blurb': "Sonoran teema ja kieli.",
  'hifi.setup.log': "Loki",
  'hifi.setup.log.blurb': "Mikä meni viime aikoina vikaan, uusin ensin.",
}

const nbNO = {
  'hifi.meter.peak': "Topp",
  'hifi.meter.balance': "Balanse",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dynamikk",
  'hifi.levelsUnavailable': "Nivåer kan ikke vises for denne kilden.",
  'hifi.vuMeters': "VU-metre",
  'hifi.levelDisplay': "Nivåvisning",
  'hifi.eqDisplay': "Grafisk equalizer",
  'hifi.reload': 'Last inn på nytt',
  'hifi.fn.zones': "Soner",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Kassett",
  'hifi.fn.timer': "Tidsur",
  'hifi.fn.setup': "Innstillinger",
  'hifi.function': "Funksjon",
  'hifi.system': "System",
  'hifi.mixtape': "{name}-mixtape",
  'hifi.showControls': "Vis kontrollene",
  'hifi.unit.preamp': "Kontrollforsterker",
  'hifi.unit.zones': "Soneforsterker",
  'hifi.unit.tuner': "Kildetuner",
  'hifi.unit.tape': "Kødekk",
  'hifi.unit.timer': "Programtidsur",
  'hifi.unit.setup': "Bakpanel",
  'hifi.ann.shuffle': "Tilfeldig",
  'hifi.ann.repeat': "Gjenta",
  'hifi.ann.repeatOne': "Gjenta 1",
  'hifi.ann.crossfade': "Overtoning",
  'hifi.ann.sleep': "Sove",
  'hifi.info': "Info",
  'hifi.link': "Koble",
  'hifi.trim': "Finjustering",
  'hifi.zone': "Sone",
  'hifi.chooseZone': "Velg en sone",
  'hifi.noZone': "Ingen sone valgt",
  'hifi.select': "Velg",
  'hifi.selectZone': "Velg denne sonen",
  'hifi.party': "Fest",
  'hifi.partyHint': "Festmodus: alle rommene i dette systemet blir med i sonen som vises",
  'hifi.dragToLink': "Dra navneskiltet til en modul over på en annen for å koble dem.",
  'hifi.speakerSelector': "Høyttalervelger",
  'hifi.output': "Spiller i",
  'hifi.presets': "Forhåndsvalg",
  'hifi.preset': "Forhåndsvalg {n}",
  'hifi.memory': "Minne",
  'hifi.showInTuner': "Vis i tuneren",
  'hifi.track': "Spor",
  'hifi.rec': "Opptak",
  'hifi.eject': "Løs ut",
  'hifi.cue': "Søk",
  'hifi.moreTracks': "Det følger {count} spor til i køen.",
  'hifi.newProgram': "Ny",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Still inn noe på tuneren, eller legg til spor med «Legg til sist i køen».",
  'hifi.allServices': "Alle tjenester",
  'hifi.allServicesGen': "Alle {gen}-tjenester",
  'hifi.playOtherSystem': "Det er på {gen}-systemet. Velg et av rommene der for å spille det.",
  'hifi.playingNow': "Spiller {title}",
  'hifi.queuedNext': "Spiller {title} neste",
  'hifi.replacedQueue': "Køen erstattet med {title}",
  'hifi.addedToQueue': "La til {title} i køen",
  'hifi.selected': "{count} valgt",
  'hifi.otherSystem': "På {gen}-systemet; velg ett av rommene der for å spille fra det",
  'hifi.filterServices': "Filtrer tjenester",
  'hifi.musicSources': "Musikkilder",
  'hifi.view': "Visning",
  'hifi.viewAuto': "Automatisk",
  'hifi.viewGrid': "Rutenett",
  'hifi.viewList': "Liste",
  'hifi.services.none': "Ingen musikktjenester er satt opp på dette systemet ennå.",
  'hifi.services.linked': "Koblet til i Sonora",
  'hifi.services.notLinked': "Satt opp i Sonos-appen, ikke koblet til i Sonora ennå",
  'hifi.alsoRemembered': "Husket, men utenfor rekkevidde: {names}.",
  'hifi.quality': "Kvalitet",
  'hifi.worst': "tregeste ms",
  'hifi.wired': "Kablet",
  'hifi.serviceRemoved': "Fjernet {service}",
  'hifi.moveUp': "Flytt opp",
  'hifi.moveDown': "Flytt ned",
  'hifi.removeSelected': "Fjern {count} valgte",
  'hifi.queueSaved': "Lagret køen som «{title}»",
  'hifi.noPairCandidates': "Ingen annen uparet høyttaler av denne modellen.",
  'hifi.lineIn': "Linjeinngang",
  'hifi.connected': "Tilkoblet",
  'hifi.nothingConnected': "Ingenting tilkoblet",
  'hifi.none': "Ingen",
  'hifi.thisRoom': "Dette rommet",
  'hifi.linkedWith': "Gruppert med {room}",
  'hifi.linkAcrossSystems': "Rom i ulike systemer kan ikke grupperes sammen.",
  'hifi.open': "Åpne",
  'hifi.leaveGroup': "Ta {room} ut av gruppen",
  'hifi.noRooms': "Ingen rom i dette systemet.",
  'hifi.diag.noAnswer': "ingen svar",
  'hifi.setup.account': "Sonos-konto",
  'hifi.setup.services': "Musikktjenester",
  'hifi.setup.services.blurb': 'Strømmetjenestene du har konfigurert.',
  'hifi.setup.library': "Musikkbibliotek",
  'hifi.setup.library.blurb': 'Delte musikkmapper på nettverket ditt.',
  'hifi.setup.time': "Dato og tid",
  'hifi.setup.time.blurb': 'Innstillinger for klokke og tidssone.',
  'hifi.setup.systems': "Systemer og rom",
  'hifi.setup.systems.blurb': 'Hvilke enheter Sonora ser på nettverket ditt.',
  'hifi.setup.parental': "Innholdsfilter",
  'hifi.setup.parental.blurb': 'Filtrering av eksplisitt innhold.',
  'hifi.setup.s2': "Oppgraderingsrådgiver",
  'hifi.setup.network': "Nettverkssjekk",
  'hifi.setup.network.blurb': 'Finn mulige ytelsesproblemer på nettverket ditt.',
  'hifi.setup.appearance': "Utseende",
  'hifi.setup.appearance.blurb': "Temaet Sonora bruker og språket den snakker.",
  'hifi.setup.log': "Logg",
  'hifi.setup.log.blurb': "Hva som gikk galt nylig, nyeste først.",
}

const plPL = {
  'hifi.meter.peak': "Szczyt",
  'hifi.meter.balance': "Balans",
  'hifi.meter.phase': "Faza",
  'hifi.meter.dynamics': "Dynamika",
  'hifi.levelsUnavailable': "Nie można pokazać poziomów tego źródła.",
  'hifi.vuMeters': "Wskaźniki VU",
  'hifi.levelDisplay': "Wskaźnik poziomu",
  'hifi.eqDisplay': "Korektor graficzny",
  'hifi.reload': 'Odśwież',
  'hifi.fn.zones': "Strefy",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Kaseta",
  'hifi.fn.timer': "Minutnik",
  'hifi.fn.setup': "Ustawienia",
  'hifi.function': "Funkcja",
  'hifi.system': "System",
  'hifi.mixtape': "Mixtape {name}",
  'hifi.showControls': "Pokaż sterowanie",
  'hifi.unit.preamp': "Wzmacniacz sterujący",
  'hifi.unit.zones': "Wzmacniacz strefowy",
  'hifi.unit.tuner': "Tuner źródeł",
  'hifi.unit.tape': "Deck kolejki",
  'hifi.unit.timer': "Programator",
  'hifi.unit.setup': "Panel tylny",
  'hifi.ann.shuffle': "Losowo",
  'hifi.ann.repeat': "Powtarzaj",
  'hifi.ann.repeatOne': "Powtarzaj 1",
  'hifi.ann.crossfade': "Przejście",
  'hifi.ann.sleep': "Uśpienie",
  'hifi.info': "Info",
  'hifi.link': "Połącz",
  'hifi.trim': "Dostrajanie",
  'hifi.zone': "Strefa",
  'hifi.chooseZone': "Wybierz strefę",
  'hifi.noZone': "Nie wybrano strefy",
  'hifi.select': "Wybierz",
  'hifi.selectZone': "Wybierz tę strefę",
  'hifi.party': "Impreza",
  'hifi.partyHint': "Tryb imprezy: wszystkie pomieszczenia tego systemu dołączają do widocznej strefy",
  'hifi.dragToLink': "Przeciągnij tabliczkę z nazwą modułu na inny, aby je połączyć.",
  'hifi.speakerSelector': "Przełącznik głośników",
  'hifi.output': "Gra w",
  'hifi.presets': "Pamięci",
  'hifi.preset': "Pamięć {n}",
  'hifi.memory': "Historia",
  'hifi.showInTuner': "Pokaż w tunerze",
  'hifi.track': "Utwór",
  'hifi.rec': "Nagr.",
  'hifi.eject': "Wysuń",
  'hifi.cue': "Szukaj",
  'hifi.moreTracks': "W kolejce jest jeszcze {count} utworów.",
  'hifi.newProgram': "Nowy",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Nastaw coś w tunerze albo dodaj utwory poleceniem „Dodaj na koniec kolejki”.",
  'hifi.allServices': "Wszystkie serwisy",
  'hifi.allServicesGen': "Wszystkie usługi {gen}",
  'hifi.playOtherSystem': "To jest w systemie {gen}. Wybierz jedno z jego pomieszczeń, aby odtworzyć.",
  'hifi.playingNow': "Odtwarzanie: {title}",
  'hifi.queuedNext': "Następne w kolejce: {title}",
  'hifi.replacedQueue': "Kolejka zastąpiona: {title}",
  'hifi.addedToQueue': "Dodano do kolejki: {title}",
  'hifi.selected': "Zaznaczono: {count}",
  'hifi.otherSystem': "W systemie {gen}; wybierz jedno z jego pomieszczeń, aby z niego odtwarzać",
  'hifi.filterServices': "Filtruj serwisy",
  'hifi.musicSources': "Źródła muzyki",
  'hifi.view': "Widok",
  'hifi.viewAuto': "Automatyczny",
  'hifi.viewGrid': "Siatka",
  'hifi.viewList': "Lista",
  'hifi.services.none': "W tym systemie nie skonfigurowano jeszcze żadnych serwisów muzycznych.",
  'hifi.services.linked': "Połączony z aplikacją Sonora",
  'hifi.services.notLinked': "Skonfigurowany w aplikacji Sonos, jeszcze niepołączony z aplikacją Sonora",
  'hifi.alsoRemembered': "Zapamiętane, ale poza zasięgiem: {names}.",
  'hifi.quality': "Jakość",
  'hifi.worst': "najwolniej, ms",
  'hifi.wired': "Przewodowe",
  'hifi.serviceRemoved': "Usunięto serwis {service}",
  'hifi.moveUp': "Przenieś w górę",
  'hifi.moveDown': "Przenieś w dół",
  'hifi.removeSelected': "Usuń zaznaczone ({count})",
  'hifi.queueSaved': "Zapisano kolejkę jako „{title}”",
  'hifi.noPairCandidates': "Brak innego niesparowanego głośnika tego modelu.",
  'hifi.lineIn': "Wejście liniowe",
  'hifi.connected': "Połączono",
  'hifi.nothingConnected': "Nic nie podłączono",
  'hifi.none': "Brak",
  'hifi.thisRoom': "To pomieszczenie",
  'hifi.linkedWith': "Zgrupowane z: {room}",
  'hifi.linkAcrossSystems': "Pomieszczeń z różnych systemów nie można zgrupować.",
  'hifi.open': "Otwórz",
  'hifi.leaveGroup': "Usuń z grupy: {room}",
  'hifi.noRooms': "Brak pomieszczeń w tym systemie.",
  'hifi.diag.noAnswer': "brak odpowiedzi",
  'hifi.setup.account': "Konto Sonos",
  'hifi.setup.services': "Serwisy muzyczne",
  'hifi.setup.services.blurb': 'Skonfigurowane przez Ciebie serwisy streamingowe.',
  'hifi.setup.library': "Biblioteka muzyczna",
  'hifi.setup.library.blurb': 'Udostępnione foldery z muzyką w Twojej sieci.',
  'hifi.setup.time': "Data i godzina",
  'hifi.setup.time.blurb': 'Ustawienia zegara i strefy czasowej.',
  'hifi.setup.systems': "Systemy i pomieszczenia",
  'hifi.setup.systems.blurb': 'Jakie urządzenia Sonora widzi w Twojej sieci.',
  'hifi.setup.parental': "Filtry zawartości",
  'hifi.setup.parental.blurb': 'Filtrowanie treści dla dorosłych.',
  'hifi.setup.s2': "Doradca aktualizacji",
  'hifi.setup.network': "Test sieci",
  'hifi.setup.network.blurb': 'Wykryj możliwe problemy z wydajnością w Twojej sieci.',
  'hifi.setup.appearance': "Wygląd",
  'hifi.setup.appearance.blurb': "Motyw aplikacji Sonora i jej język.",
  'hifi.setup.log': "Dziennik",
  'hifi.setup.log.blurb': "Ostatnie błędy, od najnowszych.",
}

const ptPT = {
  'hifi.meter.peak': "Pico",
  'hifi.meter.balance': "Balanço",
  'hifi.meter.phase': "Fase",
  'hifi.meter.dynamics': "Dinâmica",
  'hifi.levelsUnavailable': "Não é possível mostrar os níveis desta fonte.",
  'hifi.vuMeters': "Medidores VU",
  'hifi.levelDisplay': "Indicador de nível",
  'hifi.eqDisplay': "Equalizador gráfico",
  'hifi.reload': 'Recarregar',
  'hifi.fn.zones': "Zonas",
  'hifi.fn.tuner': "Sintonizador",
  'hifi.fn.tape': "Cassete",
  'hifi.fn.timer': "Temporizador",
  'hifi.fn.setup': "Definições",
  'hifi.function': "Função",
  'hifi.system': "Sistema",
  'hifi.mixtape': "Mixtape {name}",
  'hifi.showControls': "Mostrar os controlos",
  'hifi.unit.preamp': "Amplificador de controlo",
  'hifi.unit.zones': "Amplificador de zonas",
  'hifi.unit.tuner': "Sintonizador de fontes",
  'hifi.unit.tape': "Deck da fila",
  'hifi.unit.timer': "Temporizador de programas",
  'hifi.unit.setup': "Painel traseiro",
  'hifi.ann.shuffle': "Aleatório",
  'hifi.ann.repeat': "Repetir",
  'hifi.ann.repeatOne': "Repetir 1",
  'hifi.ann.crossfade': "Transição",
  'hifi.ann.sleep': "Dormir",
  'hifi.info': "Info",
  'hifi.link': "Ligar",
  'hifi.trim': "Ajuste fino",
  'hifi.zone': "Zona",
  'hifi.chooseZone': "Escolher uma zona",
  'hifi.noZone': "Nenhuma zona escolhida",
  'hifi.select': "Escolher",
  'hifi.selectZone': "Escolher esta zona",
  'hifi.party': "Festa",
  'hifi.partyHint': "Modo festa: todas as divisões deste sistema juntam-se à zona à vista",
  'hifi.dragToLink': "Arraste a placa com o nome de um módulo para cima de outro para os ligar.",
  'hifi.speakerSelector': "Seletor de colunas",
  'hifi.output': "Toca em",
  'hifi.presets': "Predefinições",
  'hifi.preset': "Predefinição {n}",
  'hifi.memory': "Memória",
  'hifi.showInTuner': "Mostrar no sintonizador",
  'hifi.track': "Faixa",
  'hifi.rec': "Gravar",
  'hifi.eject': "Ejetar",
  'hifi.cue': "Localizar",
  'hifi.moreTracks': "Seguem-se mais {count} faixas na fila.",
  'hifi.newProgram': "Novo",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Sintonize algo no sintonizador ou adicione faixas com «Adicionar ao fim da fila».",
  'hifi.allServices': "Todos os serviços",
  'hifi.allServicesGen': "Todos os serviços do {gen}",
  'hifi.playOtherSystem': "Isso está no sistema {gen}. Escolha uma das suas divisões para reproduzir.",
  'hifi.playingNow': "A reproduzir {title}",
  'hifi.queuedNext': "{title} será reproduzido a seguir",
  'hifi.replacedQueue': "Fila substituída por {title}",
  'hifi.addedToQueue': "{title} foi adicionado à fila",
  'hifi.selected': "{count} selecionados",
  'hifi.otherSystem': "No sistema {gen}; escolha uma das suas divisões para reproduzir a partir dele",
  'hifi.filterServices': "Filtrar serviços",
  'hifi.musicSources': "Origens de música",
  'hifi.view': "Vista",
  'hifi.viewAuto': "Automática",
  'hifi.viewGrid': "Grelha",
  'hifi.viewList': "Lista",
  'hifi.services.none': "Ainda não há serviços de música configurados neste sistema.",
  'hifi.services.linked': "Associado no Sonora",
  'hifi.services.notLinked': "Configurado na aplicação Sonos, ainda não associado no Sonora",
  'hifi.alsoRemembered': "Também memorizadas, mas fora de alcance: {names}.",
  'hifi.quality': "Qualidade",
  'hifi.worst': "pior ms",
  'hifi.wired': "Com fios",
  'hifi.serviceRemoved': "{service} removido",
  'hifi.moveUp': "Mover para cima",
  'hifi.moveDown': "Mover para baixo",
  'hifi.removeSelected': "Remover {count} selecionados",
  'hifi.queueSaved': "Fila guardada como «{title}»",
  'hifi.noPairCandidates': "Não há outro altifalante sem par deste modelo.",
  'hifi.lineIn': "Entrada de linha",
  'hifi.connected': "Ligado",
  'hifi.nothingConnected': "Nada ligado",
  'hifi.none': "Nenhum",
  'hifi.thisRoom': "Esta divisão",
  'hifi.linkedWith': "Agrupada com {room}",
  'hifi.linkAcrossSystems': "Não é possível agrupar divisões de sistemas diferentes.",
  'hifi.open': "Abrir",
  'hifi.leaveGroup': "Retirar {room} do grupo",
  'hifi.noRooms': "Não há divisões neste sistema.",
  'hifi.diag.noAnswer': "sem resposta",
  'hifi.setup.account': "Conta Sonos",
  'hifi.setup.services': "Serviços de música",
  'hifi.setup.services.blurb': 'Os serviços de streaming que configurou.',
  'hifi.setup.library': "Biblioteca de música",
  'hifi.setup.library.blurb': 'Pastas de música partilhadas na sua rede.',
  'hifi.setup.time': "Data e hora",
  'hifi.setup.time.blurb': 'Definições de relógio e fuso horário.',
  'hifi.setup.systems': "Sistemas e divisões",
  'hifi.setup.systems.blurb': 'Que dispositivos o Sonora vê na sua rede.',
  'hifi.setup.parental': "Filtros de conteúdo",
  'hifi.setup.parental.blurb': 'Filtragem de conteúdo explícito.',
  'hifi.setup.s2': "Assistente de atualização",
  'hifi.setup.network': "Verificação da rede",
  'hifi.setup.network.blurb': 'Identifique possíveis problemas de desempenho na sua rede.',
  'hifi.setup.appearance': "Aspeto",
  'hifi.setup.appearance.blurb': "O tema que o Sonora usa e o idioma em que fala.",
  'hifi.setup.log': "Registo",
  'hifi.setup.log.blurb': "O que correu mal recentemente, do mais recente para o mais antigo.",
}

const svSE = {
  'hifi.meter.peak': "Topp",
  'hifi.meter.balance': "Balans",
  'hifi.meter.phase': "Fas",
  'hifi.meter.dynamics': "Dynamik",
  'hifi.levelsUnavailable': "Nivåer kan inte visas för den här källan.",
  'hifi.vuMeters': "VU-mätare",
  'hifi.levelDisplay': "Nivåvisning",
  'hifi.eqDisplay': "Grafisk equalizer",
  'hifi.reload': 'Läs in igen',
  'hifi.fn.zones': "Zoner",
  'hifi.fn.tuner': "Tuner",
  'hifi.fn.tape': "Kassett",
  'hifi.fn.timer': "Timer",
  'hifi.fn.setup': "Inställningar",
  'hifi.function': "Funktion",
  'hifi.system': "System",
  'hifi.mixtape': "{name}-mixtape",
  'hifi.showControls': "Visa reglagen",
  'hifi.unit.preamp': "Kontrollförstärkare",
  'hifi.unit.zones': "Zonförstärkare",
  'hifi.unit.tuner': "Källtuner",
  'hifi.unit.tape': "Ködäck",
  'hifi.unit.timer': "Programtimer",
  'hifi.unit.setup': "Bakpanel",
  'hifi.ann.shuffle': "Blanda",
  'hifi.ann.repeat': "Upprepa",
  'hifi.ann.repeatOne': "Upprepa 1",
  'hifi.ann.crossfade': "Övertoning",
  'hifi.ann.sleep': "Sov",
  'hifi.info': "Info",
  'hifi.link': "Koppla",
  'hifi.trim': "Finjustering",
  'hifi.zone': "Zon",
  'hifi.chooseZone': "Välj en zon",
  'hifi.noZone': "Ingen zon vald",
  'hifi.select': "Välj",
  'hifi.selectZone': "Välj den här zonen",
  'hifi.party': "Fest",
  'hifi.partyHint': "Festläge: alla rum i systemet ansluter till zonen som visas",
  'hifi.dragToLink': "Dra en moduls namnskylt till en annan för att koppla ihop dem.",
  'hifi.speakerSelector': "Högtalarväljare",
  'hifi.output': "Spelar i",
  'hifi.presets': "Förval",
  'hifi.preset': "Förval {n}",
  'hifi.memory': "Minne",
  'hifi.showInTuner': "Visa i tunern",
  'hifi.track': "Spår",
  'hifi.rec': "Insp.",
  'hifi.eject': "Mata ut",
  'hifi.cue': "Sök",
  'hifi.moreTracks': "Det följer {count} spår till i kön.",
  'hifi.newProgram': "Ny",
  'hifi.program': "Prog. {n}",
  'hifi.queueEmptyBody': "Ställ in något på tunern, eller lägg till spår med ”Lägg till sist i kön”.",
  'hifi.allServices': "Alla tjänster",
  'hifi.allServicesGen': "Alla {gen}-tjänster",
  'hifi.playOtherSystem': "Det finns i {gen}-systemet. Välj ett av dess rum för att spela det.",
  'hifi.playingNow': "Spelar {title}",
  'hifi.queuedNext': "Spelar {title} härnäst",
  'hifi.replacedQueue': "Kön ersattes med {title}",
  'hifi.addedToQueue': "{title} lades till i kön",
  'hifi.selected': "{count} markerade",
  'hifi.otherSystem': "I {gen}-systemet; välj ett av dess rum för att spela från det",
  'hifi.filterServices': "Filtrera tjänster",
  'hifi.musicSources': "Musikkällor",
  'hifi.view': "Visning",
  'hifi.viewAuto': "Automatiskt",
  'hifi.viewGrid': "Rutnät",
  'hifi.viewList': "Lista",
  'hifi.services.none': "Inga musiktjänster har konfigurerats i det här systemet än.",
  'hifi.services.linked': "Länkad i Sonora",
  'hifi.services.notLinked': "Konfigurerad i Sonos-appen, inte ännu länkad i Sonora",
  'hifi.alsoRemembered': "Minns också, men utom räckhåll: {names}.",
  'hifi.quality': "Kvalitet",
  'hifi.worst': "sämst ms",
  'hifi.wired': "Trådbunden",
  'hifi.serviceRemoved': "{service} togs bort",
  'hifi.moveUp': "Flytta upp",
  'hifi.moveDown': "Flytta ned",
  'hifi.removeSelected': "Ta bort {count} markerade",
  'hifi.queueSaved': "Kön sparades som ”{title}”",
  'hifi.noPairCandidates': "Ingen annan oparad högtalare av den här modellen.",
  'hifi.lineIn': "Linjeingång",
  'hifi.connected': "Ansluten",
  'hifi.nothingConnected': "Inget anslutet",
  'hifi.none': "Inga",
  'hifi.thisRoom': "Det här rummet",
  'hifi.linkedWith': "Grupperad med {room}",
  'hifi.linkAcrossSystems': "Rum i olika system kan inte grupperas med varandra.",
  'hifi.open': "Öppna",
  'hifi.leaveGroup': "Ta ut {room} ur gruppen",
  'hifi.noRooms': "Inga rum i det här systemet.",
  'hifi.diag.noAnswer': "inget svar",
  'hifi.setup.account': "Sonos-konto",
  'hifi.setup.services': "Musiktjänster",
  'hifi.setup.services.blurb': 'Streamingtjänsterna du har konfigurerat.',
  'hifi.setup.library': "Musikbibliotek",
  'hifi.setup.library.blurb': 'Delade musikmappar i ditt nätverk.',
  'hifi.setup.time': "Datum och tid",
  'hifi.setup.time.blurb': 'Inställningar för klocka och tidszon.',
  'hifi.setup.systems': "System och rum",
  'hifi.setup.systems.blurb': 'Vilka enheter Sonora ser i ditt nätverk.',
  'hifi.setup.parental': "Innehållsfilter",
  'hifi.setup.parental.blurb': 'Filtrering av explicit innehåll.',
  'hifi.setup.s2': "Uppgraderingsguide",
  'hifi.setup.network': "Nätverkskontroll",
  'hifi.setup.network.blurb': 'Hitta möjliga prestandaproblem i ditt nätverk.',
  'hifi.setup.appearance': "Utseende",
  'hifi.setup.appearance.blurb': "Temat Sonora använder och språket den talar.",
  'hifi.setup.log': "Logg",
  'hifi.setup.log.blurb': "Vad som har gått fel nyligen, senaste först.",
}

export default { 'en-US': enUS, 'es-ES': esES, 'hu-HU': huHU, 'fr-FR': frFR, 'de-DE': deDE, 'it-IT': itIT, 'pt-BR': ptBR, 'nl-NL': nlNL, 'uk-UA': ukUA, 'ja-JP': jaJP, 'ko-KR': koKR, 'zh-CN': zhCN, 'zh-TW': zhTW, 'cs-CZ': csCZ, 'da-DK': daDK, 'fi-FI': fiFI, 'nb-NO': nbNO, 'pl-PL': plPL, 'pt-PT': ptPT, 'sv-SE': svSE }
