// Material Girl's own words, in every language Sonora speaks. The i18n layer
// lays these over the core catalog while this theme is the chosen one. Where
// one of them says what a Sonofuture string says, it carries Sonora's own
// translation of that string; the rest were translated for this theme.

const enUS = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Rooms',
  'mg.nav.clock': 'Alarms',
  'mg.nav.settings': 'Settings',
  'mg.navigation': 'Sections',
  'mg.all': 'All',
  'mg.greeting.morning': 'Good morning',
  'mg.greeting.afternoon': 'Good afternoon',
  'mg.greeting.evening': 'Good evening',
  'mg.greeting.overnight': 'Good night',
  'mg.playingIn': 'Playing in {rooms}',
  'mg.dragToGroup': 'Drag one room onto another to group them.',
  'mg.groupAcrossSystems': 'Rooms on different systems cannot be grouped together.',
  'mg.forRoom': 'for {room}',
  'mg.recent': 'Recently played',
  'mg.quietRooms.one': '{count} quiet room',
  'mg.quietRooms.other': '{count} quiet rooms',
  'mg.open': 'Open',
  'mg.playingNow': 'Playing {title}',
  'mg.queuedNext': 'Playing {title} next',
  'mg.addedToQueue': 'Added {title} to the queue',
  'mg.replacedQueue': 'Queue replaced with {title}',
  'mg.queueEmptyBody': 'Play something from the Library, or add tracks with "Add to End of Queue".',
  'mg.queueSaved': 'Saved the queue as "{title}"',
  'mg.moveUp': 'Move up',
  'mg.moveDown': 'Move down',
  'mg.removeSelected': 'Remove {count} selected',
  'mg.selected': '{count} selected',
  'mg.editGroup': 'Edit group',
  'mg.addRooms': 'Add rooms',
  'mg.leaveGroup': 'Take {room} out of the group',
  'mg.thisRoom': 'This room',
  'mg.groupedWith': 'Grouped with {room}',
  'mg.noPairCandidates': 'No other unpaired speaker of this model.',
  'mg.lineIn': 'Line-In',
  'mg.connected': 'Connected',
  'mg.nothingConnected': 'Nothing connected',
  'mg.none': 'None',
  'mg.musicSources': 'Music Sources',
  'mg.activeRoom': 'Playing in',
  'mg.chooseRoom': 'Choose a room',
  'mg.otherSystem': 'On the {gen} system; choose one of its rooms to play from it',
  'mg.allServices': 'All services',
  'mg.allServicesGen': 'All {gen} Services',
  'mg.playOtherSystem': 'That is on the {gen} system. Choose one of its rooms to play it.',
  'mg.view': 'View',
  'mg.viewAuto': 'Automatic',
  'mg.viewGrid': 'Grid',
  'mg.viewList': 'List',
  'mg.filterServices': 'Filter services',
  'mg.searchIn': 'Search "{term}" in {service}',
  'mg.search.rooms': 'Rooms',
  'mg.search.actions': 'Actions',
  'mg.search.music': 'Music',
  'mg.search.services': 'Music services',
  'mg.partyMode': 'Party mode',
  'mg.serviceRemoved': 'Removed {service}',
  'mg.quality': 'Quality',
  'mg.worst': 'worst ms',
  'mg.wired': 'Wired',
  'mg.noRooms': 'No rooms in this system.',
  'mg.services.none': 'No music services are set up on this system yet.',
  'mg.services.linked': 'Linked in Sonora',
  'mg.services.notLinked': 'Set up in the Sonos app, not yet linked in Sonora',
  'mg.alsoRemembered': 'Also remembered but out of reach: {names}.',
  'mg.noAnswer': 'no answer',
  'mg.favoritesEmpty': 'Anything you save as a Sonos Favorite, in any controller, appears here. The speakers hold the list, so it is the same list everywhere.',
  'mg.playlistsEmpty': 'Sonos Playlists are queues you have saved. There are none on this system yet.',
  'mg.settings.account': 'Sonos Account',
  'mg.settings.account.blurb': 'Sign in to unlock more features.',
  'mg.settings.services': 'Music services',
  'mg.settings.services.blurb': "The streaming services you've configured.",
  'mg.settings.library': 'Music library',
  'mg.settings.library.blurb': 'Shared music folders on your network.',
  'mg.settings.time': 'Date and time',
  'mg.settings.time.blurb': 'Clock and time zone settings.',
  'mg.settings.systems': 'Systems and rooms',
  'mg.settings.systems.blurb': 'What devices Sonora sees on your network.',
  'mg.settings.parental': 'Content Filters',
  'mg.settings.parental.blurb': 'Explicit content filtering.',
  'mg.settings.s2': 'Upgrade advisor',
  'mg.settings.s2.blurb': 'Upgrade your Sonos system.',
  'mg.settings.network': 'Network check',
  'mg.settings.network.blurb': 'Identify potential performance issues on your network.',
  'mg.settings.appearance': 'Appearance',
  'mg.settings.appearance.blurb': 'The theme Sonora wears and the language it speaks.',
  'mg.settings.log': 'Log',
  'mg.settings.log.blurb': 'What went wrong recently, newest first.',
  'mg.nav.listen': 'Listen',
  'mg.nav.browse': 'Browse',
  'mg.showInBrowse': 'Show in Browse',
  'mg.collapseRail': 'Collapse navigation',
  'mg.expandRail': 'Expand navigation',
  'mg.openPlayer': 'Open the player',
  'mg.closePlayer': 'Close the player',
  'mg.playModes': 'Play modes',
  'mg.upNext': 'Up next',
  'mg.upNextAndRooms': 'Up next and rooms',
  'mg.inThisRoom': 'In this room',
  'mg.soundAndRoom': 'Sound and settings',
  'mg.allRooms': 'All rooms',
  'mg.dragToReorder': 'Drag to reorder',
  'mg.playsIn': 'Plays in {room}',
  'mg.searchHint': 'Search rooms, actions, favorites, or a service',
  'mg.dynamicColor': 'Colors from the cover',
  'mg.dynamicColorBody': 'Tint the whole interface with the colors of what is playing in the room in view.',
  'mg.reload': 'Reload',
}

const esES = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Habitaciones',
  'mg.nav.clock': 'Alarmas',
  'mg.nav.settings': 'Ajustes',
  'mg.navigation': 'Secciones',
  'mg.all': 'Todos',
  'mg.greeting.morning': 'Buenos días',
  'mg.greeting.afternoon': 'Buenas tardes',
  'mg.greeting.evening': 'Buenas noches',
  'mg.greeting.overnight': 'Buenas noches',
  'mg.playingIn': 'Sonando en {rooms}',
  'mg.dragToGroup': 'Arrastra una habitación sobre otra para agruparlas.',
  'mg.groupAcrossSystems': 'No se pueden agrupar habitaciones de sistemas distintos.',
  'mg.forRoom': 'para {room}',
  'mg.recent': 'Reproducido hace poco',
  'mg.quietRooms.one': '{count} habitación en silencio',
  'mg.quietRooms.other': '{count} habitaciones en silencio',
  'mg.open': 'Abrir',
  'mg.playingNow': 'Reproduciendo {title}',
  'mg.queuedNext': '{title} sonará a continuación',
  'mg.addedToQueue': '{title} añadido a la cola',
  'mg.replacedQueue': 'Cola sustituida por {title}',
  'mg.queueEmptyBody': 'Reproduce algo desde la biblioteca o añade pistas con "Añadir al final de la cola".',
  'mg.queueSaved': 'Cola guardada como "{title}"',
  'mg.moveUp': 'Subir',
  'mg.moveDown': 'Bajar',
  'mg.removeSelected': 'Quitar {count} seleccionadas',
  'mg.selected': '{count} seleccionados',
  'mg.editGroup': 'Editar grupo',
  'mg.addRooms': 'Añadir habitaciones',
  'mg.leaveGroup': 'Sacar {room} del grupo',
  'mg.thisRoom': 'Esta habitación',
  'mg.groupedWith': 'Agrupada con {room}',
  'mg.noPairCandidates': 'No hay otro altavoz de este modelo sin emparejar.',
  'mg.lineIn': 'Entrada de línea',
  'mg.connected': 'Conectada',
  'mg.nothingConnected': 'Nada conectado',
  'mg.none': 'Ninguna',
  'mg.musicSources': 'Fuentes de música',
  'mg.activeRoom': 'Sonando en',
  'mg.chooseRoom': 'Elegir una habitación',
  'mg.otherSystem': 'En el sistema {gen}; elige una de sus habitaciones para reproducir desde él',
  'mg.allServices': 'Todos los servicios',
  'mg.allServicesGen': 'Todos los servicios de {gen}',
  'mg.playOtherSystem': 'Está en el sistema {gen}. Elige una de sus habitaciones para reproducirlo.',
  'mg.view': 'Vista',
  'mg.viewAuto': 'Automática',
  'mg.viewGrid': 'Cuadrícula',
  'mg.viewList': 'Lista',
  'mg.filterServices': 'Filtrar servicios',
  'mg.searchIn': 'Buscar "{term}" en {service}',
  'mg.search.rooms': 'Habitaciones',
  'mg.search.actions': 'Acciones',
  'mg.search.music': 'Música',
  'mg.search.services': 'Servicios de música',
  'mg.partyMode': 'Modo fiesta',
  'mg.serviceRemoved': '{service} eliminado',
  'mg.quality': 'Calidad',
  'mg.worst': 'peor ms',
  'mg.wired': 'Por cable',
  'mg.noRooms': 'No hay habitaciones en este sistema.',
  'mg.services.none': 'Este sistema aún no tiene servicios de música configurados.',
  'mg.services.linked': 'Vinculado en Sonora',
  'mg.services.notLinked': 'Configurado en la app de Sonos, aún no vinculado en Sonora',
  'mg.alsoRemembered': 'También recordadas pero fuera de alcance: {names}.',
  'mg.noAnswer': 'sin respuesta',
  'mg.favoritesEmpty': 'Todo lo que guardes como favorito de Sonos, en cualquier controlador, aparece aquí. Los altavoces guardan la lista, así que es la misma en todas partes.',
  'mg.playlistsEmpty': 'Las listas de Sonos son colas que has guardado. Todavía no hay ninguna en este sistema.',
  'mg.settings.account': 'Cuenta de Sonos',
  'mg.settings.account.blurb': 'Inicia sesión para desbloquear más funciones.',
  'mg.settings.services': 'Servicios de música',
  'mg.settings.services.blurb': 'Los servicios de streaming que has configurado.',
  'mg.settings.library': 'Biblioteca de música',
  'mg.settings.library.blurb': 'Carpetas de música compartidas en tu red.',
  'mg.settings.time': 'Fecha y hora',
  'mg.settings.time.blurb': 'Ajustes de reloj y zona horaria.',
  'mg.settings.systems': 'Sistemas y habitaciones',
  'mg.settings.systems.blurb': 'Qué dispositivos ve Sonora en tu red.',
  'mg.settings.parental': 'Filtros de contenido',
  'mg.settings.parental.blurb': 'Filtrado de contenido explícito.',
  'mg.settings.s2': 'Asesor de actualización',
  'mg.settings.s2.blurb': 'Actualiza tu sistema Sonos.',
  'mg.settings.network': 'Comprobación de red',
  'mg.settings.network.blurb': 'Detecta posibles problemas de rendimiento en tu red.',
  'mg.settings.appearance': 'Apariencia',
  'mg.settings.appearance.blurb': 'El tema que lleva Sonora y el idioma en que habla.',
  'mg.settings.log': 'Registro',
  'mg.settings.log.blurb': 'Lo que ha fallado últimamente, lo más reciente primero.',
  'mg.nav.listen': 'Escuchar',
  'mg.nav.browse': 'Explorar',
  'mg.showInBrowse': 'Mostrar en Explorar',
  'mg.collapseRail': 'Contraer la navegación',
  'mg.expandRail': 'Expandir la navegación',
  'mg.openPlayer': 'Abrir el reproductor',
  'mg.closePlayer': 'Cerrar el reproductor',
  'mg.playModes': 'Modos de reproducción',
  'mg.upNext': 'A continuación',
  'mg.upNextAndRooms': 'A continuación y habitaciones',
  'mg.inThisRoom': 'En esta habitación',
  'mg.soundAndRoom': 'Sonido y ajustes',
  'mg.allRooms': 'Todas las habitaciones',
  'mg.dragToReorder': 'Arrastra para cambiar el orden',
  'mg.playsIn': 'Suena en {room}',
  'mg.searchHint': 'Busca habitaciones, acciones, favoritos o un servicio',
  'mg.dynamicColor': 'Colores de la portada',
  'mg.dynamicColorBody': 'Tiñe toda la interfaz con los colores de lo que suena en la habitación que estás viendo.',
  'mg.reload': 'Recargar',
}

const huHU = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Szobák',
  'mg.nav.clock': 'Ébresztők',
  'mg.nav.settings': 'Beállítások',
  'mg.navigation': 'Szakaszok',
  'mg.all': 'Mind',
  'mg.greeting.morning': 'Jó reggelt',
  'mg.greeting.afternoon': 'Jó napot',
  'mg.greeting.evening': 'Jó estét',
  'mg.greeting.overnight': 'Jó éjszakát',
  'mg.playingIn': 'Lejátszás: {rooms}',
  'mg.dragToGroup': 'Húzz egy szobát egy másikra a csoportosításhoz.',
  'mg.groupAcrossSystems': 'Különböző rendszerek szobái nem csoportosíthatók.',
  'mg.forRoom': '{room} számára',
  'mg.recent': 'Nemrég hallgatott',
  'mg.quietRooms.one': '{count} csendes szoba',
  'mg.quietRooms.other': '{count} csendes szoba',
  'mg.open': 'Megnyitás',
  'mg.playingNow': '{title} lejátszása',
  'mg.queuedNext': '{title} következik',
  'mg.addedToQueue': '{title} a sor végére került',
  'mg.replacedQueue': 'A sor helyére: {title}',
  'mg.queueEmptyBody': 'Játssz le valamit a könyvtárból, vagy adj hozzá számokat a „Sor végére” paranccsal.',
  'mg.queueSaved': 'Sor elmentve „{title}” néven',
  'mg.moveUp': 'Feljebb',
  'mg.moveDown': 'Lejjebb',
  'mg.removeSelected': '{count} kijelölt eltávolítása',
  'mg.selected': '{count} kijelölve',
  'mg.editGroup': 'Csoport szerkesztése',
  'mg.addRooms': 'Szobák hozzáadása',
  'mg.leaveGroup': '{room} kivétele a csoportból',
  'mg.thisRoom': 'Ez a szoba',
  'mg.groupedWith': 'Csoportban: {room}',
  'mg.noPairCandidates': 'Nincs másik párosítatlan hangszóró ebből a típusból.',
  'mg.lineIn': 'Vonalbemenet',
  'mg.connected': 'Csatlakoztatva',
  'mg.nothingConnected': 'Nincs csatlakoztatva semmi',
  'mg.none': 'Nincs',
  'mg.musicSources': 'Zeneforrások',
  'mg.activeRoom': 'Lejátszás itt',
  'mg.chooseRoom': 'Válassz szobát',
  'mg.otherSystem': 'A(z) {gen} rendszeren; válaszd annak egy szobáját a lejátszáshoz',
  'mg.allServices': 'Minden szolgáltatás',
  'mg.allServicesGen': 'Minden {gen}-szolgáltatás',
  'mg.playOtherSystem': 'Ez a(z) {gen} rendszeren van. Válaszd ki egyik szobáját a lejátszáshoz.',
  'mg.view': 'Nézet',
  'mg.viewAuto': 'Automatikus',
  'mg.viewGrid': 'Rács',
  'mg.viewList': 'Lista',
  'mg.filterServices': 'Szolgáltatások szűrése',
  'mg.searchIn': '„{term}” keresése itt: {service}',
  'mg.search.rooms': 'Szobák',
  'mg.search.actions': 'Műveletek',
  'mg.search.music': 'Zene',
  'mg.search.services': 'Zeneszolgáltatások',
  'mg.partyMode': 'Party mód',
  'mg.serviceRemoved': '{service} eltávolítva',
  'mg.quality': 'Minőség',
  'mg.worst': 'legrosszabb ms',
  'mg.wired': 'Vezetékes',
  'mg.noRooms': 'Ebben a rendszerben nincs szoba.',
  'mg.services.none': 'Ezen a rendszeren még nincs beállított zeneszolgáltatás.',
  'mg.services.linked': 'Összekapcsolva a Sonorával',
  'mg.services.notLinked': 'A Sonos alkalmazásban beállítva, a Sonorában még nincs összekapcsolva',
  'mg.alsoRemembered': 'Emlékszik rájuk, de nem éri el: {names}.',
  'mg.noAnswer': 'nincs válasz',
  'mg.favoritesEmpty': 'Amit Sonos kedvencként mentesz — bármelyik vezérlőben —, itt jelenik meg. A listát a hangszórók tárolják, így mindenhol ugyanaz.',
  'mg.playlistsEmpty': 'A Sonos lejátszási listák elmentett várólisták. Ezen a rendszeren még nincs egy sem.',
  'mg.settings.account': 'Sonos-fiók',
  'mg.settings.account.blurb': 'Jelentkezz be további funkciókért.',
  'mg.settings.services': 'Zeneszolgáltatások',
  'mg.settings.services.blurb': 'A beállított streamingszolgáltatások.',
  'mg.settings.library': 'Zenekönyvtár',
  'mg.settings.library.blurb': 'Megosztott zenemappák a hálózaton.',
  'mg.settings.time': 'Dátum és idő',
  'mg.settings.time.blurb': 'Óra és időzóna beállításai.',
  'mg.settings.systems': 'Rendszerek és szobák',
  'mg.settings.systems.blurb': 'Milyen eszközöket lát a Sonora a hálózaton.',
  'mg.settings.parental': 'Tartalomszűrők',
  'mg.settings.parental.blurb': 'Szókimondó tartalmak szűrése.',
  'mg.settings.s2': 'Frissítési tanácsadó',
  'mg.settings.s2.blurb': 'Frissítsd a Sonos-rendszered.',
  'mg.settings.network': 'Hálózat-ellenőrzés',
  'mg.settings.network.blurb': 'A hálózat lehetséges teljesítményproblémáinak feltárása.',
  'mg.settings.appearance': 'Megjelenés',
  'mg.settings.appearance.blurb': 'A téma, amit a Sonora visel, és a nyelv, amin beszél.',
  'mg.settings.log': 'Napló',
  'mg.settings.log.blurb': 'Ami mostanában elromlott, a legújabb elöl.',
  'mg.nav.listen': 'Hallgatás',
  'mg.nav.browse': 'Böngészés',
  'mg.showInBrowse': 'Mutasd a Böngészésben',
  'mg.collapseRail': 'Navigáció összecsukása',
  'mg.expandRail': 'Navigáció kibontása',
  'mg.openPlayer': 'Lejátszó megnyitása',
  'mg.closePlayer': 'Lejátszó bezárása',
  'mg.playModes': 'Lejátszási módok',
  'mg.upNext': 'Következik',
  'mg.upNextAndRooms': 'Következik és szobák',
  'mg.inThisRoom': 'Ebben a szobában',
  'mg.soundAndRoom': 'Hang és beállítások',
  'mg.allRooms': 'Minden szoba',
  'mg.dragToReorder': 'Húzd az átrendezéshez',
  'mg.playsIn': 'Szól itt: {room}',
  'mg.searchHint': 'Szobák, műveletek, kedvencek vagy egy szolgáltatás keresése',
  'mg.dynamicColor': 'Színek a borítóról',
  'mg.dynamicColorBody': 'Az egész felületet annak a színeivel festi meg, ami a látott szobában szól.',
  'mg.reload': 'Újratöltés',
}

const frFR = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Pièces',
  'mg.nav.clock': 'Alarmes',
  'mg.nav.settings': 'Réglages',
  'mg.navigation': 'Sections',
  'mg.all': 'Tout',
  'mg.greeting.morning': 'Bonjour',
  'mg.greeting.afternoon': 'Bon après-midi',
  'mg.greeting.evening': 'Bonsoir',
  'mg.greeting.overnight': 'Bonne nuit',
  'mg.playingIn': 'Lecture dans {rooms}',
  'mg.dragToGroup': 'Fais glisser une pièce sur une autre pour les grouper.',
  'mg.groupAcrossSystems': 'Des pièces de systèmes différents ne peuvent pas être groupées.',
  'mg.forRoom': 'pour {room}',
  'mg.recent': 'Écouté récemment',
  'mg.quietRooms.one': '{count} pièce silencieuse',
  'mg.quietRooms.other': '{count} pièces silencieuses',
  'mg.open': 'Ouvrir',
  'mg.playingNow': 'Lecture de {title}',
  'mg.queuedNext': '{title} sera lu ensuite',
  'mg.addedToQueue': '{title} a été ajouté à la file d’attente',
  'mg.replacedQueue': 'File d’attente remplacée par {title}',
  'mg.queueEmptyBody': 'Lance quelque chose depuis la bibliothèque, ou ajoute des titres avec « Ajouter à la fin de la file d’attente ».',
  'mg.queueSaved': 'File d’attente enregistrée sous « {title} »',
  'mg.moveUp': 'Monter',
  'mg.moveDown': 'Descendre',
  'mg.removeSelected': 'Supprimer les {count} sélectionnés',
  'mg.selected': '{count} sélectionnés',
  'mg.editGroup': 'Modifier le groupe',
  'mg.addRooms': 'Ajouter des pièces',
  'mg.leaveGroup': 'Retirer {room} du groupe',
  'mg.thisRoom': 'Cette pièce',
  'mg.groupedWith': 'Groupée avec {room}',
  'mg.noPairCandidates': 'Aucune autre enceinte non appairée de ce modèle.',
  'mg.lineIn': 'Entrée ligne',
  'mg.connected': 'Connectée',
  'mg.nothingConnected': 'Rien de connecté',
  'mg.none': 'Aucun',
  'mg.musicSources': 'Sources de musique',
  'mg.activeRoom': 'Lecture dans',
  'mg.chooseRoom': 'Choisir une pièce',
  'mg.otherSystem': 'Sur le système {gen} ; choisis l’une de ses pièces pour y lire',
  'mg.allServices': 'Tous les services',
  'mg.allServicesGen': 'Tous les services {gen}',
  'mg.playOtherSystem': 'C\'est sur le système {gen}. Choisis l\'une de ses pièces pour le lire.',
  'mg.view': 'Affichage',
  'mg.viewAuto': 'Automatique',
  'mg.viewGrid': 'Grille',
  'mg.viewList': 'Liste',
  'mg.filterServices': 'Filtrer les services',
  'mg.searchIn': 'Rechercher « {term} » dans {service}',
  'mg.search.rooms': 'Pièces',
  'mg.search.actions': 'Actions',
  'mg.search.music': 'Musique',
  'mg.search.services': 'Services de musique',
  'mg.partyMode': 'Mode fête',
  'mg.serviceRemoved': '{service} a été supprimé',
  'mg.quality': 'Qualité',
  'mg.worst': 'pire ms',
  'mg.wired': 'Filaire',
  'mg.noRooms': 'Aucune pièce dans ce système.',
  'mg.services.none': 'Aucun service de musique n’est encore configuré sur ce système.',
  'mg.services.linked': 'Associé dans Sonora',
  'mg.services.notLinked': 'Configuré dans l’application Sonos, pas encore associé dans Sonora',
  'mg.alsoRemembered': 'Également en mémoire mais hors de portée : {names}.',
  'mg.noAnswer': 'aucune réponse',
  'mg.favoritesEmpty': 'Tout ce que tu enregistres comme favori Sonos, depuis n’importe quel contrôleur, apparaît ici. Ce sont les enceintes qui conservent la liste : elle est donc la même partout.',
  'mg.playlistsEmpty': 'Les listes de lecture Sonos sont des files d’attente que tu as enregistrées. Il n’y en a encore aucune sur ce système.',
  'mg.settings.account': 'Compte Sonos',
  'mg.settings.account.blurb': 'Connectez-vous pour débloquer plus de fonctionnalités.',
  'mg.settings.services': 'Services de musique',
  'mg.settings.services.blurb': 'Les services de streaming que vous avez configurés.',
  'mg.settings.library': 'Bibliothèque musicale',
  'mg.settings.library.blurb': 'Les dossiers de musique partagés sur votre réseau.',
  'mg.settings.time': 'Date et heure',
  'mg.settings.time.blurb': "Réglages de l'horloge et du fuseau horaire.",
  'mg.settings.systems': 'Systèmes et pièces',
  'mg.settings.systems.blurb': 'Les appareils que Sonora voit sur votre réseau.',
  'mg.settings.parental': 'Filtres de contenu',
  'mg.settings.parental.blurb': 'Filtrage du contenu explicite.',
  'mg.settings.s2': 'Conseiller de mise à niveau',
  'mg.settings.s2.blurb': 'Mettez à niveau votre système Sonos.',
  'mg.settings.network': 'Test du réseau',
  'mg.settings.network.blurb': 'Repérez les problèmes de performances possibles sur votre réseau.',
  'mg.settings.appearance': 'Apparence',
  'mg.settings.appearance.blurb': 'Le thème que porte Sonora et la langue qu’il parle.',
  'mg.settings.log': 'Journal',
  'mg.settings.log.blurb': 'Ce qui s’est mal passé récemment, du plus récent au plus ancien.',
  'mg.nav.listen': 'Écouter',
  'mg.nav.browse': 'Parcourir',
  'mg.showInBrowse': 'Afficher dans Parcourir',
  'mg.collapseRail': 'Réduire la navigation',
  'mg.expandRail': 'Développer la navigation',
  'mg.openPlayer': 'Ouvrir le lecteur',
  'mg.closePlayer': 'Fermer le lecteur',
  'mg.playModes': 'Modes de lecture',
  'mg.upNext': 'À suivre',
  'mg.upNextAndRooms': 'À suivre et pièces',
  'mg.inThisRoom': 'Dans cette pièce',
  'mg.soundAndRoom': 'Son et réglages',
  'mg.allRooms': 'Toutes les pièces',
  'mg.dragToReorder': 'Faites glisser pour réordonner',
  'mg.playsIn': 'Joue dans {room}',
  'mg.searchHint': 'Rechercher des pièces, des actions, des favoris ou un service',
  'mg.dynamicColor': 'Couleurs de la pochette',
  'mg.dynamicColorBody': 'Teinte toute l’interface aux couleurs de ce qui joue dans la pièce affichée.',
  'mg.reload': 'Recharger',
}

const deDE = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Räume',
  'mg.nav.clock': 'Wecker',
  'mg.nav.settings': 'Einstellungen',
  'mg.navigation': 'Bereiche',
  'mg.all': 'Alle',
  'mg.greeting.morning': 'Guten Morgen',
  'mg.greeting.afternoon': 'Guten Tag',
  'mg.greeting.evening': 'Guten Abend',
  'mg.greeting.overnight': 'Gute Nacht',
  'mg.playingIn': 'Wiedergabe: {rooms}',
  'mg.dragToGroup': 'Ziehe einen Raum auf einen anderen, um sie zu gruppieren.',
  'mg.groupAcrossSystems': 'Räume verschiedener Systeme lassen sich nicht gruppieren.',
  'mg.forRoom': 'für {room}',
  'mg.recent': 'Zuletzt gespielt',
  'mg.quietRooms.one': '{count} stiller Raum',
  'mg.quietRooms.other': '{count} stille Räume',
  'mg.open': 'Öffnen',
  'mg.playingNow': '{title} läuft',
  'mg.queuedNext': '{title} läuft als Nächstes',
  'mg.addedToQueue': '{title} wurde zur Warteschlange hinzugefügt',
  'mg.replacedQueue': 'Warteschlange durch {title} ersetzt',
  'mg.queueEmptyBody': 'Spiele etwas aus der Bibliothek ab oder füge Titel über „Ans Ende der Warteschlange“ hinzu.',
  'mg.queueSaved': 'Warteschlange als „{title}“ gespeichert',
  'mg.moveUp': 'Nach oben',
  'mg.moveDown': 'Nach unten',
  'mg.removeSelected': '{count} ausgewählte entfernen',
  'mg.selected': '{count} ausgewählt',
  'mg.editGroup': 'Gruppe bearbeiten',
  'mg.addRooms': 'Räume hinzufügen',
  'mg.leaveGroup': '{room} aus der Gruppe nehmen',
  'mg.thisRoom': 'Dieser Raum',
  'mg.groupedWith': 'Gruppiert mit {room}',
  'mg.noPairCandidates': 'Kein weiterer ungepaarter Lautsprecher dieses Modells.',
  'mg.lineIn': 'Line-In',
  'mg.connected': 'Verbunden',
  'mg.nothingConnected': 'Nichts verbunden',
  'mg.none': 'Keine',
  'mg.musicSources': 'Musikquellen',
  'mg.activeRoom': 'Läuft in',
  'mg.chooseRoom': 'Raum wählen',
  'mg.otherSystem': 'Auf dem {gen}-System; wähle einen seiner Räume, um daraus abzuspielen',
  'mg.allServices': 'Alle Dienste',
  'mg.allServicesGen': 'Alle {gen}-Dienste',
  'mg.playOtherSystem': 'Das liegt im {gen}-System. Wähle einen seiner Räume, um es abzuspielen.',
  'mg.view': 'Ansicht',
  'mg.viewAuto': 'Automatisch',
  'mg.viewGrid': 'Raster',
  'mg.viewList': 'Liste',
  'mg.filterServices': 'Dienste filtern',
  'mg.searchIn': '„{term}“ in {service} suchen',
  'mg.search.rooms': 'Räume',
  'mg.search.actions': 'Aktionen',
  'mg.search.music': 'Musik',
  'mg.search.services': 'Musikdienste',
  'mg.partyMode': 'Partymodus',
  'mg.serviceRemoved': '{service} entfernt',
  'mg.quality': 'Qualität',
  'mg.worst': 'schlechteste ms',
  'mg.wired': 'Kabelgebunden',
  'mg.noRooms': 'Keine Räume in diesem System.',
  'mg.services.none': 'Auf diesem System sind noch keine Musikdienste eingerichtet.',
  'mg.services.linked': 'In Sonora verknüpft',
  'mg.services.notLinked': 'In der Sonos-App eingerichtet, in Sonora noch nicht verknüpft',
  'mg.alsoRemembered': 'Ebenfalls bekannt, aber außer Reichweite: {names}.',
  'mg.noAnswer': 'keine Antwort',
  'mg.favoritesEmpty': 'Alles, was du in irgendeinem Controller als Sonos-Favorit speicherst, erscheint hier. Die Liste liegt bei den Lautsprechern, deshalb ist es überall dieselbe.',
  'mg.playlistsEmpty': 'Sonos-Playlists sind gespeicherte Warteschlangen. Auf diesem System gibt es noch keine.',
  'mg.settings.account': 'Sonos-Konto',
  'mg.settings.account.blurb': 'Melde dich an, um weitere Funktionen freizuschalten.',
  'mg.settings.services': 'Musikdienste',
  'mg.settings.services.blurb': 'Die Streamingdienste, die Sie eingerichtet haben.',
  'mg.settings.library': 'Musikbibliothek',
  'mg.settings.library.blurb': 'Freigegebene Musikordner in Ihrem Netzwerk.',
  'mg.settings.time': 'Datum und Uhrzeit',
  'mg.settings.time.blurb': 'Uhr- und Zeitzoneneinstellungen.',
  'mg.settings.systems': 'Systeme und Räume',
  'mg.settings.systems.blurb': 'Welche Geräte Sonora in Ihrem Netzwerk sieht.',
  'mg.settings.parental': 'Inhaltsfilter',
  'mg.settings.parental.blurb': 'Filter für explizite Inhalte.',
  'mg.settings.s2': 'Upgrade-Berater',
  'mg.settings.s2.blurb': 'Rüste dein Sonos-System auf.',
  'mg.settings.network': 'Netzwerkprüfung',
  'mg.settings.network.blurb': 'Mögliche Leistungsprobleme in Ihrem Netzwerk erkennen.',
  'mg.settings.appearance': 'Erscheinungsbild',
  'mg.settings.appearance.blurb': 'Das Design, das Sonora trägt, und die Sprache, die es spricht.',
  'mg.settings.log': 'Protokoll',
  'mg.settings.log.blurb': 'Was zuletzt schiefgelaufen ist, das Neueste zuerst.',
  'mg.nav.listen': 'Hören',
  'mg.nav.browse': 'Durchsuchen',
  'mg.showInBrowse': 'In Durchsuchen zeigen',
  'mg.collapseRail': 'Navigation einklappen',
  'mg.expandRail': 'Navigation ausklappen',
  'mg.openPlayer': 'Player öffnen',
  'mg.closePlayer': 'Player schließen',
  'mg.playModes': 'Wiedergabemodi',
  'mg.upNext': 'Als Nächstes',
  'mg.upNextAndRooms': 'Als Nächstes und Räume',
  'mg.inThisRoom': 'In diesem Raum',
  'mg.soundAndRoom': 'Klang und Einstellungen',
  'mg.allRooms': 'Alle Räume',
  'mg.dragToReorder': 'Zum Umsortieren ziehen',
  'mg.playsIn': 'Spielt in {room}',
  'mg.searchHint': 'Räume, Aktionen, Favoriten oder einen Dienst suchen',
  'mg.dynamicColor': 'Farben aus dem Cover',
  'mg.dynamicColorBody': 'Färbt die ganze Oberfläche in den Farben dessen, was im angezeigten Raum läuft.',
  'mg.reload': 'Neu laden',
}

const itIT = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Stanze',
  'mg.nav.clock': 'Sveglie',
  'mg.nav.settings': 'Impostazioni',
  'mg.navigation': 'Sezioni',
  'mg.all': 'Tutto',
  'mg.greeting.morning': 'Buongiorno',
  'mg.greeting.afternoon': 'Buon pomeriggio',
  'mg.greeting.evening': 'Buonasera',
  'mg.greeting.overnight': 'Buonanotte',
  'mg.playingIn': 'In riproduzione in {rooms}',
  'mg.dragToGroup': 'Trascina una stanza su un’altra per raggrupparle.',
  'mg.groupAcrossSystems': 'Stanze di sistemi diversi non possono essere raggruppate.',
  'mg.forRoom': 'per {room}',
  'mg.recent': 'Ascoltati di recente',
  'mg.quietRooms.one': '{count} stanza silenziosa',
  'mg.quietRooms.other': '{count} stanze silenziose',
  'mg.open': 'Apri',
  'mg.playingNow': 'In riproduzione {title}',
  'mg.queuedNext': '{title} sarà riprodotto dopo',
  'mg.addedToQueue': '{title} è stato aggiunto alla coda',
  'mg.replacedQueue': 'Coda sostituita con {title}',
  'mg.queueEmptyBody': 'Riproduci qualcosa dalla libreria, o aggiungi brani con «Aggiungi in fondo alla coda».',
  'mg.queueSaved': 'Coda salvata come «{title}»',
  'mg.moveUp': 'Sposta su',
  'mg.moveDown': 'Sposta giù',
  'mg.removeSelected': 'Rimuovi {count} selezionati',
  'mg.selected': '{count} selezionati',
  'mg.editGroup': 'Modifica il gruppo',
  'mg.addRooms': 'Aggiungi stanze',
  'mg.leaveGroup': 'Togli {room} dal gruppo',
  'mg.thisRoom': 'Questa stanza',
  'mg.groupedWith': 'Raggruppata con {room}',
  'mg.noPairCandidates': 'Nessun altro speaker non abbinato di questo modello.',
  'mg.lineIn': 'Ingresso linea',
  'mg.connected': 'Collegato',
  'mg.nothingConnected': 'Niente collegato',
  'mg.none': 'Nessuna',
  'mg.musicSources': 'Sorgenti musicali',
  'mg.activeRoom': 'In riproduzione in',
  'mg.chooseRoom': 'Scegli una stanza',
  'mg.otherSystem': 'Sul sistema {gen}; scegli una delle sue stanze per riprodurre da lì',
  'mg.allServices': 'Tutti i servizi',
  'mg.allServicesGen': 'Tutti i servizi {gen}',
  'mg.playOtherSystem': 'Si trova nel sistema {gen}. Scegli una delle sue stanze per riprodurlo.',
  'mg.view': 'Vista',
  'mg.viewAuto': 'Automatica',
  'mg.viewGrid': 'Griglia',
  'mg.viewList': 'Elenco',
  'mg.filterServices': 'Filtra i servizi',
  'mg.searchIn': 'Cerca «{term}» in {service}',
  'mg.search.rooms': 'Stanze',
  'mg.search.actions': 'Azioni',
  'mg.search.music': 'Musica',
  'mg.search.services': 'Servizi musicali',
  'mg.partyMode': 'Modalità festa',
  'mg.serviceRemoved': '{service} rimosso',
  'mg.quality': 'Qualità',
  'mg.worst': 'ms peggiore',
  'mg.wired': 'Cablato',
  'mg.noRooms': 'Nessuna stanza in questo sistema.',
  'mg.services.none': 'Su questo sistema non è ancora configurato alcun servizio musicale.',
  'mg.services.linked': 'Collegato in Sonora',
  'mg.services.notLinked': 'Configurato nell’app Sonos, non ancora collegato in Sonora',
  'mg.alsoRemembered': 'Ricordati ma fuori portata: {names}.',
  'mg.noAnswer': 'nessuna risposta',
  'mg.favoritesEmpty': 'Tutto ciò che salvi come preferito Sonos, da qualsiasi controller, compare qui. L’elenco è custodito dagli speaker, quindi è lo stesso ovunque.',
  'mg.playlistsEmpty': 'Le playlist Sonos sono code che hai salvato. Su questo sistema non ce ne sono ancora.',
  'mg.settings.account': 'Account Sonos',
  'mg.settings.account.blurb': 'Accedi per sbloccare altre funzioni.',
  'mg.settings.services': 'Servizi musicali',
  'mg.settings.services.blurb': 'I servizi di streaming che hai configurato.',
  'mg.settings.library': 'Libreria musicale',
  'mg.settings.library.blurb': 'Cartelle musicali condivise sulla tua rete.',
  'mg.settings.time': 'Data e ora',
  'mg.settings.time.blurb': 'Impostazioni di orologio e fuso orario.',
  'mg.settings.systems': 'Sistemi e stanze',
  'mg.settings.systems.blurb': 'Quali dispositivi vede Sonora sulla tua rete.',
  'mg.settings.parental': 'Filtri dei contenuti',
  'mg.settings.parental.blurb': 'Filtro dei contenuti espliciti.',
  'mg.settings.s2': 'Consulente per l’aggiornamento',
  'mg.settings.s2.blurb': 'Aggiorna il tuo sistema Sonos.',
  'mg.settings.network': 'Verifica della rete',
  'mg.settings.network.blurb': 'Individua possibili problemi di prestazioni sulla tua rete.',
  'mg.settings.appearance': 'Aspetto',
  'mg.settings.appearance.blurb': 'Il tema che indossa Sonora e la lingua che parla.',
  'mg.settings.log': 'Registro',
  'mg.settings.log.blurb': 'Cosa è andato storto di recente, dal più nuovo.',
  'mg.nav.listen': 'Ascolta',
  'mg.nav.browse': 'Sfoglia',
  'mg.showInBrowse': 'Mostra in Sfoglia',
  'mg.collapseRail': 'Comprimi la navigazione',
  'mg.expandRail': 'Espandi la navigazione',
  'mg.openPlayer': 'Apri il lettore',
  'mg.closePlayer': 'Chiudi il lettore',
  'mg.playModes': 'Modalità di riproduzione',
  'mg.upNext': 'In coda',
  'mg.upNextAndRooms': 'In coda e stanze',
  'mg.inThisRoom': 'In questa stanza',
  'mg.soundAndRoom': 'Suono e impostazioni',
  'mg.allRooms': 'Tutte le stanze',
  'mg.dragToReorder': 'Trascina per riordinare',
  'mg.playsIn': 'Suona in {room}',
  'mg.searchHint': 'Cerca stanze, azioni, preferiti o un servizio',
  'mg.dynamicColor': 'Colori dalla copertina',
  'mg.dynamicColorBody': 'Colora tutta l’interfaccia con i colori di ciò che suona nella stanza in vista.',
  'mg.reload': 'Ricarica',
}

const ptBR = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Cômodos',
  'mg.nav.clock': 'Alarmes',
  'mg.nav.settings': 'Configurações',
  'mg.navigation': 'Seções',
  'mg.all': 'Tudo',
  'mg.greeting.morning': 'Bom dia',
  'mg.greeting.afternoon': 'Boa tarde',
  'mg.greeting.evening': 'Boa noite',
  'mg.greeting.overnight': 'Boa madrugada',
  'mg.playingIn': 'Tocando em {rooms}',
  'mg.dragToGroup': 'Arraste um cômodo sobre outro para agrupá-los.',
  'mg.groupAcrossSystems': 'Cômodos de sistemas diferentes não podem ser agrupados.',
  'mg.forRoom': 'para {room}',
  'mg.recent': 'Tocados recentemente',
  'mg.quietRooms.one': '{count} cômodo em silêncio',
  'mg.quietRooms.other': '{count} cômodos em silêncio',
  'mg.open': 'Abrir',
  'mg.playingNow': 'Tocando {title}',
  'mg.queuedNext': '{title} toca em seguida',
  'mg.addedToQueue': '{title} foi adicionado à fila',
  'mg.replacedQueue': 'Fila substituída por {title}',
  'mg.queueEmptyBody': 'Toque algo da biblioteca, ou adicione faixas com “Adicionar ao fim da fila”.',
  'mg.queueSaved': 'Fila salva como “{title}”',
  'mg.moveUp': 'Mover para cima',
  'mg.moveDown': 'Mover para baixo',
  'mg.removeSelected': 'Remover {count} selecionados',
  'mg.selected': '{count} selecionados',
  'mg.editGroup': 'Editar o grupo',
  'mg.addRooms': 'Adicionar cômodos',
  'mg.leaveGroup': 'Tirar {room} do grupo',
  'mg.thisRoom': 'Este cômodo',
  'mg.groupedWith': 'Agrupado com {room}',
  'mg.noPairCandidates': 'Nenhuma outra caixa de som sem par deste modelo.',
  'mg.lineIn': 'Entrada de linha',
  'mg.connected': 'Conectado',
  'mg.nothingConnected': 'Nada conectado',
  'mg.none': 'Nenhum',
  'mg.musicSources': 'Fontes de música',
  'mg.activeRoom': 'Tocando em',
  'mg.chooseRoom': 'Escolher um cômodo',
  'mg.otherSystem': 'No sistema {gen}; escolha um dos cômodos dele para tocar a partir daí',
  'mg.allServices': 'Todos os serviços',
  'mg.allServicesGen': 'Todos os serviços do {gen}',
  'mg.playOtherSystem': 'Isso está no sistema {gen}. Escolha um dos ambientes dele para tocar.',
  'mg.view': 'Visualização',
  'mg.viewAuto': 'Automática',
  'mg.viewGrid': 'Grade',
  'mg.viewList': 'Lista',
  'mg.filterServices': 'Filtrar serviços',
  'mg.searchIn': 'Buscar “{term}” em {service}',
  'mg.search.rooms': 'Cômodos',
  'mg.search.actions': 'Ações',
  'mg.search.music': 'Música',
  'mg.search.services': 'Serviços de música',
  'mg.partyMode': 'Modo festa',
  'mg.serviceRemoved': '{service} removido',
  'mg.quality': 'Qualidade',
  'mg.worst': 'pior ms',
  'mg.wired': 'Com fio',
  'mg.noRooms': 'Nenhum cômodo neste sistema.',
  'mg.services.none': 'Ainda não há serviços de música configurados neste sistema.',
  'mg.services.linked': 'Vinculado no Sonora',
  'mg.services.notLinked': 'Configurado no aplicativo Sonos, ainda não vinculado no Sonora',
  'mg.alsoRemembered': 'Também lembrados, mas fora de alcance: {names}.',
  'mg.noAnswer': 'sem resposta',
  'mg.favoritesEmpty': 'Tudo o que você salva como favorito Sonos, em qualquer controlador, aparece aqui. A lista fica nas caixas de som, então é a mesma em todo lugar.',
  'mg.playlistsEmpty': 'Playlists Sonos são filas que você salvou. Ainda não há nenhuma neste sistema.',
  'mg.settings.account': 'Conta Sonos',
  'mg.settings.account.blurb': 'Entre para desbloquear mais recursos.',
  'mg.settings.services': 'Serviços de música',
  'mg.settings.services.blurb': 'Os serviços de streaming que você configurou.',
  'mg.settings.library': 'Biblioteca musical',
  'mg.settings.library.blurb': 'Pastas de música compartilhadas na sua rede.',
  'mg.settings.time': 'Data e hora',
  'mg.settings.time.blurb': 'Configurações de relógio e fuso horário.',
  'mg.settings.systems': 'Sistemas e cômodos',
  'mg.settings.systems.blurb': 'Quais dispositivos o Sonora vê na sua rede.',
  'mg.settings.parental': 'Filtros de conteúdo',
  'mg.settings.parental.blurb': 'Filtragem de conteúdo explícito.',
  'mg.settings.s2': 'Consultor de atualização',
  'mg.settings.s2.blurb': 'Atualize seu sistema Sonos.',
  'mg.settings.network': 'Verificação da rede',
  'mg.settings.network.blurb': 'Identifique possíveis problemas de desempenho na sua rede.',
  'mg.settings.appearance': 'Aparência',
  'mg.settings.appearance.blurb': 'O tema que o Sonora veste e o idioma que ele fala.',
  'mg.settings.log': 'Registro',
  'mg.settings.log.blurb': 'O que deu errado recentemente, do mais novo ao mais antigo.',
  'mg.nav.listen': 'Ouvir',
  'mg.nav.browse': 'Explorar',
  'mg.showInBrowse': 'Mostrar em Explorar',
  'mg.collapseRail': 'Recolher a navegação',
  'mg.expandRail': 'Expandir a navegação',
  'mg.openPlayer': 'Abrir o player',
  'mg.closePlayer': 'Fechar o player',
  'mg.playModes': 'Modos de reprodução',
  'mg.upNext': 'A seguir',
  'mg.upNextAndRooms': 'A seguir e cômodos',
  'mg.inThisRoom': 'Neste cômodo',
  'mg.soundAndRoom': 'Som e configurações',
  'mg.allRooms': 'Todos os cômodos',
  'mg.dragToReorder': 'Arraste para reordenar',
  'mg.playsIn': 'Toca em {room}',
  'mg.searchHint': 'Busque cômodos, ações, favoritos ou um serviço',
  'mg.dynamicColor': 'Cores da capa',
  'mg.dynamicColorBody': 'Tinge toda a interface com as cores do que está tocando no cômodo em exibição.',
  'mg.reload': 'Recarregar',
}

const nlNL = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Ruimtes',
  'mg.nav.clock': 'Wekkers',
  'mg.nav.settings': 'Instellingen',
  'mg.navigation': 'Secties',
  'mg.all': 'Alles',
  'mg.greeting.morning': 'Goedemorgen',
  'mg.greeting.afternoon': 'Goedemiddag',
  'mg.greeting.evening': 'Goedenavond',
  'mg.greeting.overnight': 'Goedenacht',
  'mg.playingIn': 'Speelt in {rooms}',
  'mg.dragToGroup': 'Sleep een ruimte op een andere om ze te groeperen.',
  'mg.groupAcrossSystems': 'Ruimtes van verschillende systemen kunnen niet worden gegroepeerd.',
  'mg.forRoom': 'voor {room}',
  'mg.recent': 'Onlangs afgespeeld',
  'mg.quietRooms.one': '{count} stille ruimte',
  'mg.quietRooms.other': '{count} stille ruimtes',
  'mg.open': 'Openen',
  'mg.playingNow': '{title} speelt',
  'mg.queuedNext': '{title} speelt hierna',
  'mg.addedToQueue': '{title} is aan de wachtrij toegevoegd',
  'mg.replacedQueue': 'Wachtrij vervangen door {title}',
  'mg.queueEmptyBody': 'Speel iets uit de bibliotheek, of voeg nummers toe met ‘Achteraan de wachtrij zetten’.',
  'mg.queueSaved': 'Wachtrij opgeslagen als ‘{title}’',
  'mg.moveUp': 'Omhoog',
  'mg.moveDown': 'Omlaag',
  'mg.removeSelected': '{count} geselecteerde verwijderen',
  'mg.selected': '{count} geselecteerd',
  'mg.editGroup': 'Groep bewerken',
  'mg.addRooms': 'Ruimtes toevoegen',
  'mg.leaveGroup': '{room} uit de groep halen',
  'mg.thisRoom': 'Deze ruimte',
  'mg.groupedWith': 'Gegroepeerd met {room}',
  'mg.noPairCandidates': 'Geen andere ongekoppelde speaker van dit model.',
  'mg.lineIn': 'Lijningang',
  'mg.connected': 'Verbonden',
  'mg.nothingConnected': 'Niets verbonden',
  'mg.none': 'Geen',
  'mg.musicSources': 'Muziekbronnen',
  'mg.activeRoom': 'Speelt in',
  'mg.chooseRoom': 'Kies een ruimte',
  'mg.otherSystem': 'Op het {gen}-systeem; kies een van de ruimtes daarvan om er vanaf te spelen',
  'mg.allServices': 'Alle diensten',
  'mg.allServicesGen': 'Alle {gen}-diensten',
  'mg.playOtherSystem': 'Dat staat op het {gen}-systeem. Kies een van zijn ruimtes om het af te spelen.',
  'mg.view': 'Weergave',
  'mg.viewAuto': 'Automatisch',
  'mg.viewGrid': 'Raster',
  'mg.viewList': 'Lijst',
  'mg.filterServices': 'Diensten filteren',
  'mg.searchIn': '‘{term}’ zoeken in {service}',
  'mg.search.rooms': 'Ruimtes',
  'mg.search.actions': 'Acties',
  'mg.search.music': 'Muziek',
  'mg.search.services': 'Muziekdiensten',
  'mg.partyMode': 'Partymodus',
  'mg.serviceRemoved': '{service} verwijderd',
  'mg.quality': 'Kwaliteit',
  'mg.worst': 'slechtste ms',
  'mg.wired': 'Bedraad',
  'mg.noRooms': 'Geen ruimtes in dit systeem.',
  'mg.services.none': 'Op dit systeem zijn nog geen muziekdiensten ingesteld.',
  'mg.services.linked': 'Gekoppeld in Sonora',
  'mg.services.notLinked': 'Ingesteld in de Sonos-app, nog niet gekoppeld in Sonora',
  'mg.alsoRemembered': 'Ook bekend maar buiten bereik: {names}.',
  'mg.noAnswer': 'geen antwoord',
  'mg.favoritesEmpty': 'Alles wat je als Sonos-favoriet bewaart, in welke controller dan ook, verschijnt hier. De speakers houden de lijst bij, dus overal is het dezelfde lijst.',
  'mg.playlistsEmpty': 'Sonos-afspeellijsten zijn wachtrijen die je hebt bewaard. Op dit systeem staan er nog geen.',
  'mg.settings.account': 'Sonos-account',
  'mg.settings.account.blurb': 'Log in om meer functies te ontgrendelen.',
  'mg.settings.services': 'Muziekdiensten',
  'mg.settings.services.blurb': 'De streamingdiensten die je hebt ingesteld.',
  'mg.settings.library': 'Muziekbibliotheek',
  'mg.settings.library.blurb': 'Gedeelde muziekmappen op je netwerk.',
  'mg.settings.time': 'Datum en tijd',
  'mg.settings.time.blurb': 'Instellingen voor klok en tijdzone.',
  'mg.settings.systems': 'Systemen en ruimtes',
  'mg.settings.systems.blurb': 'Welke apparaten Sonora op je netwerk ziet.',
  'mg.settings.parental': 'Inhoudsfilters',
  'mg.settings.parental.blurb': 'Filteren van expliciete inhoud.',
  'mg.settings.s2': 'Upgradeadviseur',
  'mg.settings.s2.blurb': 'Upgrade je Sonos-systeem.',
  'mg.settings.network': 'Netwerkcontrole',
  'mg.settings.network.blurb': 'Spoor mogelijke prestatieproblemen op je netwerk op.',
  'mg.settings.appearance': 'Weergave',
  'mg.settings.appearance.blurb': 'Het thema dat Sonora draagt en de taal die het spreekt.',
  'mg.settings.log': 'Logboek',
  'mg.settings.log.blurb': 'Wat er onlangs misging, nieuwste eerst.',
  'mg.nav.listen': 'Luisteren',
  'mg.nav.browse': 'Bladeren',
  'mg.showInBrowse': 'Tonen in Bladeren',
  'mg.collapseRail': 'Navigatie inklappen',
  'mg.expandRail': 'Navigatie uitklappen',
  'mg.openPlayer': 'Speler openen',
  'mg.closePlayer': 'Speler sluiten',
  'mg.playModes': 'Afspeelmodi',
  'mg.upNext': 'Hierna',
  'mg.upNextAndRooms': 'Hierna en ruimtes',
  'mg.inThisRoom': 'In deze ruimte',
  'mg.soundAndRoom': 'Geluid en instellingen',
  'mg.allRooms': 'Alle ruimtes',
  'mg.dragToReorder': 'Sleep om de volgorde te wijzigen',
  'mg.playsIn': 'Speelt in {room}',
  'mg.searchHint': 'Zoek ruimtes, acties, favorieten of een dienst',
  'mg.dynamicColor': 'Kleuren van de hoes',
  'mg.dynamicColorBody': 'Kleurt de hele interface met de kleuren van wat er speelt in de getoonde ruimte.',
  'mg.reload': 'Opnieuw laden',
}

const ukUA = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Кімнати',
  'mg.nav.clock': 'Будильники',
  'mg.nav.settings': 'Налаштування',
  'mg.navigation': 'Розділи',
  'mg.all': 'Усе',
  'mg.greeting.morning': 'Доброго ранку',
  'mg.greeting.afternoon': 'Доброго дня',
  'mg.greeting.evening': 'Доброго вечора',
  'mg.greeting.overnight': 'Доброї ночі',
  'mg.playingIn': 'Грає: {rooms}',
  'mg.dragToGroup': 'Перетягни одну кімнату на іншу, щоб згрупувати їх.',
  'mg.groupAcrossSystems': 'Кімнати з різних систем не можна згрупувати разом.',
  'mg.forRoom': 'для {room}',
  'mg.recent': 'Нещодавно грало',
  'mg.quietRooms.one': '{count} тиха кімната',
  'mg.quietRooms.other': '{count} тихих кімнат',
  'mg.open': 'Відкрити',
  'mg.playingNow': 'Грає {title}',
  'mg.queuedNext': '{title} гратиме наступним',
  'mg.addedToQueue': '{title} додано до черги',
  'mg.replacedQueue': 'Чергу замінено на {title}',
  'mg.queueEmptyBody': 'Постав щось із бібліотеки або додай треки через «Додати в кінець черги».',
  'mg.queueSaved': 'Чергу збережено як «{title}»',
  'mg.moveUp': 'Вище',
  'mg.moveDown': 'Нижче',
  'mg.removeSelected': 'Вилучити вибрані ({count})',
  'mg.selected': 'Вибрано: {count}',
  'mg.editGroup': 'Змінити групу',
  'mg.addRooms': 'Додати кімнати',
  'mg.leaveGroup': 'Вивести {room} з групи',
  'mg.thisRoom': 'Ця кімната',
  'mg.groupedWith': 'Згруповано з {room}',
  'mg.noPairCandidates': 'Немає іншої непарної колонки цієї моделі.',
  'mg.lineIn': 'Лінійний вхід',
  'mg.connected': 'Під’єднано',
  'mg.nothingConnected': 'Нічого не під’єднано',
  'mg.none': 'Немає',
  'mg.musicSources': 'Джерела музики',
  'mg.activeRoom': 'Грає в',
  'mg.chooseRoom': 'Вибери кімнату',
  'mg.otherSystem': 'У системі {gen}; вибери одну з її кімнат, щоб грати звідти',
  'mg.allServices': 'Усі сервіси',
  'mg.allServicesGen': 'Усі сервіси {gen}',
  'mg.playOtherSystem': 'Це в системі {gen}. Обери одну з її кімнат, щоб відтворити.',
  'mg.view': 'Вигляд',
  'mg.viewAuto': 'Автоматично',
  'mg.viewGrid': 'Сітка',
  'mg.viewList': 'Список',
  'mg.filterServices': 'Фільтрувати сервіси',
  'mg.searchIn': 'Шукати «{term}» у {service}',
  'mg.search.rooms': 'Кімнати',
  'mg.search.actions': 'Дії',
  'mg.search.music': 'Музика',
  'mg.search.services': 'Музичні сервіси',
  'mg.partyMode': 'Режим вечірки',
  'mg.serviceRemoved': '{service} вилучено',
  'mg.quality': 'Якість',
  'mg.worst': 'найгірші мс',
  'mg.wired': 'Дротове',
  'mg.noRooms': 'У цій системі немає кімнат.',
  'mg.services.none': 'У цій системі ще не налаштовано жодного музичного сервісу.',
  'mg.services.linked': 'Приєднано в Sonora',
  'mg.services.notLinked': 'Налаштовано в застосунку Sonos, ще не приєднано в Sonora',
  'mg.alsoRemembered': 'Також у пам’яті, але поза досяжністю: {names}.',
  'mg.noAnswer': 'немає відповіді',
  'mg.favoritesEmpty': 'Усе, що ти зберігаєш як обране Sonos у будь-якому контролері, з’являється тут. Список тримають колонки, тож він скрізь однаковий.',
  'mg.playlistsEmpty': 'Плейлисти Sonos — це збережені черги. У цій системі їх поки немає.',
  'mg.settings.account': 'Обліковий запис Sonos',
  'mg.settings.account.blurb': 'Увійди, щоб відкрити більше можливостей.',
  'mg.settings.services': 'Музичні сервіси',
  'mg.settings.services.blurb': 'Стрімінгові сервіси, які ви налаштували.',
  'mg.settings.library': 'Музична бібліотека',
  'mg.settings.library.blurb': 'Спільні папки з музикою у вашій мережі.',
  'mg.settings.time': 'Дата й час',
  'mg.settings.time.blurb': 'Налаштування годинника й часового поясу.',
  'mg.settings.systems': 'Системи та кімнати',
  'mg.settings.systems.blurb': 'Які пристрої Sonora бачить у вашій мережі.',
  'mg.settings.parental': 'Фільтри вмісту',
  'mg.settings.parental.blurb': 'Фільтрування відвертого вмісту.',
  'mg.settings.s2': 'Порадник з оновлення',
  'mg.settings.s2.blurb': 'Онови свою систему Sonos.',
  'mg.settings.network': 'Перевірка мережі',
  'mg.settings.network.blurb': 'Виявлення можливих проблем із продуктивністю у вашій мережі.',
  'mg.settings.appearance': 'Вигляд',
  'mg.settings.appearance.blurb': 'Тема, яку носить Sonora, і мова, якою вона говорить.',
  'mg.settings.log': 'Журнал',
  'mg.settings.log.blurb': 'Що нещодавно пішло не так, від найновішого.',
  'mg.nav.listen': 'Слухати',
  'mg.nav.browse': 'Огляд',
  'mg.showInBrowse': 'Показати в Огляді',
  'mg.collapseRail': 'Згорнути навігацію',
  'mg.expandRail': 'Розгорнути навігацію',
  'mg.openPlayer': 'Відкрити програвач',
  'mg.closePlayer': 'Закрити програвач',
  'mg.playModes': 'Режими відтворення',
  'mg.upNext': 'Далі',
  'mg.upNextAndRooms': 'Далі та кімнати',
  'mg.inThisRoom': 'У цій кімнаті',
  'mg.soundAndRoom': 'Звук і налаштування',
  'mg.allRooms': 'Усі кімнати',
  'mg.dragToReorder': 'Перетягніть, щоб змінити порядок',
  'mg.playsIn': 'Грає в {room}',
  'mg.searchHint': 'Шукайте кімнати, дії, обране або сервіс',
  'mg.dynamicColor': 'Кольори з обкладинки',
  'mg.dynamicColorBody': 'Забарвлює весь інтерфейс кольорами того, що грає у вибраній кімнаті.',
  'mg.reload': 'Оновити',
}

const jaJP = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': '部屋',
  'mg.nav.clock': 'アラーム',
  'mg.nav.settings': '設定',
  'mg.navigation': 'セクション',
  'mg.all': 'すべて',
  'mg.greeting.morning': 'おはようございます',
  'mg.greeting.afternoon': 'こんにちは',
  'mg.greeting.evening': 'こんばんは',
  'mg.greeting.overnight': 'おやすみなさい',
  'mg.playingIn': '{rooms} で再生中',
  'mg.dragToGroup': '部屋を別の部屋にドラッグするとグループになります。',
  'mg.groupAcrossSystems': '異なるシステムの部屋どうしはグループにできません。',
  'mg.forRoom': '{room} 用',
  'mg.recent': '最近再生した項目',
  'mg.quietRooms.one': '静かな部屋 {count}',
  'mg.quietRooms.other': '静かな部屋 {count}',
  'mg.open': '開く',
  'mg.playingNow': '{title} を再生中',
  'mg.queuedNext': '{title} を次に再生します',
  'mg.addedToQueue': '{title} をキューに追加しました',
  'mg.replacedQueue': 'キューを {title} で置き換えました',
  'mg.queueEmptyBody': 'ライブラリから何か再生するか、「キューの最後に追加」で曲を足してください。',
  'mg.queueSaved': 'キューを「{title}」として保存しました',
  'mg.moveUp': '上へ',
  'mg.moveDown': '下へ',
  'mg.removeSelected': '選択した {count} 件を削除',
  'mg.selected': '{count} 件選択',
  'mg.editGroup': 'グループを編集',
  'mg.addRooms': '部屋を追加',
  'mg.leaveGroup': '{room} をグループから外す',
  'mg.thisRoom': 'この部屋',
  'mg.groupedWith': '{room} とグループ化',
  'mg.noPairCandidates': 'このモデルで未ペアのスピーカーが他にありません。',
  'mg.lineIn': 'ライン入力',
  'mg.connected': '接続済み',
  'mg.nothingConnected': '何も接続されていません',
  'mg.none': 'なし',
  'mg.musicSources': '音楽ソース',
  'mg.activeRoom': '再生先',
  'mg.chooseRoom': '部屋を選択',
  'mg.otherSystem': '{gen} システム上です。そこから再生するには、その部屋のいずれかを選んでください',
  'mg.allServices': 'すべてのサービス',
  'mg.allServicesGen': 'すべての{gen}サービス',
  'mg.playOtherSystem': 'これは {gen} システムにあります。再生するには、そのシステムのルームを選んでください。',
  'mg.view': '表示',
  'mg.viewAuto': '自動',
  'mg.viewGrid': 'グリッド',
  'mg.viewList': 'リスト',
  'mg.filterServices': 'サービスを絞り込む',
  'mg.searchIn': '{service} で「{term}」を検索',
  'mg.search.rooms': '部屋',
  'mg.search.actions': '操作',
  'mg.search.music': '音楽',
  'mg.search.services': '音楽サービス',
  'mg.partyMode': 'パーティーモード',
  'mg.serviceRemoved': '{service} を削除しました',
  'mg.quality': '品質',
  'mg.worst': '最遅 ms',
  'mg.wired': '有線',
  'mg.noRooms': 'このシステムに部屋がありません。',
  'mg.services.none': 'このシステムにはまだ音楽サービスが設定されていません。',
  'mg.services.linked': 'Sonora に連携済み',
  'mg.services.notLinked': 'Sonos アプリで設定済み、Sonora には未連携',
  'mg.alsoRemembered': '覚えてはいますが届きません：{names}。',
  'mg.noAnswer': '応答なし',
  'mg.favoritesEmpty': 'どのコントローラーからでも、Sonos のお気に入りに保存したものはここに表示されます。一覧はスピーカーが保持しているので、どこで見ても同じです。',
  'mg.playlistsEmpty': 'Sonos プレイリストは保存したキューです。このシステムにはまだありません。',
  'mg.settings.account': 'Sonos アカウント',
  'mg.settings.account.blurb': 'サインインすると、さらに多くの機能が使えます。',
  'mg.settings.services': '音楽サービス',
  'mg.settings.services.blurb': '設定済みのストリーミングサービス。',
  'mg.settings.library': '音楽ライブラリ',
  'mg.settings.library.blurb': 'ネットワーク上の共有音楽フォルダー。',
  'mg.settings.time': '日付と時刻',
  'mg.settings.time.blurb': '時計とタイムゾーンの設定。',
  'mg.settings.systems': 'システムと部屋',
  'mg.settings.systems.blurb': 'Sonora がネットワーク上で認識しているデバイス。',
  'mg.settings.parental': 'コンテンツフィルター',
  'mg.settings.parental.blurb': '露骨なコンテンツのフィルタリング。',
  'mg.settings.s2': 'アップグレードアドバイザー',
  'mg.settings.s2.blurb': 'Sonosシステムをアップグレードします。',
  'mg.settings.network': 'ネットワーク確認',
  'mg.settings.network.blurb': 'ネットワークで起こりうるパフォーマンスの問題を見つけます。',
  'mg.settings.appearance': '外観',
  'mg.settings.appearance.blurb': 'Sonora がまとうテーマと、話す言語。',
  'mg.settings.log': 'ログ',
  'mg.settings.log.blurb': '最近うまくいかなかったこと、新しい順。',
  'mg.nav.listen': '聴く',
  'mg.nav.browse': 'ブラウズ',
  'mg.showInBrowse': 'ブラウズで表示',
  'mg.collapseRail': 'ナビゲーションを折りたたむ',
  'mg.expandRail': 'ナビゲーションを広げる',
  'mg.openPlayer': 'プレーヤーを開く',
  'mg.closePlayer': 'プレーヤーを閉じる',
  'mg.playModes': '再生モード',
  'mg.upNext': '次に再生',
  'mg.upNextAndRooms': '次に再生と部屋',
  'mg.inThisRoom': 'この部屋で',
  'mg.soundAndRoom': 'サウンドと設定',
  'mg.allRooms': 'すべての部屋',
  'mg.dragToReorder': 'ドラッグで並べ替え',
  'mg.playsIn': '{room} で再生',
  'mg.searchHint': '部屋、操作、お気に入り、サービスを検索',
  'mg.dynamicColor': 'ジャケットの色',
  'mg.dynamicColorBody': '表示中の部屋で再生している曲の色で、画面全体を彩ります。',
  'mg.reload': '再読み込み',
}

const koKR = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': '방',
  'mg.nav.clock': '알람',
  'mg.nav.settings': '설정',
  'mg.navigation': '섹션',
  'mg.all': '전체',
  'mg.greeting.morning': '좋은 아침이에요',
  'mg.greeting.afternoon': '좋은 오후예요',
  'mg.greeting.evening': '좋은 저녁이에요',
  'mg.greeting.overnight': '안녕히 주무세요',
  'mg.playingIn': '{rooms}에서 재생 중',
  'mg.dragToGroup': '방을 다른 방 위로 끌어다 놓으면 그룹이 됩니다.',
  'mg.groupAcrossSystems': '서로 다른 시스템의 방은 함께 묶을 수 없습니다.',
  'mg.forRoom': '{room}용',
  'mg.recent': '최근 재생',
  'mg.quietRooms.one': '조용한 방 {count}곳',
  'mg.quietRooms.other': '조용한 방 {count}곳',
  'mg.open': '열기',
  'mg.playingNow': '{title} 재생 중',
  'mg.queuedNext': '{title}을(를) 다음에 재생합니다',
  'mg.addedToQueue': '{title}을(를) 대기열에 추가했습니다',
  'mg.replacedQueue': '대기열을 {title}(으)로 바꿨습니다',
  'mg.queueEmptyBody': '라이브러리에서 무언가를 재생하거나 \'대기열 끝에 추가\'로 곡을 더하세요.',
  'mg.queueSaved': '대기열을 \'{title}\'(으)로 저장했습니다',
  'mg.moveUp': '위로',
  'mg.moveDown': '아래로',
  'mg.removeSelected': '선택한 {count}개 제거',
  'mg.selected': '{count}개 선택됨',
  'mg.editGroup': '그룹 편집',
  'mg.addRooms': '방 추가',
  'mg.leaveGroup': '{room}을(를) 그룹에서 빼기',
  'mg.thisRoom': '이 방',
  'mg.groupedWith': '{room}과(와) 그룹',
  'mg.noPairCandidates': '같은 모델의 짝 없는 스피커가 더 없습니다.',
  'mg.lineIn': '라인 입력',
  'mg.connected': '연결됨',
  'mg.nothingConnected': '연결된 것 없음',
  'mg.none': '없음',
  'mg.musicSources': '음악 소스',
  'mg.activeRoom': '재생 위치',
  'mg.chooseRoom': '방 선택',
  'mg.otherSystem': '{gen} 시스템에 있습니다. 거기서 재생하려면 그 방 중 하나를 선택하세요',
  'mg.allServices': '모든 서비스',
  'mg.allServicesGen': '모든 {gen} 서비스',
  'mg.playOtherSystem': '{gen} 시스템에 있습니다. 재생하려면 그 시스템의 룸을 선택하세요.',
  'mg.view': '보기',
  'mg.viewAuto': '자동',
  'mg.viewGrid': '그리드',
  'mg.viewList': '목록',
  'mg.filterServices': '서비스 필터',
  'mg.searchIn': '{service}에서 \'{term}\' 검색',
  'mg.search.rooms': '방',
  'mg.search.actions': '동작',
  'mg.search.music': '음악',
  'mg.search.services': '음악 서비스',
  'mg.partyMode': '파티 모드',
  'mg.serviceRemoved': '{service}을(를) 제거했습니다',
  'mg.quality': '품질',
  'mg.worst': '최저 ms',
  'mg.wired': '유선',
  'mg.noRooms': '이 시스템에 방이 없습니다.',
  'mg.services.none': '이 시스템에는 아직 설정된 음악 서비스가 없습니다.',
  'mg.services.linked': 'Sonora에 연결됨',
  'mg.services.notLinked': 'Sonos 앱에서 설정됨, Sonora에는 아직 연결되지 않음',
  'mg.alsoRemembered': '기억하고 있지만 닿지 않음: {names}.',
  'mg.noAnswer': '응답 없음',
  'mg.favoritesEmpty': '어떤 컨트롤러에서든 Sonos 즐겨찾기로 저장한 것은 여기에 나타납니다. 목록은 스피커가 갖고 있어서 어디서 보든 같습니다.',
  'mg.playlistsEmpty': 'Sonos 재생목록은 저장해 둔 대기열입니다. 이 시스템에는 아직 없습니다.',
  'mg.settings.account': 'Sonos 계정',
  'mg.settings.account.blurb': '로그인하면 더 많은 기능을 사용할 수 있습니다.',
  'mg.settings.services': '음악 서비스',
  'mg.settings.services.blurb': '설정한 스트리밍 서비스.',
  'mg.settings.library': '음악 라이브러리',
  'mg.settings.library.blurb': '네트워크의 공유 음악 폴더.',
  'mg.settings.time': '날짜와 시간',
  'mg.settings.time.blurb': '시계 및 시간대 설정.',
  'mg.settings.systems': '시스템과 방',
  'mg.settings.systems.blurb': 'Sonora가 네트워크에서 보고 있는 기기.',
  'mg.settings.parental': '콘텐츠 필터',
  'mg.settings.parental.blurb': '선정적인 콘텐츠 필터링.',
  'mg.settings.s2': '업그레이드 도우미',
  'mg.settings.s2.blurb': 'Sonos 시스템을 업그레이드하세요.',
  'mg.settings.network': '네트워크 점검',
  'mg.settings.network.blurb': '네트워크의 잠재적인 성능 문제를 찾아냅니다.',
  'mg.settings.appearance': '모양',
  'mg.settings.appearance.blurb': 'Sonora가 입은 테마와 사용하는 언어.',
  'mg.settings.log': '로그',
  'mg.settings.log.blurb': '최근에 잘못된 일들, 최신순.',
  'mg.nav.listen': '듣기',
  'mg.nav.browse': '둘러보기',
  'mg.showInBrowse': '둘러보기에서 보기',
  'mg.collapseRail': '탐색 접기',
  'mg.expandRail': '탐색 펼치기',
  'mg.openPlayer': '플레이어 열기',
  'mg.closePlayer': '플레이어 닫기',
  'mg.playModes': '재생 모드',
  'mg.upNext': '다음 곡',
  'mg.upNextAndRooms': '다음 곡과 방',
  'mg.inThisRoom': '이 방에서',
  'mg.soundAndRoom': '사운드 및 설정',
  'mg.allRooms': '모든 방',
  'mg.dragToReorder': '끌어서 순서 바꾸기',
  'mg.playsIn': '{room}에서 재생',
  'mg.searchHint': '방, 작업, 즐겨찾기 또는 서비스 검색',
  'mg.dynamicColor': '커버 색상',
  'mg.dynamicColorBody': '보고 있는 방에서 재생 중인 음악의 색으로 화면 전체를 물들입니다.',
  'mg.reload': '새로고침',
}

const zhCN = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': '房间',
  'mg.nav.clock': '闹钟',
  'mg.nav.settings': '设置',
  'mg.navigation': '板块',
  'mg.all': '全部',
  'mg.greeting.morning': '早上好',
  'mg.greeting.afternoon': '下午好',
  'mg.greeting.evening': '晚上好',
  'mg.greeting.overnight': '晚安',
  'mg.playingIn': '{rooms} 正在播放',
  'mg.dragToGroup': '把一个房间拖到另一个房间上即可编组。',
  'mg.groupAcrossSystems': '不同系统的房间无法编组在一起。',
  'mg.forRoom': '用于 {room}',
  'mg.recent': '最近播放',
  'mg.quietRooms.one': '{count} 个安静的房间',
  'mg.quietRooms.other': '{count} 个安静的房间',
  'mg.open': '打开',
  'mg.playingNow': '正在播放 {title}',
  'mg.queuedNext': '{title} 将在下一首播放',
  'mg.addedToQueue': '已把 {title} 加入播放队列',
  'mg.replacedQueue': '播放队列已替换为 {title}',
  'mg.queueEmptyBody': '从音乐库播放一些内容，或者用“添加到队列末尾”加入曲目。',
  'mg.queueSaved': '播放队列已保存为“{title}”',
  'mg.moveUp': '上移',
  'mg.moveDown': '下移',
  'mg.removeSelected': '移除选中的 {count} 项',
  'mg.selected': '已选择 {count} 项',
  'mg.editGroup': '编辑编组',
  'mg.addRooms': '添加房间',
  'mg.leaveGroup': '把 {room} 移出编组',
  'mg.thisRoom': '这个房间',
  'mg.groupedWith': '与 {room} 编组',
  'mg.noPairCandidates': '没有同型号的其他未配对扬声器。',
  'mg.lineIn': '线路输入',
  'mg.connected': '已连接',
  'mg.nothingConnected': '没有连接任何设备',
  'mg.none': '无',
  'mg.musicSources': '音乐来源',
  'mg.activeRoom': '正在播放于',
  'mg.chooseRoom': '选择房间',
  'mg.otherSystem': '在 {gen} 系统上；选择它的一个房间即可从那里播放',
  'mg.allServices': '所有服务',
  'mg.allServicesGen': '所有 {gen} 服务',
  'mg.playOtherSystem': '这在 {gen} 系统上。请选择该系统的一个房间来播放。',
  'mg.view': '视图',
  'mg.viewAuto': '自动',
  'mg.viewGrid': '网格',
  'mg.viewList': '列表',
  'mg.filterServices': '筛选服务',
  'mg.searchIn': '在 {service} 中搜索“{term}”',
  'mg.search.rooms': '房间',
  'mg.search.actions': '操作',
  'mg.search.music': '音乐',
  'mg.search.services': '音乐服务',
  'mg.partyMode': '派对模式',
  'mg.serviceRemoved': '已移除 {service}',
  'mg.quality': '质量',
  'mg.worst': '最慢 ms',
  'mg.wired': '有线',
  'mg.noRooms': '此系统中没有房间。',
  'mg.services.none': '此系统还没有配置音乐服务。',
  'mg.services.linked': '已在 Sonora 中关联',
  'mg.services.notLinked': '已在 Sonos 应用中配置，尚未在 Sonora 中关联',
  'mg.alsoRemembered': '还记得但无法触及：{names}。',
  'mg.noAnswer': '没有响应',
  'mg.favoritesEmpty': '无论在哪个控制器里存为 Sonos 收藏的内容都会出现在这里。列表由扬声器保存，所以到哪儿看都一样。',
  'mg.playlistsEmpty': 'Sonos 播放列表是你保存下来的播放队列。此系统上还没有。',
  'mg.settings.account': 'Sonos 账户',
  'mg.settings.account.blurb': '登录以解锁更多功能。',
  'mg.settings.services': '音乐服务',
  'mg.settings.services.blurb': '您已设置的流媒体服务。',
  'mg.settings.library': '音乐库',
  'mg.settings.library.blurb': '网络上的共享音乐文件夹。',
  'mg.settings.time': '日期与时间',
  'mg.settings.time.blurb': '时钟和时区设置。',
  'mg.settings.systems': '系统与房间',
  'mg.settings.systems.blurb': 'Sonora 在您的网络上看到的设备。',
  'mg.settings.parental': '内容过滤',
  'mg.settings.parental.blurb': '露骨内容过滤。',
  'mg.settings.s2': '升级顾问',
  'mg.settings.s2.blurb': '升级你的 Sonos 系统。',
  'mg.settings.network': '网络检查',
  'mg.settings.network.blurb': '找出网络上可能存在的性能问题。',
  'mg.settings.appearance': '外观',
  'mg.settings.appearance.blurb': 'Sonora 穿的主题，以及它说的语言。',
  'mg.settings.log': '日志',
  'mg.settings.log.blurb': '最近出错的记录，最新的在前。',
  'mg.nav.listen': '聆听',
  'mg.nav.browse': '浏览',
  'mg.showInBrowse': '在浏览中显示',
  'mg.collapseRail': '收起导航',
  'mg.expandRail': '展开导航',
  'mg.openPlayer': '打开播放器',
  'mg.closePlayer': '关闭播放器',
  'mg.playModes': '播放模式',
  'mg.upNext': '接下来',
  'mg.upNextAndRooms': '接下来与房间',
  'mg.inThisRoom': '在这个房间',
  'mg.soundAndRoom': '声音与设置',
  'mg.allRooms': '所有房间',
  'mg.dragToReorder': '拖动以重新排序',
  'mg.playsIn': '在 {room} 播放',
  'mg.searchHint': '搜索房间、操作、收藏或某项服务',
  'mg.dynamicColor': '取自封面的颜色',
  'mg.dynamicColorBody': '用当前房间正在播放内容的颜色为整个界面着色。',
  'mg.reload': '重新加载',
}

const zhTW = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': '房間',
  'mg.nav.clock': '鬧鐘',
  'mg.nav.settings': '設定',
  'mg.navigation': '區塊',
  'mg.all': '全部',
  'mg.greeting.morning': '早安',
  'mg.greeting.afternoon': '午安',
  'mg.greeting.evening': '晚安',
  'mg.greeting.overnight': '夜安',
  'mg.playingIn': '{rooms} 正在播放',
  'mg.dragToGroup': '把一個房間拖到另一個房間上就能組成群組。',
  'mg.groupAcrossSystems': '不同系統的房間無法組成群組。',
  'mg.forRoom': '用於 {room}',
  'mg.recent': '最近播放',
  'mg.quietRooms.one': '{count} 個安靜的房間',
  'mg.quietRooms.other': '{count} 個安靜的房間',
  'mg.open': '開啟',
  'mg.playingNow': '正在播放 {title}',
  'mg.queuedNext': '{title} 將在下一首播放',
  'mg.addedToQueue': '已把 {title} 加入播放佇列',
  'mg.replacedQueue': '播放佇列已換成 {title}',
  'mg.queueEmptyBody': '從音樂庫播點什麼，或用「加到佇列末端」加入曲目。',
  'mg.queueSaved': '播放佇列已存成「{title}」',
  'mg.moveUp': '上移',
  'mg.moveDown': '下移',
  'mg.removeSelected': '移除選取的 {count} 項',
  'mg.selected': '已選取 {count} 項',
  'mg.editGroup': '編輯群組',
  'mg.addRooms': '新增房間',
  'mg.leaveGroup': '把 {room} 移出群組',
  'mg.thisRoom': '這個房間',
  'mg.groupedWith': '與 {room} 群組',
  'mg.noPairCandidates': '沒有其他同型號的未配對喇叭。',
  'mg.lineIn': '線路輸入',
  'mg.connected': '已連接',
  'mg.nothingConnected': '沒有接任何東西',
  'mg.none': '無',
  'mg.musicSources': '音樂來源',
  'mg.activeRoom': '正在播放於',
  'mg.chooseRoom': '選擇房間',
  'mg.otherSystem': '在 {gen} 系統上；選它的一個房間就能從那裡播放',
  'mg.allServices': '所有服務',
  'mg.allServicesGen': '所有 {gen} 服務',
  'mg.playOtherSystem': '這在 {gen} 系統上。請選擇該系統的一個房間來播放。',
  'mg.view': '檢視',
  'mg.viewAuto': '自動',
  'mg.viewGrid': '格狀',
  'mg.viewList': '清單',
  'mg.filterServices': '篩選服務',
  'mg.searchIn': '在 {service} 中搜尋「{term}」',
  'mg.search.rooms': '房間',
  'mg.search.actions': '動作',
  'mg.search.music': '音樂',
  'mg.search.services': '音樂服務',
  'mg.partyMode': '派對模式',
  'mg.serviceRemoved': '已移除 {service}',
  'mg.quality': '品質',
  'mg.worst': '最慢 ms',
  'mg.wired': '有線',
  'mg.noRooms': '這套系統裡沒有房間。',
  'mg.services.none': '這套系統還沒有設定音樂服務。',
  'mg.services.linked': '已在 Sonora 中連結',
  'mg.services.notLinked': '已在 Sonos App 中設定，尚未在 Sonora 中連結',
  'mg.alsoRemembered': '還記得但搆不著：{names}。',
  'mg.noAnswer': '沒有回應',
  'mg.favoritesEmpty': '不管在哪個控制器裡存成 Sonos 我的最愛的內容都會出現在這裡。清單由喇叭保存，所以在哪裡看都一樣。',
  'mg.playlistsEmpty': 'Sonos 播放清單是你存下來的播放佇列。這套系統上還沒有。',
  'mg.settings.account': 'Sonos 帳戶',
  'mg.settings.account.blurb': '登入以解鎖更多功能。',
  'mg.settings.services': '音樂服務',
  'mg.settings.services.blurb': '您已設定的串流服務。',
  'mg.settings.library': '音樂庫',
  'mg.settings.library.blurb': '網路上的共用音樂資料夾。',
  'mg.settings.time': '日期與時間',
  'mg.settings.time.blurb': '時鐘與時區設定。',
  'mg.settings.systems': '系統與房間',
  'mg.settings.systems.blurb': 'Sonora 在您的網路上看到的裝置。',
  'mg.settings.parental': '內容過濾',
  'mg.settings.parental.blurb': '露骨內容過濾。',
  'mg.settings.s2': '升級顧問',
  'mg.settings.s2.blurb': '升級你的 Sonos 系統。',
  'mg.settings.network': '網路檢查',
  'mg.settings.network.blurb': '找出網路上可能存在的效能問題。',
  'mg.settings.appearance': '外觀',
  'mg.settings.appearance.blurb': 'Sonora 穿的佈景主題，以及它說的語言。',
  'mg.settings.log': '記錄',
  'mg.settings.log.blurb': '最近出錯的記錄，最新的在前。',
  'mg.nav.listen': '聆聽',
  'mg.nav.browse': '瀏覽',
  'mg.showInBrowse': '在瀏覽中顯示',
  'mg.collapseRail': '收合導覽',
  'mg.expandRail': '展開導覽',
  'mg.openPlayer': '開啟播放器',
  'mg.closePlayer': '關閉播放器',
  'mg.playModes': '播放模式',
  'mg.upNext': '接下來',
  'mg.upNextAndRooms': '接下來與房間',
  'mg.inThisRoom': '在這個房間',
  'mg.soundAndRoom': '聲音與設定',
  'mg.allRooms': '所有房間',
  'mg.dragToReorder': '拖曳以重新排序',
  'mg.playsIn': '在 {room} 播放',
  'mg.searchHint': '搜尋房間、操作、我的最愛或某項服務',
  'mg.dynamicColor': '取自封面的顏色',
  'mg.dynamicColorBody': '以目前房間正在播放內容的顏色為整個介面上色。',
  'mg.reload': '重新載入',
}

const csCZ = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Místnosti',
  'mg.nav.clock': 'Budíky',
  'mg.nav.settings': 'Nastavení',
  'mg.navigation': 'Sekce',
  'mg.all': 'Vše',
  'mg.greeting.morning': 'Dobré ráno',
  'mg.greeting.afternoon': 'Dobré odpoledne',
  'mg.greeting.evening': 'Dobrý večer',
  'mg.greeting.overnight': 'Dobrou noc',
  'mg.playingIn': 'Hraje ({rooms})',
  'mg.dragToGroup': 'Přetažením jedné místnosti na jinou je seskupíte.',
  'mg.groupAcrossSystems': 'Místnosti z různých systémů nelze seskupit.',
  'mg.forRoom': 'pro {room}',
  'mg.recent': 'Nedávno přehráváno',
  'mg.quietRooms.one': '{count} tichá místnost',
  'mg.quietRooms.other': '{count} tichých místností',
  'mg.open': 'Otevřít',
  'mg.playingNow': 'Přehrává se {title}',
  'mg.queuedNext': 'Jako další se přehraje {title}',
  'mg.addedToQueue': '{title} přidáno do fronty',
  'mg.replacedQueue': 'Fronta nahrazena položkou {title}',
  'mg.queueEmptyBody': 'Přehrajte něco z knihovny nebo přidejte skladby pomocí „Přidat na konec fronty“.',
  'mg.queueSaved': 'Fronta uložena jako „{title}“',
  'mg.moveUp': 'Posunout nahoru',
  'mg.moveDown': 'Posunout dolů',
  'mg.removeSelected': 'Odebrat vybrané ({count})',
  'mg.selected': 'Vybráno: {count}',
  'mg.editGroup': 'Upravit skupinu',
  'mg.addRooms': 'Přidat místnosti',
  'mg.leaveGroup': 'Vyjmout {room} ze skupiny',
  'mg.thisRoom': 'Tato místnost',
  'mg.groupedWith': 'Seskupeno s {room}',
  'mg.noPairCandidates': 'Žádný další nespárovaný reproduktor tohoto modelu.',
  'mg.lineIn': 'Linkový vstup',
  'mg.connected': 'Připojeno',
  'mg.nothingConnected': 'Nic není připojeno',
  'mg.none': 'Žádné',
  'mg.musicSources': 'Zdroje hudby',
  'mg.activeRoom': 'Hraje v',
  'mg.chooseRoom': 'Vyberte místnost',
  'mg.otherSystem': 'V systému {gen}; chcete-li z něj přehrávat, vyberte jednu z jeho místností',
  'mg.allServices': 'Všechny služby',
  'mg.allServicesGen': 'Všechny služby {gen}',
  'mg.playOtherSystem': 'Je to v systému {gen}. K přehrání vyberte jednu z jeho místností.',
  'mg.view': 'Zobrazení',
  'mg.viewAuto': 'Automaticky',
  'mg.viewGrid': 'Mřížka',
  'mg.viewList': 'Seznam',
  'mg.filterServices': 'Filtrovat služby',
  'mg.searchIn': 'Vyhledat „{term}“ v {service}',
  'mg.search.rooms': 'Místnosti',
  'mg.search.actions': 'Akce',
  'mg.search.music': 'Hudba',
  'mg.search.services': 'Hudební služby',
  'mg.partyMode': 'Režim párty',
  'mg.serviceRemoved': 'Služba {service} odebrána',
  'mg.quality': 'Kvalita',
  'mg.worst': 'nejhorší ms',
  'mg.wired': 'Kabelem',
  'mg.noRooms': 'V tomto systému nejsou žádné místnosti.',
  'mg.services.none': 'V tomto systému zatím nejsou nastavené žádné hudební služby.',
  'mg.services.linked': 'Propojeno v Sonoře',
  'mg.services.notLinked': 'Nastaveno v aplikaci Sonos, zatím nepropojeno v Sonoře',
  'mg.alsoRemembered': 'Zapamatované, ale mimo dosah: {names}.',
  'mg.noAnswer': 'bez odpovědi',
  'mg.favoritesEmpty': 'Vše, co v jakémkoli ovladači uložíte do Oblíbených Sonos, se zobrazí zde. Seznam uchovávají reproduktory, takže je všude stejný.',
  'mg.playlistsEmpty': 'Playlisty Sonos jsou uložené fronty. V tomto systému zatím žádné nejsou.',
  'mg.settings.account': 'Účet Sonos',
  'mg.settings.account.blurb': 'Přihlaste se a odemkněte další funkce.',
  'mg.settings.services': 'Hudební služby',
  'mg.settings.services.blurb': 'Streamovací služby, které jste nastavili.',
  'mg.settings.library': 'Hudební knihovna',
  'mg.settings.library.blurb': 'Sdílené složky s hudbou ve vaší síti.',
  'mg.settings.time': 'Datum a čas',
  'mg.settings.time.blurb': 'Nastavení hodin a časového pásma.',
  'mg.settings.systems': 'Systémy a místnosti',
  'mg.settings.systems.blurb': 'Která zařízení Sonora vidí ve vaší síti.',
  'mg.settings.parental': 'Filtry obsahu',
  'mg.settings.parental.blurb': 'Filtrování explicitního obsahu.',
  'mg.settings.s2': 'Poradce pro upgrade',
  'mg.settings.s2.blurb': 'Upgradujte svůj systém Sonos.',
  'mg.settings.network': 'Kontrola sítě',
  'mg.settings.network.blurb': 'Odhalte možné potíže s výkonem ve vaší síti.',
  'mg.settings.appearance': 'Vzhled',
  'mg.settings.appearance.blurb': 'Motiv, který Sonora používá, a jazyk, kterým mluví.',
  'mg.settings.log': 'Záznam',
  'mg.settings.log.blurb': 'Co se v poslední době pokazilo, od nejnovějšího.',
  'mg.nav.listen': 'Poslech',
  'mg.nav.browse': 'Procházet',
  'mg.showInBrowse': 'Zobrazit v Procházení',
  'mg.collapseRail': 'Sbalit navigaci',
  'mg.expandRail': 'Rozbalit navigaci',
  'mg.openPlayer': 'Otevřít přehrávač',
  'mg.closePlayer': 'Zavřít přehrávač',
  'mg.playModes': 'Režimy přehrávání',
  'mg.upNext': 'Na řadě',
  'mg.upNextAndRooms': 'Na řadě a místnosti',
  'mg.inThisRoom': 'V této místnosti',
  'mg.soundAndRoom': 'Zvuk a nastavení',
  'mg.allRooms': 'Všechny místnosti',
  'mg.dragToReorder': 'Přetažením změníte pořadí',
  'mg.playsIn': 'Hraje v: {room}',
  'mg.searchHint': 'Hledejte místnosti, akce, oblíbené nebo službu',
  'mg.dynamicColor': 'Barvy z obalu',
  'mg.dynamicColorBody': 'Obarví celé rozhraní barvami toho, co hraje v zobrazené místnosti.',
  'mg.reload': 'Znovu načíst',
}

const daDK = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Rum',
  'mg.nav.clock': 'Alarmer',
  'mg.nav.settings': 'Indstillinger',
  'mg.navigation': 'Sektioner',
  'mg.all': 'Alle',
  'mg.greeting.morning': 'Godmorgen',
  'mg.greeting.afternoon': 'God eftermiddag',
  'mg.greeting.evening': 'Godaften',
  'mg.greeting.overnight': 'Godnat',
  'mg.playingIn': 'Afspiller i {rooms}',
  'mg.dragToGroup': 'Træk et rum hen på et andet for at gruppere dem.',
  'mg.groupAcrossSystems': 'Rum på forskellige systemer kan ikke grupperes sammen.',
  'mg.forRoom': 'til {room}',
  'mg.recent': 'Afspillet for nylig',
  'mg.quietRooms.one': '{count} stille rum',
  'mg.quietRooms.other': '{count} stille rum',
  'mg.open': 'Åbn',
  'mg.playingNow': 'Afspiller {title}',
  'mg.queuedNext': 'Afspiller {title} som det næste',
  'mg.addedToQueue': '{title} blev føjet til køen',
  'mg.replacedQueue': 'Køen blev erstattet med {title}',
  'mg.queueEmptyBody': 'Afspil noget fra biblioteket, eller tilføj numre med "Føj til slutningen af køen".',
  'mg.queueSaved': 'Køen blev gemt som "{title}"',
  'mg.moveUp': 'Flyt op',
  'mg.moveDown': 'Flyt ned',
  'mg.removeSelected': 'Fjern {count} valgte',
  'mg.selected': '{count} valgt',
  'mg.editGroup': 'Rediger gruppe',
  'mg.addRooms': 'Tilføj rum',
  'mg.leaveGroup': 'Tag {room} ud af gruppen',
  'mg.thisRoom': 'Dette rum',
  'mg.groupedWith': 'Grupperet med {room}',
  'mg.noPairCandidates': 'Ingen anden uparret højttaler af denne model.',
  'mg.lineIn': 'Line-in',
  'mg.connected': 'Forbundet',
  'mg.nothingConnected': 'Intet tilsluttet',
  'mg.none': 'Ingen',
  'mg.musicSources': 'Musikkilder',
  'mg.activeRoom': 'Afspiller i',
  'mg.chooseRoom': 'Vælg et rum',
  'mg.otherSystem': 'På {gen}-systemet; vælg et af dets rum for at afspille derfra',
  'mg.allServices': 'Alle tjenester',
  'mg.allServicesGen': 'Alle {gen}-tjenester',
  'mg.playOtherSystem': 'Det ligger på {gen}-systemet. Vælg et af dets rum for at afspille det.',
  'mg.view': 'Visning',
  'mg.viewAuto': 'Automatisk',
  'mg.viewGrid': 'Gitter',
  'mg.viewList': 'Liste',
  'mg.filterServices': 'Filtrer tjenester',
  'mg.searchIn': 'Søg efter "{term}" i {service}',
  'mg.search.rooms': 'Rum',
  'mg.search.actions': 'Handlinger',
  'mg.search.music': 'Musik',
  'mg.search.services': 'Musiktjenester',
  'mg.partyMode': 'Party-tilstand',
  'mg.serviceRemoved': '{service} blev fjernet',
  'mg.quality': 'Kvalitet',
  'mg.worst': 'værste ms',
  'mg.wired': 'Kablet',
  'mg.noRooms': 'Ingen rum i dette system.',
  'mg.services.none': 'Der er endnu ikke konfigureret nogen musiktjenester på dette system.',
  'mg.services.linked': 'Tilknyttet i Sonora',
  'mg.services.notLinked': 'Konfigureret i Sonos-appen, endnu ikke tilknyttet i Sonora',
  'mg.alsoRemembered': 'Husket, men uden for rækkevidde: {names}.',
  'mg.noAnswer': 'intet svar',
  'mg.favoritesEmpty': 'Alt, hvad du gemmer som Sonos-favorit i en hvilken som helst controller, vises her. Højttalerne gemmer listen, så det er den samme liste overalt.',
  'mg.playlistsEmpty': 'Sonos-playlister er køer, du har gemt. Der er endnu ingen på dette system.',
  'mg.settings.account': 'Sonos-konto',
  'mg.settings.account.blurb': 'Log ind for at låse op for flere funktioner.',
  'mg.settings.services': 'Musiktjenester',
  'mg.settings.services.blurb': 'De streamingtjenester, du har konfigureret.',
  'mg.settings.library': 'Musikbibliotek',
  'mg.settings.library.blurb': 'Delte musikmapper på dit netværk.',
  'mg.settings.time': 'Dato og tid',
  'mg.settings.time.blurb': 'Indstillinger for ur og tidszone.',
  'mg.settings.systems': 'Systemer og rum',
  'mg.settings.systems.blurb': 'Hvilke enheder Sonora ser på dit netværk.',
  'mg.settings.parental': 'Indholdsfiltre',
  'mg.settings.parental.blurb': 'Filtrering af eksplicit indhold.',
  'mg.settings.s2': 'Opgraderingsrådgiver',
  'mg.settings.s2.blurb': 'Opgrader dit Sonos-system.',
  'mg.settings.network': 'Netværkstjek',
  'mg.settings.network.blurb': 'Find mulige ydeevneproblemer på dit netværk.',
  'mg.settings.appearance': 'Udseende',
  'mg.settings.appearance.blurb': 'Det tema, Sonora bruger, og det sprog, den taler.',
  'mg.settings.log': 'Log',
  'mg.settings.log.blurb': 'Hvad der er gået galt for nylig, nyeste først.',
  'mg.nav.listen': 'Lyt',
  'mg.nav.browse': 'Gennemse',
  'mg.showInBrowse': 'Vis i Gennemse',
  'mg.collapseRail': 'Skjul navigation',
  'mg.expandRail': 'Vis navigation',
  'mg.openPlayer': 'Åbn afspilleren',
  'mg.closePlayer': 'Luk afspilleren',
  'mg.playModes': 'Afspilningstilstande',
  'mg.upNext': 'Næste',
  'mg.upNextAndRooms': 'Næste og rum',
  'mg.inThisRoom': 'I dette rum',
  'mg.soundAndRoom': 'Lyd og indstillinger',
  'mg.allRooms': 'Alle rum',
  'mg.dragToReorder': 'Træk for at ændre rækkefølgen',
  'mg.playsIn': 'Spiller i {room}',
  'mg.searchHint': 'Søg efter rum, handlinger, favoritter eller en tjeneste',
  'mg.dynamicColor': 'Farver fra coveret',
  'mg.dynamicColorBody': 'Farver hele brugerfladen med farverne fra det, der spiller i det viste rum.',
  'mg.reload': 'Genindlæs',
}

const fiFI = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Huoneet',
  'mg.nav.clock': 'Hälytykset',
  'mg.nav.settings': 'Asetukset',
  'mg.navigation': 'Osiot',
  'mg.all': 'Kaikki',
  'mg.greeting.morning': 'Hyvää huomenta',
  'mg.greeting.afternoon': 'Hyvää päivää',
  'mg.greeting.evening': 'Hyvää iltaa',
  'mg.greeting.overnight': 'Hyvää yötä',
  'mg.playingIn': 'Soi: {rooms}',
  'mg.dragToGroup': 'Ryhmitä huoneet vetämällä huone toisen päälle.',
  'mg.groupAcrossSystems': 'Eri järjestelmien huoneita ei voi ryhmittää yhteen.',
  'mg.forRoom': 'kohteelle {room}',
  'mg.recent': 'Viimeksi toistetut',
  'mg.quietRooms.one': '{count} hiljainen huone',
  'mg.quietRooms.other': '{count} hiljaista huonetta',
  'mg.open': 'Avaa',
  'mg.playingNow': 'Toistetaan: {title}',
  'mg.queuedNext': 'Seuraavaksi: {title}',
  'mg.addedToQueue': 'Lisättiin jonoon: {title}',
  'mg.replacedQueue': 'Jono korvattiin: {title}',
  'mg.queueEmptyBody': 'Toista jotain kirjastosta tai lisää kappaleita valinnalla "Lisää jonon loppuun".',
  'mg.queueSaved': 'Jono tallennettiin nimellä "{title}"',
  'mg.moveUp': 'Siirrä ylös',
  'mg.moveDown': 'Siirrä alas',
  'mg.removeSelected': 'Poista {count} valittua',
  'mg.selected': '{count} valittu',
  'mg.editGroup': 'Muokkaa ryhmää',
  'mg.addRooms': 'Lisää huoneita',
  'mg.leaveGroup': 'Poista {room} ryhmästä',
  'mg.thisRoom': 'Tämä huone',
  'mg.groupedWith': 'Samassa ryhmässä: {room}',
  'mg.noPairCandidates': 'Tätä mallia ei ole muita parittomia kaiuttimia.',
  'mg.lineIn': 'Linjatulo',
  'mg.connected': 'Yhdistetty',
  'mg.nothingConnected': 'Ei mitään yhdistettynä',
  'mg.none': 'Ei mitään',
  'mg.musicSources': 'Musiikkilähteet',
  'mg.activeRoom': 'Toistetaan huoneessa',
  'mg.chooseRoom': 'Valitse huone',
  'mg.otherSystem': '{gen}-järjestelmässä; valitse jokin sen huoneista toistaaksesi siitä',
  'mg.allServices': 'Kaikki palvelut',
  'mg.allServicesGen': 'Kaikki {gen}-palvelut',
  'mg.playOtherSystem': 'Se on {gen}-järjestelmässä. Valitse sen huone toistaaksesi.',
  'mg.view': 'Näkymä',
  'mg.viewAuto': 'Automaattinen',
  'mg.viewGrid': 'Ruudukko',
  'mg.viewList': 'Luettelo',
  'mg.filterServices': 'Suodata palveluita',
  'mg.searchIn': 'Etsi "{term}": {service}',
  'mg.search.rooms': 'Huoneet',
  'mg.search.actions': 'Toiminnot',
  'mg.search.music': 'Musiikki',
  'mg.search.services': 'Musiikkipalvelut',
  'mg.partyMode': 'Juhlatila',
  'mg.serviceRemoved': 'Poistettiin: {service}',
  'mg.quality': 'Laatu',
  'mg.worst': 'hitain ms',
  'mg.wired': 'Langallinen',
  'mg.noRooms': 'Tässä järjestelmässä ei ole huoneita.',
  'mg.services.none': 'Tähän järjestelmään ei ole vielä määritetty musiikkipalveluita.',
  'mg.services.linked': 'Yhdistetty Sonoraan',
  'mg.services.notLinked': 'Määritetty Sonos-sovelluksessa, ei vielä yhdistetty Sonoraan',
  'mg.alsoRemembered': 'Muistetaan myös, mutta ei tavoitettavissa: {names}.',
  'mg.noAnswer': 'ei vastausta',
  'mg.favoritesEmpty': 'Kaikki, minkä tallennat Sonos-suosikiksi missä tahansa ohjaimessa, näkyy täällä. Luettelo on kaiuttimissa, joten se on sama kaikkialla.',
  'mg.playlistsEmpty': 'Sonos-toistoluettelot ovat tallentamiasi jonoja. Tässä järjestelmässä ei ole vielä yhtään.',
  'mg.settings.account': 'Sonos-tili',
  'mg.settings.account.blurb': 'Kirjaudu sisään, niin saat lisää ominaisuuksia käyttöön.',
  'mg.settings.services': 'Musiikkipalvelut',
  'mg.settings.services.blurb': 'Määrittämäsi suoratoistopalvelut.',
  'mg.settings.library': 'Musiikkikirjasto',
  'mg.settings.library.blurb': 'Verkkosi jaetut musiikkikansiot.',
  'mg.settings.time': 'Päivämäärä ja aika',
  'mg.settings.time.blurb': 'Kellon ja aikavyöhykkeen asetukset.',
  'mg.settings.systems': 'Järjestelmät ja huoneet',
  'mg.settings.systems.blurb': 'Mitkä laitteet Sonora näkee verkossasi.',
  'mg.settings.parental': 'Sisältösuodattimet',
  'mg.settings.parental.blurb': 'Sopimattoman sisällön suodatus.',
  'mg.settings.s2': 'Päivitysneuvoja',
  'mg.settings.s2.blurb': 'Päivitä Sonos-järjestelmäsi.',
  'mg.settings.network': 'Verkon tarkistus',
  'mg.settings.network.blurb': 'Tunnista verkkosi mahdolliset suorituskykyongelmat.',
  'mg.settings.appearance': 'Ulkoasu',
  'mg.settings.appearance.blurb': 'Sonoran teema ja kieli.',
  'mg.settings.log': 'Loki',
  'mg.settings.log.blurb': 'Mikä meni viime aikoina vikaan, uusin ensin.',
  'mg.nav.listen': 'Kuuntele',
  'mg.nav.browse': 'Selaa',
  'mg.showInBrowse': 'Näytä Selaa-näkymässä',
  'mg.collapseRail': 'Pienennä navigointi',
  'mg.expandRail': 'Laajenna navigointi',
  'mg.openPlayer': 'Avaa soitin',
  'mg.closePlayer': 'Sulje soitin',
  'mg.playModes': 'Toistotilat',
  'mg.upNext': 'Seuraavaksi',
  'mg.upNextAndRooms': 'Seuraavaksi ja huoneet',
  'mg.inThisRoom': 'Tässä huoneessa',
  'mg.soundAndRoom': 'Ääni ja asetukset',
  'mg.allRooms': 'Kaikki huoneet',
  'mg.dragToReorder': 'Järjestä vetämällä',
  'mg.playsIn': 'Soi huoneessa {room}',
  'mg.searchHint': 'Hae huoneita, toimintoja, suosikkeja tai palvelua',
  'mg.dynamicColor': 'Värit kansikuvasta',
  'mg.dynamicColorBody': 'Sävyttää koko käyttöliittymän näkyvän huoneen soivan musiikin väreillä.',
  'mg.reload': 'Lataa uudelleen',
}

const nbNO = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Rom',
  'mg.nav.clock': 'Alarmer',
  'mg.nav.settings': 'Innstillinger',
  'mg.navigation': 'Seksjoner',
  'mg.all': 'Alle',
  'mg.greeting.morning': 'God morgen',
  'mg.greeting.afternoon': 'God ettermiddag',
  'mg.greeting.evening': 'God kveld',
  'mg.greeting.overnight': 'God natt',
  'mg.playingIn': 'Spiller i {rooms}',
  'mg.dragToGroup': 'Dra ett rom over på et annet for å gruppere dem.',
  'mg.groupAcrossSystems': 'Rom i ulike systemer kan ikke grupperes sammen.',
  'mg.forRoom': 'for {room}',
  'mg.recent': 'Nylig spilt',
  'mg.quietRooms.one': '{count} stille rom',
  'mg.quietRooms.other': '{count} stille rom',
  'mg.open': 'Åpne',
  'mg.playingNow': 'Spiller {title}',
  'mg.queuedNext': 'Spiller {title} neste',
  'mg.addedToQueue': 'La til {title} i køen',
  'mg.replacedQueue': 'Køen erstattet med {title}',
  'mg.queueEmptyBody': 'Spill noe fra biblioteket, eller legg til spor med «Legg til sist i køen».',
  'mg.queueSaved': 'Lagret køen som «{title}»',
  'mg.moveUp': 'Flytt opp',
  'mg.moveDown': 'Flytt ned',
  'mg.removeSelected': 'Fjern {count} valgte',
  'mg.selected': '{count} valgt',
  'mg.editGroup': 'Rediger gruppe',
  'mg.addRooms': 'Legg til rom',
  'mg.leaveGroup': 'Ta {room} ut av gruppen',
  'mg.thisRoom': 'Dette rommet',
  'mg.groupedWith': 'Gruppert med {room}',
  'mg.noPairCandidates': 'Ingen annen uparet høyttaler av denne modellen.',
  'mg.lineIn': 'Linjeinngang',
  'mg.connected': 'Tilkoblet',
  'mg.nothingConnected': 'Ingenting tilkoblet',
  'mg.none': 'Ingen',
  'mg.musicSources': 'Musikkilder',
  'mg.activeRoom': 'Spiller i',
  'mg.chooseRoom': 'Velg et rom',
  'mg.otherSystem': 'På {gen}-systemet; velg ett av rommene der for å spille fra det',
  'mg.allServices': 'Alle tjenester',
  'mg.allServicesGen': 'Alle {gen}-tjenester',
  'mg.playOtherSystem': 'Det er på {gen}-systemet. Velg et av rommene der for å spille det.',
  'mg.view': 'Visning',
  'mg.viewAuto': 'Automatisk',
  'mg.viewGrid': 'Rutenett',
  'mg.viewList': 'Liste',
  'mg.filterServices': 'Filtrer tjenester',
  'mg.searchIn': 'Søk etter «{term}» i {service}',
  'mg.search.rooms': 'Rom',
  'mg.search.actions': 'Handlinger',
  'mg.search.music': 'Musikk',
  'mg.search.services': 'Musikktjenester',
  'mg.partyMode': 'Partymodus',
  'mg.serviceRemoved': 'Fjernet {service}',
  'mg.quality': 'Kvalitet',
  'mg.worst': 'tregeste ms',
  'mg.wired': 'Kablet',
  'mg.noRooms': 'Ingen rom i dette systemet.',
  'mg.services.none': 'Ingen musikktjenester er satt opp på dette systemet ennå.',
  'mg.services.linked': 'Koblet til i Sonora',
  'mg.services.notLinked': 'Satt opp i Sonos-appen, ikke koblet til i Sonora ennå',
  'mg.alsoRemembered': 'Husket, men utenfor rekkevidde: {names}.',
  'mg.noAnswer': 'ingen svar',
  'mg.favoritesEmpty': 'Alt du lagrer som en Sonos-favoritt, i hvilken som helst kontroller, vises her. Høyttalerne holder listen, så den er den samme overalt.',
  'mg.playlistsEmpty': 'Sonos-spillelister er køer du har lagret. Det finnes ingen på dette systemet ennå.',
  'mg.settings.account': 'Sonos-konto',
  'mg.settings.account.blurb': 'Logg på for å låse opp flere funksjoner.',
  'mg.settings.services': 'Musikktjenester',
  'mg.settings.services.blurb': 'Strømmetjenestene du har konfigurert.',
  'mg.settings.library': 'Musikkbibliotek',
  'mg.settings.library.blurb': 'Delte musikkmapper på nettverket ditt.',
  'mg.settings.time': 'Dato og tid',
  'mg.settings.time.blurb': 'Innstillinger for klokke og tidssone.',
  'mg.settings.systems': 'Systemer og rom',
  'mg.settings.systems.blurb': 'Hvilke enheter Sonora ser på nettverket ditt.',
  'mg.settings.parental': 'Innholdsfilter',
  'mg.settings.parental.blurb': 'Filtrering av eksplisitt innhold.',
  'mg.settings.s2': 'Oppgraderingsrådgiver',
  'mg.settings.s2.blurb': 'Oppgrader Sonos-systemet ditt.',
  'mg.settings.network': 'Nettverkssjekk',
  'mg.settings.network.blurb': 'Finn mulige ytelsesproblemer på nettverket ditt.',
  'mg.settings.appearance': 'Utseende',
  'mg.settings.appearance.blurb': 'Temaet Sonora bruker og språket den snakker.',
  'mg.settings.log': 'Logg',
  'mg.settings.log.blurb': 'Hva som gikk galt nylig, nyeste først.',
  'mg.nav.listen': 'Lytt',
  'mg.nav.browse': 'Bla gjennom',
  'mg.showInBrowse': 'Vis i Bla gjennom',
  'mg.collapseRail': 'Skjul navigasjonen',
  'mg.expandRail': 'Vis navigasjonen',
  'mg.openPlayer': 'Åpne spilleren',
  'mg.closePlayer': 'Lukk spilleren',
  'mg.playModes': 'Avspillingsmoduser',
  'mg.upNext': 'Neste',
  'mg.upNextAndRooms': 'Neste og rom',
  'mg.inThisRoom': 'I dette rommet',
  'mg.soundAndRoom': 'Lyd og innstillinger',
  'mg.allRooms': 'Alle rom',
  'mg.dragToReorder': 'Dra for å endre rekkefølgen',
  'mg.playsIn': 'Spiller i {room}',
  'mg.searchHint': 'Søk etter rom, handlinger, favoritter eller en tjeneste',
  'mg.dynamicColor': 'Farger fra coveret',
  'mg.dynamicColorBody': 'Farger hele grensesnittet med fargene fra det som spilles i rommet som vises.',
  'mg.reload': 'Last inn på nytt',
}

const plPL = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Pomieszczenia',
  'mg.nav.clock': 'Alarmy',
  'mg.nav.settings': 'Ustawienia',
  'mg.navigation': 'Sekcje',
  'mg.all': 'Wszystkie',
  'mg.greeting.morning': 'Dzień dobry',
  'mg.greeting.afternoon': 'Dzień dobry',
  'mg.greeting.evening': 'Dobry wieczór',
  'mg.greeting.overnight': 'Dobranoc',
  'mg.playingIn': 'Gra ({rooms})',
  'mg.dragToGroup': 'Przeciągnij jedno pomieszczenie na drugie, aby je zgrupować.',
  'mg.groupAcrossSystems': 'Pomieszczeń z różnych systemów nie można zgrupować.',
  'mg.forRoom': 'dla: {room}',
  'mg.recent': 'Ostatnio odtwarzane',
  'mg.quietRooms.one': '{count} ciche pomieszczenie',
  'mg.quietRooms.other': 'Ciche pomieszczenia: {count}',
  'mg.open': 'Otwórz',
  'mg.playingNow': 'Odtwarzanie: {title}',
  'mg.queuedNext': 'Następne w kolejce: {title}',
  'mg.addedToQueue': 'Dodano do kolejki: {title}',
  'mg.replacedQueue': 'Kolejka zastąpiona: {title}',
  'mg.queueEmptyBody': 'Odtwórz coś z biblioteki lub dodaj utwory za pomocą opcji „Dodaj na koniec kolejki”.',
  'mg.queueSaved': 'Zapisano kolejkę jako „{title}”',
  'mg.moveUp': 'Przenieś w górę',
  'mg.moveDown': 'Przenieś w dół',
  'mg.removeSelected': 'Usuń zaznaczone ({count})',
  'mg.selected': 'Zaznaczono: {count}',
  'mg.editGroup': 'Edytuj grupę',
  'mg.addRooms': 'Dodaj pomieszczenia',
  'mg.leaveGroup': 'Usuń z grupy: {room}',
  'mg.thisRoom': 'To pomieszczenie',
  'mg.groupedWith': 'Zgrupowane z: {room}',
  'mg.noPairCandidates': 'Brak innego niesparowanego głośnika tego modelu.',
  'mg.lineIn': 'Wejście liniowe',
  'mg.connected': 'Połączono',
  'mg.nothingConnected': 'Nic nie podłączono',
  'mg.none': 'Brak',
  'mg.musicSources': 'Źródła muzyki',
  'mg.activeRoom': 'Odtwarzanie w',
  'mg.chooseRoom': 'Wybierz pomieszczenie',
  'mg.otherSystem': 'W systemie {gen}; wybierz jedno z jego pomieszczeń, aby z niego odtwarzać',
  'mg.allServices': 'Wszystkie serwisy',
  'mg.allServicesGen': 'Wszystkie usługi {gen}',
  'mg.playOtherSystem': 'To jest w systemie {gen}. Wybierz jedno z jego pomieszczeń, aby odtworzyć.',
  'mg.view': 'Widok',
  'mg.viewAuto': 'Automatyczny',
  'mg.viewGrid': 'Siatka',
  'mg.viewList': 'Lista',
  'mg.filterServices': 'Filtruj serwisy',
  'mg.searchIn': 'Szukaj „{term}” w serwisie {service}',
  'mg.search.rooms': 'Pomieszczenia',
  'mg.search.actions': 'Działania',
  'mg.search.music': 'Muzyka',
  'mg.search.services': 'Serwisy muzyczne',
  'mg.partyMode': 'Tryb imprezy',
  'mg.serviceRemoved': 'Usunięto serwis {service}',
  'mg.quality': 'Jakość',
  'mg.worst': 'najwolniej, ms',
  'mg.wired': 'Przewodowe',
  'mg.noRooms': 'Brak pomieszczeń w tym systemie.',
  'mg.services.none': 'W tym systemie nie skonfigurowano jeszcze żadnych serwisów muzycznych.',
  'mg.services.linked': 'Połączony z aplikacją Sonora',
  'mg.services.notLinked': 'Skonfigurowany w aplikacji Sonos, jeszcze niepołączony z aplikacją Sonora',
  'mg.alsoRemembered': 'Zapamiętane, ale poza zasięgiem: {names}.',
  'mg.noAnswer': 'brak odpowiedzi',
  'mg.favoritesEmpty': 'Wszystko, co zapiszesz jako ulubione Sonos w dowolnej aplikacji sterującej, pojawi się tutaj. Listę przechowują głośniki, więc wszędzie jest taka sama.',
  'mg.playlistsEmpty': 'Playlisty Sonos to zapisane kolejki. W tym systemie nie ma jeszcze żadnych.',
  'mg.settings.account': 'Konto Sonos',
  'mg.settings.account.blurb': 'Zaloguj się, aby odblokować więcej funkcji.',
  'mg.settings.services': 'Serwisy muzyczne',
  'mg.settings.services.blurb': 'Skonfigurowane przez Ciebie serwisy streamingowe.',
  'mg.settings.library': 'Biblioteka muzyczna',
  'mg.settings.library.blurb': 'Udostępnione foldery z muzyką w Twojej sieci.',
  'mg.settings.time': 'Data i godzina',
  'mg.settings.time.blurb': 'Ustawienia zegara i strefy czasowej.',
  'mg.settings.systems': 'Systemy i pomieszczenia',
  'mg.settings.systems.blurb': 'Jakie urządzenia Sonora widzi w Twojej sieci.',
  'mg.settings.parental': 'Filtry zawartości',
  'mg.settings.parental.blurb': 'Filtrowanie treści dla dorosłych.',
  'mg.settings.s2': 'Doradca aktualizacji',
  'mg.settings.s2.blurb': 'Zaktualizuj swój system Sonos.',
  'mg.settings.network': 'Test sieci',
  'mg.settings.network.blurb': 'Wykryj możliwe problemy z wydajnością w Twojej sieci.',
  'mg.settings.appearance': 'Wygląd',
  'mg.settings.appearance.blurb': 'Motyw aplikacji Sonora i jej język.',
  'mg.settings.log': 'Dziennik',
  'mg.settings.log.blurb': 'Ostatnie błędy, od najnowszych.',
  'mg.nav.listen': 'Słuchaj',
  'mg.nav.browse': 'Przeglądaj',
  'mg.showInBrowse': 'Pokaż w Przeglądaniu',
  'mg.collapseRail': 'Zwiń nawigację',
  'mg.expandRail': 'Rozwiń nawigację',
  'mg.openPlayer': 'Otwórz odtwarzacz',
  'mg.closePlayer': 'Zamknij odtwarzacz',
  'mg.playModes': 'Tryby odtwarzania',
  'mg.upNext': 'Następne',
  'mg.upNextAndRooms': 'Następne i pomieszczenia',
  'mg.inThisRoom': 'W tym pomieszczeniu',
  'mg.soundAndRoom': 'Dźwięk i ustawienia',
  'mg.allRooms': 'Wszystkie pomieszczenia',
  'mg.dragToReorder': 'Przeciągnij, aby zmienić kolejność',
  'mg.playsIn': 'Gra w: {room}',
  'mg.searchHint': 'Szukaj pomieszczeń, działań, ulubionych lub serwisu',
  'mg.dynamicColor': 'Kolory z okładki',
  'mg.dynamicColorBody': 'Barwi cały interfejs kolorami tego, co gra w wyświetlanym pomieszczeniu.',
  'mg.reload': 'Odśwież',
}

const ptPT = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Divisões',
  'mg.nav.clock': 'Despertadores',
  'mg.nav.settings': 'Definições',
  'mg.navigation': 'Secções',
  'mg.all': 'Tudo',
  'mg.greeting.morning': 'Bom dia',
  'mg.greeting.afternoon': 'Boa tarde',
  'mg.greeting.evening': 'Boa noite',
  'mg.greeting.overnight': 'Boa noite',
  'mg.playingIn': 'A tocar em {rooms}',
  'mg.dragToGroup': 'Arraste uma divisão para cima de outra para as agrupar.',
  'mg.groupAcrossSystems': 'Não é possível agrupar divisões de sistemas diferentes.',
  'mg.forRoom': 'para {room}',
  'mg.recent': 'Reproduzido recentemente',
  'mg.quietRooms.one': '{count} divisão em silêncio',
  'mg.quietRooms.other': '{count} divisões em silêncio',
  'mg.open': 'Abrir',
  'mg.playingNow': 'A reproduzir {title}',
  'mg.queuedNext': '{title} será reproduzido a seguir',
  'mg.addedToQueue': '{title} foi adicionado à fila',
  'mg.replacedQueue': 'Fila substituída por {title}',
  'mg.queueEmptyBody': 'Reproduza algo da Biblioteca ou adicione faixas com «Adicionar ao fim da fila».',
  'mg.queueSaved': 'Fila guardada como «{title}»',
  'mg.moveUp': 'Mover para cima',
  'mg.moveDown': 'Mover para baixo',
  'mg.removeSelected': 'Remover {count} selecionados',
  'mg.selected': '{count} selecionados',
  'mg.editGroup': 'Editar grupo',
  'mg.addRooms': 'Adicionar divisões',
  'mg.leaveGroup': 'Retirar {room} do grupo',
  'mg.thisRoom': 'Esta divisão',
  'mg.groupedWith': 'Agrupada com {room}',
  'mg.noPairCandidates': 'Não há outro altifalante sem par deste modelo.',
  'mg.lineIn': 'Entrada de linha',
  'mg.connected': 'Ligado',
  'mg.nothingConnected': 'Nada ligado',
  'mg.none': 'Nenhum',
  'mg.musicSources': 'Origens de música',
  'mg.activeRoom': 'A reproduzir em',
  'mg.chooseRoom': 'Escolher uma divisão',
  'mg.otherSystem': 'No sistema {gen}; escolha uma das suas divisões para reproduzir a partir dele',
  'mg.allServices': 'Todos os serviços',
  'mg.allServicesGen': 'Todos os serviços do {gen}',
  'mg.playOtherSystem': 'Isso está no sistema {gen}. Escolha uma das suas divisões para reproduzir.',
  'mg.view': 'Vista',
  'mg.viewAuto': 'Automática',
  'mg.viewGrid': 'Grelha',
  'mg.viewList': 'Lista',
  'mg.filterServices': 'Filtrar serviços',
  'mg.searchIn': 'Pesquisar «{term}» em {service}',
  'mg.search.rooms': 'Divisões',
  'mg.search.actions': 'Ações',
  'mg.search.music': 'Música',
  'mg.search.services': 'Serviços de música',
  'mg.partyMode': 'Modo de festa',
  'mg.serviceRemoved': '{service} removido',
  'mg.quality': 'Qualidade',
  'mg.worst': 'pior ms',
  'mg.wired': 'Com fios',
  'mg.noRooms': 'Não há divisões neste sistema.',
  'mg.services.none': 'Ainda não há serviços de música configurados neste sistema.',
  'mg.services.linked': 'Associado no Sonora',
  'mg.services.notLinked': 'Configurado na aplicação Sonos, ainda não associado no Sonora',
  'mg.alsoRemembered': 'Também memorizadas, mas fora de alcance: {names}.',
  'mg.noAnswer': 'sem resposta',
  'mg.favoritesEmpty': 'Tudo o que guardar como Favorito Sonos, em qualquer controlador, aparece aqui. A lista é guardada pelos altifalantes, por isso é a mesma em todo o lado.',
  'mg.playlistsEmpty': 'As Listas de reprodução Sonos são filas que guardou. Ainda não existe nenhuma neste sistema.',
  'mg.settings.account': 'Conta Sonos',
  'mg.settings.account.blurb': 'Inicie sessão para desbloquear mais funcionalidades.',
  'mg.settings.services': 'Serviços de música',
  'mg.settings.services.blurb': 'Os serviços de streaming que configurou.',
  'mg.settings.library': 'Biblioteca de música',
  'mg.settings.library.blurb': 'Pastas de música partilhadas na sua rede.',
  'mg.settings.time': 'Data e hora',
  'mg.settings.time.blurb': 'Definições de relógio e fuso horário.',
  'mg.settings.systems': 'Sistemas e divisões',
  'mg.settings.systems.blurb': 'Que dispositivos o Sonora vê na sua rede.',
  'mg.settings.parental': 'Filtros de conteúdo',
  'mg.settings.parental.blurb': 'Filtragem de conteúdo explícito.',
  'mg.settings.s2': 'Assistente de atualização',
  'mg.settings.s2.blurb': 'Atualize o seu sistema Sonos.',
  'mg.settings.network': 'Verificação da rede',
  'mg.settings.network.blurb': 'Identifique possíveis problemas de desempenho na sua rede.',
  'mg.settings.appearance': 'Aspeto',
  'mg.settings.appearance.blurb': 'O tema que o Sonora usa e o idioma em que fala.',
  'mg.settings.log': 'Registo',
  'mg.settings.log.blurb': 'O que correu mal recentemente, do mais recente para o mais antigo.',
  'mg.nav.listen': 'Ouvir',
  'mg.nav.browse': 'Explorar',
  'mg.showInBrowse': 'Mostrar em Explorar',
  'mg.collapseRail': 'Recolher a navegação',
  'mg.expandRail': 'Expandir a navegação',
  'mg.openPlayer': 'Abrir o leitor',
  'mg.closePlayer': 'Fechar o leitor',
  'mg.playModes': 'Modos de reprodução',
  'mg.upNext': 'A seguir',
  'mg.upNextAndRooms': 'A seguir e divisões',
  'mg.inThisRoom': 'Nesta divisão',
  'mg.soundAndRoom': 'Som e definições',
  'mg.allRooms': 'Todas as divisões',
  'mg.dragToReorder': 'Arraste para reordenar',
  'mg.playsIn': 'Toca em {room}',
  'mg.searchHint': 'Pesquise divisões, ações, favoritos ou um serviço',
  'mg.dynamicColor': 'Cores da capa',
  'mg.dynamicColorBody': 'Tinge toda a interface com as cores do que está a tocar na divisão apresentada.',
  'mg.reload': 'Recarregar',
}

const svSE = {
  'mg.name': 'Material Girl',
  'mg.nav.rooms': 'Rum',
  'mg.nav.clock': 'Väckningar',
  'mg.nav.settings': 'Inställningar',
  'mg.navigation': 'Avsnitt',
  'mg.all': 'Alla',
  'mg.greeting.morning': 'God morgon',
  'mg.greeting.afternoon': 'God eftermiddag',
  'mg.greeting.evening': 'God kväll',
  'mg.greeting.overnight': 'God natt',
  'mg.playingIn': 'Spelar i {rooms}',
  'mg.dragToGroup': 'Dra ett rum till ett annat för att gruppera dem.',
  'mg.groupAcrossSystems': 'Rum i olika system kan inte grupperas med varandra.',
  'mg.forRoom': 'för {room}',
  'mg.recent': 'Nyligen spelat',
  'mg.quietRooms.one': '{count} tyst rum',
  'mg.quietRooms.other': '{count} tysta rum',
  'mg.open': 'Öppna',
  'mg.playingNow': 'Spelar {title}',
  'mg.queuedNext': 'Spelar {title} härnäst',
  'mg.addedToQueue': '{title} lades till i kön',
  'mg.replacedQueue': 'Kön ersattes med {title}',
  'mg.queueEmptyBody': 'Spela något från Bibliotek, eller lägg till spår med ”Lägg till sist i kön”.',
  'mg.queueSaved': 'Kön sparades som ”{title}”',
  'mg.moveUp': 'Flytta upp',
  'mg.moveDown': 'Flytta ned',
  'mg.removeSelected': 'Ta bort {count} markerade',
  'mg.selected': '{count} markerade',
  'mg.editGroup': 'Redigera grupp',
  'mg.addRooms': 'Lägg till rum',
  'mg.leaveGroup': 'Ta ut {room} ur gruppen',
  'mg.thisRoom': 'Det här rummet',
  'mg.groupedWith': 'Grupperad med {room}',
  'mg.noPairCandidates': 'Ingen annan oparad högtalare av den här modellen.',
  'mg.lineIn': 'Linjeingång',
  'mg.connected': 'Ansluten',
  'mg.nothingConnected': 'Inget anslutet',
  'mg.none': 'Inga',
  'mg.musicSources': 'Musikkällor',
  'mg.activeRoom': 'Spelar i',
  'mg.chooseRoom': 'Välj ett rum',
  'mg.otherSystem': 'I {gen}-systemet; välj ett av dess rum för att spela från det',
  'mg.allServices': 'Alla tjänster',
  'mg.allServicesGen': 'Alla {gen}-tjänster',
  'mg.playOtherSystem': 'Det finns i {gen}-systemet. Välj ett av dess rum för att spela det.',
  'mg.view': 'Visning',
  'mg.viewAuto': 'Automatiskt',
  'mg.viewGrid': 'Rutnät',
  'mg.viewList': 'Lista',
  'mg.filterServices': 'Filtrera tjänster',
  'mg.searchIn': 'Sök efter ”{term}” i {service}',
  'mg.search.rooms': 'Rum',
  'mg.search.actions': 'Åtgärder',
  'mg.search.music': 'Musik',
  'mg.search.services': 'Musiktjänster',
  'mg.partyMode': 'Partyläge',
  'mg.serviceRemoved': '{service} togs bort',
  'mg.quality': 'Kvalitet',
  'mg.worst': 'sämst ms',
  'mg.wired': 'Trådbunden',
  'mg.noRooms': 'Inga rum i det här systemet.',
  'mg.services.none': 'Inga musiktjänster har konfigurerats i det här systemet än.',
  'mg.services.linked': 'Länkad i Sonora',
  'mg.services.notLinked': 'Konfigurerad i Sonos-appen, inte ännu länkad i Sonora',
  'mg.alsoRemembered': 'Minns också, men utom räckhåll: {names}.',
  'mg.noAnswer': 'inget svar',
  'mg.favoritesEmpty': 'Allt du sparar som Sonos-favorit, i valfri kontroller, visas här. Högtalarna håller listan, så den är densamma överallt.',
  'mg.playlistsEmpty': 'Sonos-spellistor är köer som du har sparat. Det finns inga i det här systemet än.',
  'mg.settings.account': 'Sonos-konto',
  'mg.settings.account.blurb': 'Logga in för att låsa upp fler funktioner.',
  'mg.settings.services': 'Musiktjänster',
  'mg.settings.services.blurb': 'Streamingtjänsterna du har konfigurerat.',
  'mg.settings.library': 'Musikbibliotek',
  'mg.settings.library.blurb': 'Delade musikmappar i ditt nätverk.',
  'mg.settings.time': 'Datum och tid',
  'mg.settings.time.blurb': 'Inställningar för klocka och tidszon.',
  'mg.settings.systems': 'System och rum',
  'mg.settings.systems.blurb': 'Vilka enheter Sonora ser i ditt nätverk.',
  'mg.settings.parental': 'Innehållsfilter',
  'mg.settings.parental.blurb': 'Filtrering av explicit innehåll.',
  'mg.settings.s2': 'Uppgraderingsguide',
  'mg.settings.s2.blurb': 'Uppgradera ditt Sonos-system.',
  'mg.settings.network': 'Nätverkskontroll',
  'mg.settings.network.blurb': 'Hitta möjliga prestandaproblem i ditt nätverk.',
  'mg.settings.appearance': 'Utseende',
  'mg.settings.appearance.blurb': 'Temat Sonora använder och språket den talar.',
  'mg.settings.log': 'Logg',
  'mg.settings.log.blurb': 'Vad som har gått fel nyligen, senaste först.',
  'mg.nav.listen': 'Lyssna',
  'mg.nav.browse': 'Bläddra',
  'mg.showInBrowse': 'Visa i Bläddra',
  'mg.collapseRail': 'Fäll ihop navigeringen',
  'mg.expandRail': 'Fäll ut navigeringen',
  'mg.openPlayer': 'Öppna spelaren',
  'mg.closePlayer': 'Stäng spelaren',
  'mg.playModes': 'Uppspelningslägen',
  'mg.upNext': 'Näst på tur',
  'mg.upNextAndRooms': 'Näst på tur och rum',
  'mg.inThisRoom': 'I det här rummet',
  'mg.soundAndRoom': 'Ljud och inställningar',
  'mg.allRooms': 'Alla rum',
  'mg.dragToReorder': 'Dra för att ändra ordning',
  'mg.playsIn': 'Spelar i {room}',
  'mg.searchHint': 'Sök efter rum, åtgärder, favoriter eller en tjänst',
  'mg.dynamicColor': 'Färger från omslaget',
  'mg.dynamicColorBody': 'Färgar hela gränssnittet i färgerna från det som spelas i rummet som visas.',
  'mg.reload': 'Läs in igen',
}

export default { 'en-US': enUS, 'es-ES': esES, 'hu-HU': huHU, 'fr-FR': frFR, 'de-DE': deDE, 'it-IT': itIT, 'pt-BR': ptBR, 'nl-NL': nlNL, 'uk-UA': ukUA, 'ja-JP': jaJP, 'ko-KR': koKR, 'zh-CN': zhCN, 'zh-TW': zhTW, 'cs-CZ': csCZ, 'da-DK': daDK, 'fi-FI': fiFI, 'nb-NO': nbNO, 'pl-PL': plPL, 'pt-PT': ptPT, 'sv-SE': svSE }
