"""What Sonora includes from others is credited, and nothing else slips in.

THIRD-PARTY-NOTICES.md reproduces the licenses of the open-source code and
artwork Sonora carries. A dependency added without regenerating
it fails here, and so does a picture added
to the repository that nobody has checked is Sonora's own: a Sonos bitmap
was once committed as is.
"""

import asyncio
import json
import pathlib
import re
import subprocess

from backend import main

ROOT = pathlib.Path(__file__).resolve().parent.parent
NOTICES = (ROOT.parent / "THIRD-PARTY-NOTICES.md").read_text(encoding="utf-8")

#: Every picture in the repository, each Sonora's own drawing.
OWN_PICTURES = {
    "app/frontend/public/apple-touch-icon.png",
    "app/frontend/public/favicon.ico",
    "app/frontend/src/assets/sonora.png",
    # The README's logo, uploaded by the project's author.
    "docs/sonora-wordmark.png",
    "docs/sonora-wordmark-noshadow.png",
    # A half-size copy of it, for the start-up and crash screens, the Sonos Web settings and the
    # Sedona header.
    "app/frontend/src/assets/wordmark-readme.png",
    # The Home Assistant app store's icon and logo: the touch icon at 128px and the wordmark cropped.
    "homeassistant/sonora/icon.png",
    "homeassistant/sonora/logo.png",
    # The README's hardware-generations timeline, drawn in SVG shapes and
    # text with no embedded images, uploaded by the project's author.
    "docs/sonos-hardware-generations-2026.svg",
    # Sedona's header photograph of the Sonoran Desert, generated by the project's author with ChatGPT and
    # cropped for the theme.
    "app/themes/sedona/landscape.webp",
}


def test_every_bundled_javascript_dependency_is_credited():
    deps = json.loads((ROOT / "frontend" / "package.json").read_text())["dependencies"]
    for name in deps:
        assert f"[{name}]" in NOTICES, name


def test_every_python_dependency_is_credited():
    text = (ROOT / "pyproject.toml").read_text()
    block = text[text.index("dependencies = ["):]
    block = block[:block.index("]")]
    for req in re.findall(r'"([A-Za-z0-9_.-]+)', block):
        assert re.search(rf"\[{re.escape(req)}\]", NOTICES, re.I), req


def test_the_license_texts_are_there():
    assert "Permission is hereby granted, free of charge" in NOTICES
    assert "TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION" in NOTICES
    assert "Pictogrammers Free License" in NOTICES
    assert ".NET Foundation and Contributors" in NOTICES


def test_the_about_windows_link_is_served():
    notices = asyncio.run(main.third_party_notices())
    assert notices.status_code == 200
    assert notices.body.decode("utf-8") == NOTICES
    license = asyncio.run(main.license_text())
    assert b"GNU AFFERO GENERAL PUBLIC LICENSE" in license.body


def test_no_picture_is_in_the_repository_that_is_not_accounted_for():
    tracked = subprocess.run(["git", "ls-files"], cwd=ROOT.parent, capture_output=True, text=True).stdout.split()
    pictures = {f for f in tracked
                if re.search(r"\.(png|jpe?g|gif|webp|svg|ico|tiff?|bmp|woff2?|ttf|otf)$", f, re.I)}
    thumbnails = {f for f in pictures if re.fullmatch(r"app/themes/[a-z0-9]+/thumbnail(-[a-z]+)?\.webp", f)}
    # The README's screenshots of Sonora itself: each theme in light, in dark,
    # and on a phone.
    screenshots = {f for f in pictures
                   if re.fullmatch(r"docs/screenshots/[a-z]+/((mobile-)?(home|nowplaying|service|player)(-dark)?|spread(-dark|-mobile)?)\.webp", f)}
    assert pictures - thumbnails - screenshots - set(THIRD_PARTY_FILES) == OWN_PICTURES


#: Files that are someone else's work, each with the name it is credited
#: under in THIRD-PARTY-NOTICES.md.
THIRD_PARTY_FILES = {
    "app/themes/hifi/permanent-marker.woff2": "Permanent Marker",
    "app/themes/materialgirl/fonts/roboto-flex-latin.woff2": "Roboto Flex",
    "app/themes/materialgirl/fonts/roboto-flex-latin-ext.woff2": "Roboto Flex",
    "app/themes/materialgirl/fonts/roboto-flex-cyrillic.woff2": "Roboto Flex",
    "app/themes/materialgirl/fonts/roboto-flex-cyrillic-ext.woff2": "Roboto Flex",
}


def test_every_third_party_file_is_credited():
    for path, name in THIRD_PARTY_FILES.items():
        assert (ROOT.parent / path).is_file(), path
        assert f"[{name}]" in NOTICES and f"### {name}" in NOTICES, name
